/**
 * Restaurant Subtypes
 * Comprehensive restaurant subtype definitions with realistic and varied options
 */

export const RESTAURANT_SUB_TYPES: Record<string, Record<string, {value: string, label: string}[]>> = {
  appetizers: {
    appetizer: [
      { value: 'cold', label: '🥒 Cold Appetizer' },
      { value: 'hot', label: '🔥 Hot Appetizer' },
      { value: 'fried', label: '🍟 Fried Appetizer' },
      { value: 'grilled', label: '🔥 Grilled Appetizer' },
      { value: 'baked', label: '🍕 Baked Appetizer' },
      { value: 'steamed', label: '💨 Steamed Appetizer' },
      { value: 'raw', label: '🥗 Raw Appetizer' },
      { value: 'marinated', label: '🫒 Marinated Appetizer' },
      { value: 'stuffed', label: '🥟 Stuffed Appetizer' },
      { value: 'dipped', label: '🫕 Dipped Appetizer' },
      { value: 'seafood', label: '🦐 Seafood Appetizer' },
      { value: 'vegetarian', label: '🥬 Vegetarian Appetizer' },
      { value: 'vegan', label: '🌱 Vegan Appetizer' },
      { value: 'gluten-free', label: '🌾 Gluten-Free Appetizer' },
      { value: 'dairy-free', label: '🥛 Dairy-Free Appetizer' },
      { value: 'nut-free', label: '🥜 Nut-Free Appetizer' },
      { value: 'spicy', label: '🌶️ Spicy Appetizer' },
      { value: 'mild', label: '😌 Mild Appetizer' },
      { value: 'sweet', label: '🍯 Sweet Appetizer' },
      { value: 'savory', label: '🧂 Savory Appetizer' },
      { value: 'shareable', label: '👥 Shareable Appetizer' },
      { value: 'individual', label: '👤 Individual Appetizer' },
      { value: 'platter', label: '🍽️ Appetizer Platter' },
      { value: 'sampler', label: '🎯 Appetizer Sampler' },
      { value: 'combo', label: '📦 Appetizer Combo' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Appetizer' },
      { value: 'party', label: '🎉 Party Appetizer' },
      { value: 'celebration', label: '🎊 Celebration Appetizer' },
      { value: 'classic', label: '🏛 Classic Appetizer' },
      { value: 'signature', label: '✍️ Signature Appetizer' },
      { value: 'seasonal', label: '🍂 Seasonal Appetizer' },
      { value: 'limited', label: '⏰ Limited Time Appetizer' },
      { value: 'specialty', label: '⭐ Specialty Appetizer' },
      { value: 'gourmet', label: '🍽️ Gourmet Appetizer' },
      { value: 'artisan', label: '🎨 Artisan Appetizer' },
      { value: 'imported', label: '🌍 Imported Appetizer' },
      { value: 'local', label: '🏠 Local Appetizer' },
      { value: 'organic', label: '🌱 Organic Appetizer' },
      { value: 'fresh', label: '🍎 Fresh Appetizer' },
      { value: 'house-special', label: '🏠 House Special Appetizer' },
      { value: 'chef-special', label: '👨‍🍳 Chef Special Appetizer' }
    ],
    side: [
      { value: 'small', label: '🥗 Small Side' },
      { value: 'medium', label: '🍽️ Medium Side' },
      { value: 'large', label: '🍽️ Large Side' },
      { value: 'shareable', label: '👥 Shareable Side' },
      { value: 'individual', label: '👤 Individual Side' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Side' },
      { value: 'party', label: '🎉 Party Side' },
      { value: 'vegetable', label: '🥬 Vegetable Side' },
      { value: 'starch', label: '🍟 Starch Side' },
      { value: 'salad', label: '🥗 Salad Side' },
      { value: 'bread', label: '🍞 Bread Side' },
      { value: 'potato', label: '🥔 Potato Side' },
      { value: 'rice', label: '🍚 Rice Side' },
      { value: 'pasta', label: '🍝 Pasta Side' },
      { value: 'grilled-vegetables', label: '🔥 Grilled Vegetables' },
      { value: 'steamed-vegetables', label: '💨 Steamed Vegetables' },
      { value: 'roasted-vegetables', label: '🔥 Roasted Vegetables' },
      { value: 'sautéed-vegetables', label: '🍳 Sautéed Vegetables' },
      { value: 'fried', label: '🍟 Fried Side' },
      { value: 'mashed-potatoes', label: '🥔 Mashed Potatoes' },
      { value: 'french-fries', label: '🍟 French Fries' },
      { value: 'sweet-potatoes', label: '🍠 Sweet Potatoes' },
      { value: 'corn', label: '🌽 Corn Side' },
      { value: 'beans', label: '🫘 Beans Side' },
      { value: 'coleslaw', label: '🥗 Coleslaw' },
      { value: 'mac-cheese', label: '🧀 Mac & Cheese' },
      { value: 'stuffing', label: '🍞 Stuffing' },
      { value: 'gravy', label: '🍲 Gravy' },
      { value: 'garlic-bread', label: '🧄 Garlic Bread' },
      { value: 'breadsticks', label: '🥖 Breadsticks' },
      { value: 'dinner-rolls', label: '🍞 Dinner Rolls' },
      { value: 'biscuits', label: '🍞 Biscuits' },
      { value: 'hush-puppies', label: '🍟 Hush Puppies' },
      { value: 'onion-rings', label: '🧅 Onion Rings' },
      { value: 'tater-tots', label: '🥔 Tater Tots' },
      { value: 'hash-browns', label: '🥔 Hash Browns' },
      { value: 'home-fries', label: '🍟 Home Fries' },
      { value: 'wedge-fries', label: '🍟 Wedge Fries' },
      { value: 'seasonal', label: '🍂 Seasonal Side' },
      { value: 'specialty', label: '⭐ Specialty Side' },
      { value: 'house', label: '🏠 House Side' },
      { value: 'chef', label: '👨‍🍳 Chef Side' }
    ],
    bundle: [
      { value: 'sampler', label: '🎯 Appetizer Sampler' },
      { value: 'combo', label: '📦 Appetizer Combo' },
      { value: 'platter', label: '🍽️ Appetizer Platter' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Platter' },
      { value: 'party', label: '🎉 Party Pack' },
      { value: 'variety-pack', label: '🎯 Variety Pack' },
      { value: 'assorted', label: '🥗 Assorted Appetizers' },
      { value: 'mixed-platter', label: '🍽️ Mixed Platter' },
      { value: 'seafood-sampler', label: '🦐 Seafood Sampler' },
      { value: 'vegetarian-sampler', label: '🥬 Vegetarian Sampler' },
      { value: 'vegan-sampler', label: '🌱 Vegan Sampler' },
      { value: 'meat-sampler', label: '🥩 Meat Sampler' },
      { value: 'cheese-sampler', label: '🧀 Cheese Sampler' },
      { value: 'dip-sampler', label: '🫕 Dip Sampler' },
      { value: 'cold-sampler', label: '🥒 Cold Sampler' },
      { value: 'hot-sampler', label: '🔥 Hot Sampler' },
      { value: 'fried-sampler', label: '🍟 Fried Sampler' },
      { value: 'grilled-sampler', label: '🔥 Grilled Sampler' },
      { value: 'baked-sampler', label: '🍕 Baked Sampler' },
      { value: 'international', label: '🌍 International Sampler' },
      { value: 'regional', label: '🗺️ Regional Sampler' },
      { value: 'seasonal', label: '🍂 Seasonal Sampler' },
      { value: 'holiday', label: '🎄 Holiday Sampler' },
      { value: 'celebration', label: '🎊 Celebration Sampler' },
      { value: 'corporate', label: '💼 Corporate Sampler' },
      { value: 'catering', label: '🍱 Catering Sampler' },
      { value: 'event', label: '🎪 Event Sampler' },
      { value: 'party-sampler', label: '🎉 Party Sampler' },
      { value: 'family-feast', label: '👨‍👩‍👧‍👦 Family Feast' },
      { value: 'gourmet', label: '🍽️ Gourmet Sampler' },
      { value: 'artisan', label: '🎨 Artisan Sampler' },
      { value: 'signature', label: '✍️ Signature Sampler' },
      { value: 'deluxe', label: '💎 Deluxe Sampler' },
      { value: 'premium', label: '👑 Premium Sampler' },
      { value: 'exclusive', label: '🔒 Exclusive Sampler' },
      { value: 'limited', label: '⏰ Limited Sampler' },
      { value: 'specialty', label: '⭐ Specialty Sampler' },
      { value: 'classic', label: '🏛 Classic Sampler' },
      { value: 'modern', label: '🆕 Modern Sampler' },
      { value: 'trending', label: '📈 Trending Sampler' }
    ]
  },
  entrees: {
    entree: [
      { value: 'beef', label: '🥩 Beef Entree' },
      { value: 'chicken', label: '🍗 Chicken Entree' },
      { value: 'pork', label: '🥓 Pork Entree' },
      { value: 'seafood', label: '🐟 Seafood Entree' },
      { value: 'vegetarian', label: '🥬 Vegetarian Entree' },
      { value: 'vegan', label: '🌱 Vegan Entree' },
      { value: 'lamb', label: '🐑 Lamb Entree' },
      { value: 'duck', label: '🦆 Duck Entree' },
      { value: 'turkey', label: '🦃 Turkey Entree' },
      { value: 'game', label: '🦌 Game Meat' },
      { value: 'pasta', label: '🍝 Pasta Entree' },
      { value: 'rice', label: '🍚 Rice Entree' },
      { value: 'stir-fry', label: '🥢 Stir Fry' },
      { value: 'curry', label: '🍛 Curry' },
      { value: 'roasted', label: '🔥 Roasted' },
      { value: 'grilled', label: '🔥 Grilled' },
      { value: 'pan-seared', label: '🍳 Pan Seared' },
      { value: 'braised', label: '🍲 Braised' },
      { value: 'steamed', label: '💨 Steamed' },
      { value: 'fried', label: '🍟 Fried' },
      { value: 'baked', label: '🍕 Baked' },
      { value: 'broiled', label: '🔥 Broiled' },
      { value: 'smoked', label: '💨 Smoked' },
      { value: 'slow-cooked', label: '⏰ Slow Cooked' },
      { value: 'pressure-cooked', label: '🔳 Pressure Cooked' },
      { value: 'sous-vide', label: '💧 Sous Vide' },
      { value: 'air-fried', label: '💨 Air Fried' },
      { value: 'deconstructed', label: '🔧 Deconstructed' },
      { value: 'fusion', label: '🍽️ Fusion' },
      { value: 'modern', label: '🆕 Modern' },
      { value: 'classic', label: '🏛 Classic' },
      { value: 'signature', label: '✍️ Signature' },
      { value: 'seasonal', label: '🍂 Seasonal' },
      { value: 'limited', label: '⏰ Limited Time' },
      { value: 'specialty', label: '⭐ Specialty' },
      { value: 'gourmet', label: '🍽️ Gourmet' },
      { value: 'artisan', label: '🎨 Artisan' },
      { value: 'house-special', label: '🏠 House Special' },
      { value: 'chef-special', label: '👨‍🍳 Chef Special' },
      { value: 'regional', label: '🗺️ Regional' },
      { value: 'international', label: '🌍 International' },
      { value: 'comfort', label: '🍲 Comfort' },
      { value: 'healthy', label: '🥗 Healthy' },
      { value: 'light', label: '😌 Light' },
      { value: 'hearty', label: '🍽️ Hearty' },
      { value: 'spicy', label: '🌶️ Spicy' },
      { value: 'mild', label: '😌 Mild' },
      { value: 'sweet', label: '🍯 Sweet' },
      { value: 'savory', label: '🧂 Savory' },
      { value: 'tangy', label: '🍋 Tangy' },
      { value: 'umami', label: '🍲 Umami' },
      { value: 'zesty', label: '🍋 Zesty' },
      { value: 'bold', label: '💪 Bold' },
      { value: 'subtle', label: '😌 Subtle' },
      { value: 'complex', label: '🧪 Complex' },
      { value: 'simple', label: '😊 Simple' },
      { value: 'elegant', label: '🎩 Elegant' },
      { value: 'rustic', label: '🏠 Rustic' },
      { value: 'refined', label: '💎 Refined' },
      { value: 'traditional', label: '🏛 Traditional' },
      { value: 'contemporary', label: '🆕 Contemporary' },
      { value: 'innovative', label: '💡 Innovative' },
      { value: 'experimental', label: '🧪 Experimental' },
      { value: 'authentic', label: '🌍 Authentic' },
      { value: 'inspired', label: '💭 Inspired' }
    ],
    bundle: [
      { value: 'dinner', label: '🍽️ Dinner Bundle' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Bundle' },
      { value: 'couple', label: '💑 Couple Bundle' },
      { value: 'executive', label: '💼 Executive Bundle' },
      { value: 'celebration', label: '🎉 Celebration Bundle' },
      { value: 'feast', label: '🍽️ Feast Bundle' },
      { value: 'banquet', label: '🎊 Banquet Bundle' },
      { value: 'gala', label: '🎊 Gala Bundle' },
      { value: 'party', label: '🎉 Party Bundle' },
      { value: 'event', label: '🎪 Event Bundle' },
      { value: 'catering', label: '🍱 Catering Bundle' },
      { value: 'corporate', label: '💼 Corporate Bundle' },
      { value: 'business', label: '💼 Business Bundle' },
      { value: 'meeting', label: '🤝 Meeting Bundle' },
      { value: 'conference', label: '🤝 Conference Bundle' },
      { value: 'workshop', label: '🛠️ Workshop Bundle' },
      { value: 'seminar', label: '🎓 Seminar Bundle' },
      { value: 'training', label: '🎓 Training Bundle' },
      { value: 'team-building', label: '👥 Team Building Bundle' },
      { value: 'holiday', label: '🎄 Holiday Bundle' },
      { value: 'seasonal', label: '🍂 Seasonal Bundle' },
      { value: 'special-occasion', label: '🎊 Special Occasion Bundle' },
      { value: 'anniversary', label: '🎂 Anniversary Bundle' },
      { value: 'birthday', label: '🎂 Birthday Bundle' },
      { value: 'graduation', label: '🎓 Graduation Bundle' },
      { value: 'promotion', label: '📈 Promotion Bundle' },
      { value: 'retirement', label: '👵 Retirement Bundle' },
      { value: 'wedding', label: '💒 Wedding Bundle' },
      { value: 'engagement', label: '💍 Engagement Bundle' },
      { value: 'milestone', label: '🏆 Milestone Bundle' },
      { value: 'achievement', label: '🏆 Achievement Bundle' },
      { value: 'recognition', label: '🏆 Recognition Bundle' },
      { value: 'appreciation', label: '🙏 Appreciation Bundle' },
      { value: 'thank-you', label: '🙏 Thank You Bundle' },
      { value: 'congratulations', label: '🎉 Congratulations Bundle' },
      { value: 'deluxe', label: '💎 Deluxe Bundle' },
      { value: 'premium', label: '👑 Premium Bundle' },
      { value: 'vip', label: '🌟 VIP Bundle' },
      { value: 'exclusive', label: '🔒 Exclusive Bundle' },
      { value: 'limited-edition', label: '⏰ Limited Edition Bundle' },
      { value: 'collector', label: '📦 Collector Bundle' },
      { value: 'signature', label: '✍️ Signature Bundle' },
      { value: 'classic', label: '🏛 Classic Bundle' },
      { value: 'traditional', label: '🏛 Traditional Bundle' },
      { value: 'modern', label: '🆕 Modern Bundle' },
      { value: 'contemporary', label: '🆕 Contemporary Bundle' },
      { value: 'innovative', label: '💡 Innovative Bundle' },
      { value: 'gourmet', label: '🍽️ Gourmet Bundle' },
      { value: 'artisan', label: '🎨 Artisan Bundle' },
      { value: 'handcrafted', label: '👐️ Handcrafted Bundle' },
      { value: 'custom', label: '🎨 Custom Bundle' },
      { value: 'personalized', label: '👤 Personalized Bundle' },
      { value: 'bespoke', label: '🎨 Bespoke Bundle' },
      { value: 'tailored', label: '👔 Tailored Bundle' },
      { value: 'curated', label: '🎨 Curated Bundle' },
      { value: 'themed', label: '🎭 Themed Bundle' }
    ]
  }
}

export type RestaurantSubType = typeof RESTAURANT_SUB_TYPES[string][string][number]

export function getRestaurantSubTypes(category: string, type: string): {value: string, label: string}[] {
  return RESTAURANT_SUB_TYPES[category]?.[type] || []
}

export function getRestaurantSubTypeByValue(category: string, type: string, value: string): RestaurantSubType | undefined {
  return RESTAURANT_SUB_TYPES[category]?.[type]?.find(subType => subType.value === value)
}

export function isRestaurantSubType(category: string, type: string, value: string): boolean {
  return RESTAURANT_SUB_TYPES[category]?.[type]?.some(subType => subType.value === value) || false
}

export function getAllRestaurantSubTypes(): typeof RESTAURANT_SUB_TYPES {
  return RESTAURANT_SUB_TYPES
}
