#!/usr/bin/env tsx
/**
 * Generate Frontend Types from DTOs
 * 
 * Parses Zod schemas directly from DTOs and generates TypeScript types
 * 100% reliable - no OpenAPI middleman, direct from source of truth
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Import all DTOs
import * as authDTO from '../src/dtos/auth.dto.js'
import * as storeDTO from '../src/dtos/store.dto.js'
import * as itemDTO from '../src/dtos/item.dto.js'
import * as cartDTO from '../src/dtos/cart.dto.js'
import * as orderDTO from '../src/dtos/order.dto.js'
import * as addressDTO from '../src/dtos/address.dto.js'
import * as promotionDTO from '../src/dtos/promotion.dto.js'
import * as tipDTO from '../src/dtos/tip.dto.js'
import * as userDTO from '../src/dtos/user.dto.js'
import * as riverDTO from '../src/dtos/river.dto.js'
import * as mediaDTO from '../src/dtos/media.dto.js'
import * as paymentDTO from '../src/dtos/payment.dto.js'
import { z } from 'zod'

console.log('🔄 Generating frontend types from DTOs...')

/**
 * Extract TypeScript type from Zod schema
 */
function zodToTypeString(schema: z.ZodTypeAny, typeName: string): string {
  // For now, use z.infer approach
  // This generates from the actual Zod schemas
  return `export type ${typeName} = z.infer<typeof ${typeName}Schema>`
}

/**
 * Generate type exports from DTO module
 */
function generateTypesFromDTO(dtoModule: any, moduleName: string): string[] {
  const types: string[] = []
  
  for (const [exportName, exportValue] of Object.entries(dtoModule)) {
    if (exportName.endsWith('Schema') && exportValue instanceof z.ZodType) {
      const typeName = exportName.replace('Schema', '')
      
      // Skip internal schemas
      if (typeName.includes('Internal') || typeName.includes('Private')) {
        continue
      }
      
      types.push(typeName)
    }
  }
  
  return types
}

// Generate the types file
const output: string[] = []

output.push(`/**
 * Frontend Types - Auto-Generated from Backend DTOs
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: pnpm generate:frontend-types
 * Source: packages/schemas/src/dtos/*.dto.ts
 * 
 * This file is 100% reliable - generated directly from Zod schemas
 * No OpenAPI middleman, no SDK generation needed
 */

import { z } from 'zod'
`)

// Import all schemas
const dtoModules = {
  auth: authDTO,
  store: storeDTO,
  item: itemDTO,
  cart: cartDTO,
  order: orderDTO,
  address: addressDTO,
  promotion: promotionDTO,
  tip: tipDTO,
  user: userDTO,
  river: riverDTO,
  media: mediaDTO,
  payment: paymentDTO,
}

// Import schemas
output.push(`// Import Zod schemas from DTOs`)
for (const [moduleName, module] of Object.entries(dtoModules)) {
  const types = generateTypesFromDTO(module, moduleName)
  if (types.length > 0) {
    const schemaNames = types.map(t => `${t}Schema`).join(', ')
    output.push(`import { ${schemaNames} } from '@packages/schemas/dtos/${moduleName}.dto'`)
  }
}

output.push(`\n// ========================================`)
output.push(`// Type Exports (inferred from Zod schemas)`)
output.push(`// ========================================\n`)

// Generate type exports
for (const [moduleName, module] of Object.entries(dtoModules)) {
  const types = generateTypesFromDTO(module, moduleName)
  
  if (types.length > 0) {
    output.push(`// ${moduleName.charAt(0).toUpperCase() + moduleName.slice(1)} Types`)
    for (const typeName of types) {
      output.push(`export type ${typeName} = z.infer<typeof ${typeName}Schema>`)
    }
    output.push('')
  }
}

// Add convenience type aliases
output.push(`// ========================================`)
output.push(`// Convenience Aliases`)
output.push(`// ========================================\n`)

output.push(`export type Store = StoreResponse`)
output.push(`export type Item = ItemResponse`)
output.push(`export type Cart = CartResponse`)
output.push(`export type Order = OrderResponse`)
output.push(`export type Address = AddressResponse`)
output.push(`export type User = UserResponse`)
output.push(`export type RiverPost = PostResponse`)
output.push(`export type RiverComment = CommentResponse\n`)

// Add enhanced types
output.push(`// ========================================`)
output.push(`// Enhanced Types`)
output.push(`// ========================================\n`)

output.push(`/** Store with calculated distance from user location */`)
output.push(`export interface StoreWithDistance extends StoreResponse {`)
output.push(`  distance?: number`)
output.push(`}\n`)

output.push(`/** Cart with calculated totals */`)
output.push(`export interface CartWithTotals extends CartResponse {`)
output.push(`  items: CartItemData[]`)
output.push(`  itemCount: number`)
output.push(`  subtotal: number`)
output.push(`  tax: number`)
output.push(`  total: number`)
output.push(`}\n`)

output.push(`/** Cart item with populated item data */`)
output.push(`export interface CartItemData {`)
output.push(`  id: string`)
output.push(`  cartId: string`)
output.push(`  itemId: string`)
output.push(`  item: Item`)
output.push(`  quantity: number`)
output.push(`  price: number`)
output.push(`  options?: Record<string, unknown>`)
output.push(`  specialInstructions?: string | null`)
output.push(`}\n`)

output.push(`/** Address snapshot for orders */`)
output.push(`export interface AddressSnapshot {`)
output.push(`  line1: string`)
output.push(`  line2?: string`)
output.push(`  city: string`)
output.push(`  state: string`)
output.push(`  postalCode: string`)
output.push(`  country?: string`)
output.push(`}\n`)

// Order status enum
output.push(`// Order status enum`)
output.push(`export type OrderStatus =`)
output.push(`  | 'PLACED'`)
output.push(`  | 'ACCEPTED'`)
output.push(`  | 'PREPARING'`)
output.push(`  | 'READY'`)
output.push(`  | 'OUT_FOR_DELIVERY'`)
output.push(`  | 'COMPLETED'`)
output.push(`  | 'CANCELED'\n`)

// Media item type
output.push(`// Media item type`)
output.push(`export type MediaItem = z.infer<typeof MediaItemSchema>\n`)

// River filters
output.push(`// River filters`)
output.push(`export interface RiverFilters {`)
output.push(`  storeId?: string`)
output.push(`  sortBy?: 'recent' | 'popular' | 'trending'`)
output.push(`  hasMedia?: boolean`)
output.push(`}\n`)

// Write the file
const outputPath = path.resolve(__dirname, '../../../apps/web/src/api/generated-types.ts')
fs.writeFileSync(outputPath, output.join('\n'))

console.log('✅ Generated:', outputPath)
console.log('📊 Types generated from DTOs - 100% reliable!')

