#!/usr/bin/env tsx
/**
 * Simple Smoke Test Script
 * 
 * Quick validation of the generation pipeline
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

interface TestResult {
  name: string
  status: 'pass' | 'fail' | 'skip'
  message: string
}

class SimpleSmokeTestRunner {
  private results: TestResult[] = []

  /**
   * Test OpenAPI spec exists and is valid
   */
  testOpenApiSpec(): void {
    const specPath = path.resolve(__dirname, '../../openapi/openapi.json')
    
    if (!fs.existsSync(specPath)) {
      this.addResult('openapi-spec', 'fail', 'OpenAPI spec file not found')
      return
    }

    try {
      const specContent = fs.readFileSync(specPath, 'utf-8')
      const spec = JSON.parse(specContent)
      
      if (!spec.openapi || !spec.paths || !spec.components) {
        this.addResult('openapi-spec', 'fail', 'Invalid OpenAPI structure')
        return
      }

      const endpointCount = Object.keys(spec.paths).length
      const schemaCount = Object.keys(spec.components?.schemas || {}).length
      
      this.addResult('openapi-spec', 'pass', 
        `OpenAPI spec valid: ${endpointCount} endpoints, ${schemaCount} schemas`)
    } catch (error) {
      this.addResult('openapi-spec', 'fail', `Invalid JSON: ${error}`)
    }
  }

  /**
   * Test DTOs are generated
   */
  testGeneratedDtos(): void {
    const dtosPath = path.resolve(__dirname, '../src/dtos')
    
    if (!fs.existsSync(dtosPath)) {
      this.addResult('generated-dtos', 'fail', 'DTOs directory not found')
      return
    }

    const dtoFiles = fs.readdirSync(dtosPath).filter(file => file.endsWith('.dto.ts'))
    const autoGeneratedDtos = dtoFiles.filter(file => {
      const content = fs.readFileSync(path.join(dtosPath, file), 'utf-8')
      return content.includes('Auto-Generated from Prisma')
    })

    this.addResult('generated-dtos', 'pass', 
      `Generated ${autoGeneratedDtos.length} DTOs from ${dtoFiles.length} total DTO files`)
  }

  /**
   * Test SDK is generated
   */
  testGeneratedSdk(): void {
    const sdkPath = path.resolve(__dirname, '../../sdk/src')
    
    if (!fs.existsSync(sdkPath)) {
      this.addResult('generated-sdk', 'skip', 'SDK not generated - run pnpm gen:sdk')
      return
    }

    const apiFiles = fs.readdirSync(path.join(sdkPath, 'apis')).filter(file => file.endsWith('.ts'))
    const modelFiles = fs.readdirSync(path.join(sdkPath, 'models')).filter(file => file.endsWith('.ts'))
    
    this.addResult('generated-sdk', 'pass', 
      `Generated SDK: ${apiFiles.length} API files, ${modelFiles.length} model files`)
  }

  /**
   * Test client hooks are generated
   */
  testGeneratedClientHooks(): void {
    const hooksPath = path.resolve(__dirname, '../../sdk/src/hooks/generated.ts')
    
    if (!fs.existsSync(hooksPath)) {
      this.addResult('generated-client-hooks', 'skip', 'Client hooks not generated - run pnpm gen:client')
      return
    }

    const content = fs.readFileSync(hooksPath, 'utf-8')
    const hookCount = (content.match(/export const use\w+/g) || []).length
    
    this.addResult('generated-client-hooks', 'pass', 
      `Generated ${hookCount} client hooks`)
  }

  /**
   * Test Prisma schema exists
   */
  testPrismaSchema(): void {
    const schemaPath = path.resolve(__dirname, '../../db/prisma/schema.prisma')
    
    if (!fs.existsSync(schemaPath)) {
      this.addResult('prisma-schema', 'fail', 'Prisma schema not found')
      return
    }

    const content = fs.readFileSync(schemaPath, 'utf-8')
    const modelCount = (content.match(/^model \w+/gm) || []).length
    const enumCount = (content.match(/^enum \w+/gm) || []).length
    
    this.addResult('prisma-schema', 'pass', 
      `Prisma schema: ${modelCount} models, ${enumCount} enums`)
  }

  /**
   * Test package.json scripts
   */
  testPackageScripts(): void {
    const packageJsonPath = path.resolve(__dirname, '../../../package.json')
    
    if (!fs.existsSync(packageJsonPath)) {
      this.addResult('package-scripts', 'fail', 'Root package.json not found')
      return
    }

    const content = fs.readFileSync(packageJsonPath, 'utf-8')
    const packageJson = JSON.parse(content)
    const scripts = packageJson.scripts || {}
    
    const requiredScripts = [
      'gen:dtos',
      'gen:openapi', 
      'gen:sdk',
      'gen:client',
      'gen:all',
      'smoke-test'
    ]

    const missingScripts = requiredScripts.filter(script => !scripts[script])
    
    if (missingScripts.length > 0) {
      this.addResult('package-scripts', 'fail', 
        `Missing scripts: ${missingScripts.join(', ')}`)
      return
    }

    this.addResult('package-scripts', 'pass', 
      `All required scripts present: ${requiredScripts.length} scripts`)
  }

  /**
   * Add test result
   */
  private addResult(name: string, status: 'pass' | 'fail' | 'skip', message: string): void {
    this.results.push({ name, status, message })
  }

  /**
   * Run all tests
   */
  runAllTests(): void {
    console.log('🧪 Running Simple Smoke Tests...\n')

    this.testPrismaSchema()
    this.testGeneratedDtos()
    this.testOpenApiSpec()
    this.testGeneratedSdk()
    this.testGeneratedClientHooks()
    this.testPackageScripts()

    this.printResults()
  }

  /**
   * Print results
   */
  private printResults(): void {
    console.log('\n📊 Smoke Test Results:')
    console.log('=' .repeat(50))

    const passed = this.results.filter(r => r.status === 'pass').length
    const failed = this.results.filter(r => r.status === 'fail').length
    const skipped = this.results.filter(r => r.status === 'skip').length

    console.log(`✅ Passed: ${passed}`)
    console.log(`❌ Failed: ${failed}`)
    console.log(`⏭️  Skipped: ${skipped}`)
    console.log(`📈 Total: ${this.results.length}`)

    console.log('\n📋 Detailed Results:')
    console.log('-'.repeat(50))

    this.results.forEach(result => {
      const icon = result.status === 'pass' ? '✅' : result.status === 'fail' ? '❌' : '⏭️'
      console.log(`${icon} ${result.name}`)
      console.log(`   ${result.message}`)
      console.log()
    })

    // Overall status
    if (failed === 0) {
      console.log('🎉 All smoke tests passed! Your generation pipeline is working correctly.')
    } else {
      console.log(`⚠️  ${failed} test(s) failed. Please check the issues above.`)
    }

    // Recommendations
    if (skipped > 0) {
      console.log('\n💡 Recommendations:')
      if (this.results.find(r => r.name === 'generated-sdk' && r.status === 'skip')) {
        console.log('   • Run: pnpm gen:sdk')
      }
      if (this.results.find(r => r.name === 'generated-client-hooks' && r.status === 'skip')) {
        console.log('   • Run: pnpm gen:client')
      }
    }
  }
}

// CLI usage
const runner = new SimpleSmokeTestRunner()
runner.runAllTests()
