#!/usr/bin/env tsx
/**
 * Working Smoke Test Script
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

console.log('🧪 Starting Working Smoke Test...\n')

// Test 1: Check if OpenAPI spec exists
console.log('1. Testing OpenAPI spec...')
const openApiPath = path.resolve(__dirname, '../../openapi/openapi.json')
if (fs.existsSync(openApiPath)) {
  try {
    const spec = JSON.parse(fs.readFileSync(openApiPath, 'utf-8'))
    const endpointCount = Object.keys(spec.paths || {}).length
    const schemaCount = Object.keys(spec.components?.schemas || {}).length
    console.log(`   ✅ OpenAPI spec found: ${endpointCount} endpoints, ${schemaCount} schemas`)
  } catch (error) {
    console.log(`   ❌ OpenAPI spec invalid: ${error}`)
  }
} else {
  console.log('   ❌ OpenAPI spec not found')
}

// Test 2: Check if DTOs are generated
console.log('\n2. Testing generated DTOs...')
const dtosPath = path.resolve(__dirname, '../src/dtos')
if (fs.existsSync(dtosPath)) {
  const dtoFiles = fs.readdirSync(dtosPath).filter(file => file.endsWith('.dto.ts'))
  const autoGenerated = dtoFiles.filter(file => {
    const content = fs.readFileSync(path.join(dtosPath, file), 'utf-8')
    return content.includes('Auto-Generated from Prisma')
  })
  console.log(`   ✅ Found ${autoGenerated.length} auto-generated DTOs out of ${dtoFiles.length} total`)
} else {
  console.log('   ❌ DTOs directory not found')
}

// Test 3: Check if SDK is generated
console.log('\n3. Testing generated SDK...')
const sdkPath = path.resolve(__dirname, '../../sdk/src')
if (fs.existsSync(sdkPath)) {
  const apiPath = path.join(sdkPath, 'apis')
  const modelPath = path.join(sdkPath, 'models')
  
  let apiCount = 0
  let modelCount = 0
  
  if (fs.existsSync(apiPath)) {
    apiCount = fs.readdirSync(apiPath).filter(file => file.endsWith('.ts')).length
  }
  
  if (fs.existsSync(modelPath)) {
    modelCount = fs.readdirSync(modelPath).filter(file => file.endsWith('.ts')).length
  }
  
  console.log(`   ✅ SDK generated: ${apiCount} API files, ${modelCount} model files`)
} else {
  console.log('   ⏭️  SDK not generated (run: pnpm gen:sdk)')
}

// Test 4: Check if client hooks are generated
console.log('\n4. Testing client hooks...')
const hooksPath = path.resolve(__dirname, '../../sdk/src/hooks/generated.ts')
if (fs.existsSync(hooksPath)) {
  const content = fs.readFileSync(hooksPath, 'utf-8')
  const hookCount = (content.match(/export const use\w+/g) || []).length
  console.log(`   ✅ Generated ${hookCount} client hooks`)
} else {
  console.log('   ⏭️  Client hooks not generated (run: pnpm gen:client)')
}

// Test 5: Check Prisma schema
console.log('\n5. Testing Prisma schema...')
const schemaPath = path.resolve(__dirname, '../../db/prisma/schema.prisma')
if (fs.existsSync(schemaPath)) {
  const content = fs.readFileSync(schemaPath, 'utf-8')
  const modelCount = (content.match(/^model \w+/gm) || []).length
  const enumCount = (content.match(/^enum \w+/gm) || []).length
  console.log(`   ✅ Prisma schema: ${modelCount} models, ${enumCount} enums`)
} else {
  console.log('   ❌ Prisma schema not found')
}

// Test 6: Check package.json scripts
console.log('\n6. Testing package scripts...')
const packageJsonPath = path.resolve(__dirname, '../../../package.json')
if (fs.existsSync(packageJsonPath)) {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'))
  const scripts = packageJson.scripts || {}
  
  const requiredScripts = ['gen:dtos', 'gen:openapi', 'gen:sdk', 'gen:client', 'gen:all', 'smoke-test']
  const missingScripts = requiredScripts.filter(script => !scripts[script])
  
  if (missingScripts.length === 0) {
    console.log(`   ✅ All required scripts present (${requiredScripts.length} scripts)`)
  } else {
    console.log(`   ❌ Missing scripts: ${missingScripts.join(', ')}`)
  }
} else {
  console.log('   ❌ Root package.json not found')
}

console.log('\n🎉 Smoke test completed!')
console.log('\n💡 To run full generation pipeline:')
console.log('   pnpm gen:all')
console.log('   pnpm gen:client')
