import { z } from 'zod';
export declare const CreateAddressInputSchema: z.ZodObject<{
    userId: z.ZodString;
    label: z.ZodOptional<z.ZodString>;
    contactName: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    line1: z.ZodString;
    line2: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    state: z.ZodString;
    postalCode: z.ZodString;
    country: z.ZodString;
    instructions: z.ZodOptional<z.ZodString>;
    geo: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    isDefault: z.ZodOptional<z.ZodBoolean>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    externalRef: z.ZodOptional<z.ZodString>;
    archivedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    userId: string;
    line1: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line2?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}, {
    userId: string;
    line1: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line2?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}>;
export declare const UpdateAddressInputSchema: z.ZodEffects<z.ZodObject<{
    userId: z.ZodOptional<z.ZodString>;
    label: z.ZodOptional<z.ZodString>;
    contactName: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    line1: z.ZodOptional<z.ZodString>;
    line2: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    state: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodOptional<z.ZodString>;
    country: z.ZodOptional<z.ZodString>;
    instructions: z.ZodOptional<z.ZodString>;
    geo: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    isDefault: z.ZodOptional<z.ZodBoolean>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    externalRef: z.ZodOptional<z.ZodString>;
    archivedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    userId?: string | undefined;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line1?: string | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
    country?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}, {
    userId?: string | undefined;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line1?: string | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
    country?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}>, {
    userId?: string | undefined;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line1?: string | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
    country?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}, {
    userId?: string | undefined;
    phone?: string | undefined;
    isActive?: boolean | undefined;
    label?: string | undefined;
    contactName?: string | undefined;
    line1?: string | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
    country?: string | undefined;
    instructions?: string | undefined;
    geo?: Record<string, unknown> | undefined;
    isDefault?: boolean | undefined;
    externalRef?: string | undefined;
    archivedAt?: string | undefined;
}>;
export declare const AddressResponseSchema: z.ZodObject<{
    userId: z.ZodString;
    user: z.ZodString;
    label: z.ZodNullable<z.ZodString>;
    contactName: z.ZodNullable<z.ZodString>;
    phone: z.ZodNullable<z.ZodString>;
    line1: z.ZodString;
    line2: z.ZodNullable<z.ZodString>;
    city: z.ZodString;
    state: z.ZodString;
    postalCode: z.ZodString;
    country: z.ZodString;
    instructions: z.ZodNullable<z.ZodString>;
    geo: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    isDefault: z.ZodNullable<z.ZodBoolean>;
    isActive: z.ZodNullable<z.ZodBoolean>;
    externalRef: z.ZodNullable<z.ZodString>;
    orders: z.ZodString;
    archivedAt: z.ZodNullable<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    user: string;
    userId: string;
    phone: string | null;
    orders: string;
    isActive: boolean | null;
    label: string | null;
    contactName: string | null;
    line1: string;
    line2: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    instructions: string | null;
    geo: Record<string, unknown> | null;
    isDefault: boolean | null;
    externalRef: string | null;
    archivedAt: string | null;
}, {
    user: string;
    userId: string;
    phone: string | null;
    orders: string;
    isActive: boolean | null;
    label: string | null;
    contactName: string | null;
    line1: string;
    line2: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    instructions: string | null;
    geo: Record<string, unknown> | null;
    isDefault: boolean | null;
    externalRef: string | null;
    archivedAt: string | null;
}>;
export declare const AddressListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        userId: z.ZodString;
        user: z.ZodString;
        label: z.ZodNullable<z.ZodString>;
        contactName: z.ZodNullable<z.ZodString>;
        phone: z.ZodNullable<z.ZodString>;
        line1: z.ZodString;
        line2: z.ZodNullable<z.ZodString>;
        city: z.ZodString;
        state: z.ZodString;
        postalCode: z.ZodString;
        country: z.ZodString;
        instructions: z.ZodNullable<z.ZodString>;
        geo: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        isDefault: z.ZodNullable<z.ZodBoolean>;
        isActive: z.ZodNullable<z.ZodBoolean>;
        externalRef: z.ZodNullable<z.ZodString>;
        orders: z.ZodString;
        archivedAt: z.ZodNullable<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        user: string;
        userId: string;
        phone: string | null;
        orders: string;
        isActive: boolean | null;
        label: string | null;
        contactName: string | null;
        line1: string;
        line2: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        instructions: string | null;
        geo: Record<string, unknown> | null;
        isDefault: boolean | null;
        externalRef: string | null;
        archivedAt: string | null;
    }, {
        user: string;
        userId: string;
        phone: string | null;
        orders: string;
        isActive: boolean | null;
        label: string | null;
        contactName: string | null;
        line1: string;
        line2: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        instructions: string | null;
        geo: Record<string, unknown> | null;
        isDefault: boolean | null;
        externalRef: string | null;
        archivedAt: string | null;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    data: {
        user: string;
        userId: string;
        phone: string | null;
        orders: string;
        isActive: boolean | null;
        label: string | null;
        contactName: string | null;
        line1: string;
        line2: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        instructions: string | null;
        geo: Record<string, unknown> | null;
        isDefault: boolean | null;
        externalRef: string | null;
        archivedAt: string | null;
    }[];
    page: number;
    limit: number;
}, {
    total: number;
    data: {
        user: string;
        userId: string;
        phone: string | null;
        orders: string;
        isActive: boolean | null;
        label: string | null;
        contactName: string | null;
        line1: string;
        line2: string | null;
        city: string;
        state: string;
        postalCode: string;
        country: string;
        instructions: string | null;
        geo: Record<string, unknown> | null;
        isDefault: boolean | null;
        externalRef: string | null;
        archivedAt: string | null;
    }[];
    page: number;
    limit: number;
}>;
export declare const AddressQuerySchema: z.ZodEffects<z.ZodObject<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>, {
    page: number;
    limit: number;
    filters: {};
    orderBy: {
        createdAt: string;
    };
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>;
export type CreateAddressInput = z.infer<typeof CreateAddressInputSchema>;
export type UpdateAddressInput = z.infer<typeof UpdateAddressInputSchema>;
export type AddressResponse = z.infer<typeof AddressResponseSchema>;
export type AddressListResponse = z.infer<typeof AddressListResponseSchema>;
export type AddressQuery = z.infer<typeof AddressQuerySchema>;
//# sourceMappingURL=address.dto.d.ts.map