import { z } from 'zod';
/** POST /orders — placement payload (server computes totals and rows). */
export declare const OrderPlacementInputSchema: z.ZodObject<{
    cartId: z.ZodString;
    deliveryType: z.ZodEnum<["DELIVERY", "PICKUP"]>;
    addressId: z.ZodOptional<z.ZodString>;
    tip: z.ZodOptional<z.ZodString>;
    /** Client geocode — preferred when Address.geo is missing */
    deliveryLatitude: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodString]>>;
    deliveryLongitude: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodString]>>;
}, "strip", z.ZodTypeAny, {
    deliveryType: "DELIVERY" | "PICKUP";
    cartId: string;
    deliveryLatitude?: string | number | undefined;
    deliveryLongitude?: string | number | undefined;
    tip?: string | undefined;
    addressId?: string | undefined;
}, {
    deliveryType: "DELIVERY" | "PICKUP";
    cartId: string;
    deliveryLatitude?: string | number | undefined;
    deliveryLongitude?: string | number | undefined;
    tip?: string | undefined;
    addressId?: string | undefined;
}>;
/** @deprecated internal bulk/admin shape; prefer OrderPlacementInputSchema for HTTP */
export declare const OrderFullRowCreateInputSchema: z.ZodObject<{
    userId: z.ZodString;
    storeId: z.ZodString;
    cartId: z.ZodOptional<z.ZodString>;
    status: z.ZodString;
    deliveryType: z.ZodString;
    paymentStatus: z.ZodString;
    subtotal: z.ZodString;
    fees: z.ZodString;
    tax: z.ZodString;
    tip: z.ZodString;
    total: z.ZodString;
    serviceFeePercent: z.ZodString;
    serviceFeeAmount: z.ZodString;
    netToVendor: z.ZodString;
    stripePaymentIntentId: z.ZodOptional<z.ZodString>;
    stripeChargeId: z.ZodOptional<z.ZodString>;
    stripeTransferId: z.ZodOptional<z.ZodString>;
    stripeApplicationFeeId: z.ZodOptional<z.ZodString>;
    stripeRefundId: z.ZodOptional<z.ZodString>;
    addressId: z.ZodOptional<z.ZodString>;
    addressSnapshot: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    cancelReason: z.ZodOptional<z.ZodString>;
    canceledBy: z.ZodOptional<z.ZodString>;
    canceledAt: z.ZodOptional<z.ZodString>;
    refundReason: z.ZodOptional<z.ZodString>;
    refundedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: string;
    deliveryType: string;
    tip: string;
    paymentStatus: string;
    subtotal: string;
    fees: string;
    tax: string;
    total: string;
    serviceFeePercent: string;
    serviceFeeAmount: string;
    netToVendor: string;
    userId: string;
    storeId: string;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}, {
    status: string;
    deliveryType: string;
    tip: string;
    paymentStatus: string;
    subtotal: string;
    fees: string;
    tax: string;
    total: string;
    serviceFeePercent: string;
    serviceFeeAmount: string;
    netToVendor: string;
    userId: string;
    storeId: string;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}>;
export declare const CreateOrderInputSchema: z.ZodObject<{
    cartId: z.ZodString;
    deliveryType: z.ZodEnum<["DELIVERY", "PICKUP"]>;
    addressId: z.ZodOptional<z.ZodString>;
    tip: z.ZodOptional<z.ZodString>;
    /** Client geocode — preferred when Address.geo is missing */
    deliveryLatitude: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodString]>>;
    deliveryLongitude: z.ZodOptional<z.ZodUnion<[z.ZodNumber, z.ZodString]>>;
}, "strip", z.ZodTypeAny, {
    deliveryType: "DELIVERY" | "PICKUP";
    cartId: string;
    deliveryLatitude?: string | number | undefined;
    deliveryLongitude?: string | number | undefined;
    tip?: string | undefined;
    addressId?: string | undefined;
}, {
    deliveryType: "DELIVERY" | "PICKUP";
    cartId: string;
    deliveryLatitude?: string | number | undefined;
    deliveryLongitude?: string | number | undefined;
    tip?: string | undefined;
    addressId?: string | undefined;
}>;
export declare const UpdateOrderInputSchema: z.ZodEffects<z.ZodObject<{
    userId: z.ZodOptional<z.ZodString>;
    storeId: z.ZodOptional<z.ZodString>;
    cartId: z.ZodOptional<z.ZodString>;
    status: z.ZodString;
    deliveryType: z.ZodString;
    paymentStatus: z.ZodString;
    subtotal: z.ZodOptional<z.ZodString>;
    fees: z.ZodOptional<z.ZodString>;
    tax: z.ZodOptional<z.ZodString>;
    tip: z.ZodOptional<z.ZodString>;
    total: z.ZodOptional<z.ZodString>;
    serviceFeePercent: z.ZodOptional<z.ZodString>;
    serviceFeeAmount: z.ZodOptional<z.ZodString>;
    netToVendor: z.ZodOptional<z.ZodString>;
    stripePaymentIntentId: z.ZodOptional<z.ZodString>;
    stripeChargeId: z.ZodOptional<z.ZodString>;
    stripeTransferId: z.ZodOptional<z.ZodString>;
    stripeApplicationFeeId: z.ZodOptional<z.ZodString>;
    stripeRefundId: z.ZodOptional<z.ZodString>;
    addressId: z.ZodOptional<z.ZodString>;
    addressSnapshot: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    cancelReason: z.ZodOptional<z.ZodString>;
    canceledBy: z.ZodOptional<z.ZodString>;
    canceledAt: z.ZodOptional<z.ZodString>;
    refundReason: z.ZodOptional<z.ZodString>;
    refundedAt: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: string;
    deliveryType: string;
    paymentStatus: string;
    tip?: string | undefined;
    subtotal?: string | undefined;
    fees?: string | undefined;
    tax?: string | undefined;
    total?: string | undefined;
    serviceFeePercent?: string | undefined;
    serviceFeeAmount?: string | undefined;
    netToVendor?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    userId?: string | undefined;
    storeId?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}, {
    status: string;
    deliveryType: string;
    paymentStatus: string;
    tip?: string | undefined;
    subtotal?: string | undefined;
    fees?: string | undefined;
    tax?: string | undefined;
    total?: string | undefined;
    serviceFeePercent?: string | undefined;
    serviceFeeAmount?: string | undefined;
    netToVendor?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    userId?: string | undefined;
    storeId?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}>, {
    status: string;
    deliveryType: string;
    paymentStatus: string;
    tip?: string | undefined;
    subtotal?: string | undefined;
    fees?: string | undefined;
    tax?: string | undefined;
    total?: string | undefined;
    serviceFeePercent?: string | undefined;
    serviceFeeAmount?: string | undefined;
    netToVendor?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    userId?: string | undefined;
    storeId?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}, {
    status: string;
    deliveryType: string;
    paymentStatus: string;
    tip?: string | undefined;
    subtotal?: string | undefined;
    fees?: string | undefined;
    tax?: string | undefined;
    total?: string | undefined;
    serviceFeePercent?: string | undefined;
    serviceFeeAmount?: string | undefined;
    netToVendor?: string | undefined;
    stripePaymentIntentId?: string | undefined;
    stripeChargeId?: string | undefined;
    stripeTransferId?: string | undefined;
    stripeApplicationFeeId?: string | undefined;
    stripeRefundId?: string | undefined;
    addressSnapshot?: Record<string, unknown> | undefined;
    cancelReason?: string | undefined;
    canceledBy?: string | undefined;
    canceledAt?: string | undefined;
    refundReason?: string | undefined;
    refundedAt?: string | undefined;
    userId?: string | undefined;
    storeId?: string | undefined;
    cartId?: string | undefined;
    addressId?: string | undefined;
}>;
export declare const OrderResponseSchema: z.ZodObject<{
    userId: z.ZodString;
    storeId: z.ZodString;
    cartId: z.ZodNullable<z.ZodString>;
    user: z.ZodString;
    store: z.ZodString;
    cart: z.ZodNullable<z.ZodString>;
    status: z.ZodString;
    deliveryType: z.ZodString;
    paymentStatus: z.ZodString;
    subtotal: z.ZodString;
    fees: z.ZodString;
    tax: z.ZodString;
    tip: z.ZodString;
    total: z.ZodString;
    serviceFeePercent: z.ZodString;
    serviceFeeAmount: z.ZodString;
    netToVendor: z.ZodString;
    stripePaymentIntentId: z.ZodNullable<z.ZodString>;
    stripeChargeId: z.ZodNullable<z.ZodString>;
    stripeTransferId: z.ZodNullable<z.ZodString>;
    stripeApplicationFeeId: z.ZodNullable<z.ZodString>;
    stripeRefundId: z.ZodNullable<z.ZodString>;
    addressId: z.ZodNullable<z.ZodString>;
    address: z.ZodNullable<z.ZodString>;
    addressSnapshot: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    deliveryLatitude: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
    deliveryLongitude: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
    deliveryDistanceMiles: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
    estimatedDeliveryAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    cancelReason: z.ZodNullable<z.ZodString>;
    canceledBy: z.ZodNullable<z.ZodString>;
    canceledAt: z.ZodNullable<z.ZodString>;
    refundReason: z.ZodNullable<z.ZodString>;
    refundedAt: z.ZodNullable<z.ZodString>;
    items: z.ZodString;
    events: z.ZodString;
    tips: z.ZodString;
    commissions: z.ZodString;
}, "strip", z.ZodTypeAny, {
    items: string;
    status: string;
    deliveryType: string;
    user: string;
    store: string;
    cart: string | null;
    tip: string;
    address: string | null;
    paymentStatus: string;
    subtotal: string;
    fees: string;
    tax: string;
    total: string;
    serviceFeePercent: string;
    serviceFeeAmount: string;
    netToVendor: string;
    stripePaymentIntentId: string | null;
    stripeChargeId: string | null;
    stripeTransferId: string | null;
    stripeApplicationFeeId: string | null;
    stripeRefundId: string | null;
    addressSnapshot: Record<string, unknown> | null;
    cancelReason: string | null;
    canceledBy: string | null;
    canceledAt: string | null;
    refundReason: string | null;
    refundedAt: string | null;
    events: string;
    tips: string;
    commissions: string;
    userId: string;
    storeId: string;
    cartId: string | null;
    addressId: string | null;
    deliveryLatitude?: string | number | null | undefined;
    deliveryLongitude?: string | number | null | undefined;
    deliveryDistanceMiles?: string | number | null | undefined;
    estimatedDeliveryAt?: string | null | undefined;
}, {
    items: string;
    status: string;
    deliveryType: string;
    user: string;
    store: string;
    cart: string | null;
    tip: string;
    address: string | null;
    paymentStatus: string;
    subtotal: string;
    fees: string;
    tax: string;
    total: string;
    serviceFeePercent: string;
    serviceFeeAmount: string;
    netToVendor: string;
    stripePaymentIntentId: string | null;
    stripeChargeId: string | null;
    stripeTransferId: string | null;
    stripeApplicationFeeId: string | null;
    stripeRefundId: string | null;
    addressSnapshot: Record<string, unknown> | null;
    cancelReason: string | null;
    canceledBy: string | null;
    canceledAt: string | null;
    refundReason: string | null;
    refundedAt: string | null;
    events: string;
    tips: string;
    commissions: string;
    userId: string;
    storeId: string;
    cartId: string | null;
    addressId: string | null;
    deliveryLatitude?: string | number | null | undefined;
    deliveryLongitude?: string | number | null | undefined;
    deliveryDistanceMiles?: string | number | null | undefined;
    estimatedDeliveryAt?: string | null | undefined;
}>;
export declare const OrderListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        userId: z.ZodString;
        storeId: z.ZodString;
        cartId: z.ZodNullable<z.ZodString>;
        user: z.ZodString;
        store: z.ZodString;
        cart: z.ZodNullable<z.ZodString>;
        status: z.ZodString;
        deliveryType: z.ZodString;
        paymentStatus: z.ZodString;
        subtotal: z.ZodString;
        fees: z.ZodString;
        tax: z.ZodString;
        tip: z.ZodString;
        total: z.ZodString;
        serviceFeePercent: z.ZodString;
        serviceFeeAmount: z.ZodString;
        netToVendor: z.ZodString;
        stripePaymentIntentId: z.ZodNullable<z.ZodString>;
        stripeChargeId: z.ZodNullable<z.ZodString>;
        stripeTransferId: z.ZodNullable<z.ZodString>;
        stripeApplicationFeeId: z.ZodNullable<z.ZodString>;
        stripeRefundId: z.ZodNullable<z.ZodString>;
        addressId: z.ZodNullable<z.ZodString>;
        address: z.ZodNullable<z.ZodString>;
        addressSnapshot: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        deliveryLatitude: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
        deliveryLongitude: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
        deliveryDistanceMiles: z.ZodOptional<z.ZodNullable<z.ZodUnion<[z.ZodString, z.ZodNumber]>>>;
        estimatedDeliveryAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        cancelReason: z.ZodNullable<z.ZodString>;
        canceledBy: z.ZodNullable<z.ZodString>;
        canceledAt: z.ZodNullable<z.ZodString>;
        refundReason: z.ZodNullable<z.ZodString>;
        refundedAt: z.ZodNullable<z.ZodString>;
        items: z.ZodString;
        events: z.ZodString;
        tips: z.ZodString;
        commissions: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        items: string;
        status: string;
        deliveryType: string;
        user: string;
        store: string;
        cart: string | null;
        tip: string;
        address: string | null;
        paymentStatus: string;
        subtotal: string;
        fees: string;
        tax: string;
        total: string;
        serviceFeePercent: string;
        serviceFeeAmount: string;
        netToVendor: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        stripeTransferId: string | null;
        stripeApplicationFeeId: string | null;
        stripeRefundId: string | null;
        addressSnapshot: Record<string, unknown> | null;
        cancelReason: string | null;
        canceledBy: string | null;
        canceledAt: string | null;
        refundReason: string | null;
        refundedAt: string | null;
        events: string;
        tips: string;
        commissions: string;
        userId: string;
        storeId: string;
        cartId: string | null;
        addressId: string | null;
        deliveryLatitude?: string | number | null | undefined;
        deliveryLongitude?: string | number | null | undefined;
        deliveryDistanceMiles?: string | number | null | undefined;
        estimatedDeliveryAt?: string | null | undefined;
    }, {
        items: string;
        status: string;
        deliveryType: string;
        user: string;
        store: string;
        cart: string | null;
        tip: string;
        address: string | null;
        paymentStatus: string;
        subtotal: string;
        fees: string;
        tax: string;
        total: string;
        serviceFeePercent: string;
        serviceFeeAmount: string;
        netToVendor: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        stripeTransferId: string | null;
        stripeApplicationFeeId: string | null;
        stripeRefundId: string | null;
        addressSnapshot: Record<string, unknown> | null;
        cancelReason: string | null;
        canceledBy: string | null;
        canceledAt: string | null;
        refundReason: string | null;
        refundedAt: string | null;
        events: string;
        tips: string;
        commissions: string;
        userId: string;
        storeId: string;
        cartId: string | null;
        addressId: string | null;
        deliveryLatitude?: string | number | null | undefined;
        deliveryLongitude?: string | number | null | undefined;
        deliveryDistanceMiles?: string | number | null | undefined;
        estimatedDeliveryAt?: string | null | undefined;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    data: {
        items: string;
        status: string;
        deliveryType: string;
        user: string;
        store: string;
        cart: string | null;
        tip: string;
        address: string | null;
        paymentStatus: string;
        subtotal: string;
        fees: string;
        tax: string;
        total: string;
        serviceFeePercent: string;
        serviceFeeAmount: string;
        netToVendor: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        stripeTransferId: string | null;
        stripeApplicationFeeId: string | null;
        stripeRefundId: string | null;
        addressSnapshot: Record<string, unknown> | null;
        cancelReason: string | null;
        canceledBy: string | null;
        canceledAt: string | null;
        refundReason: string | null;
        refundedAt: string | null;
        events: string;
        tips: string;
        commissions: string;
        userId: string;
        storeId: string;
        cartId: string | null;
        addressId: string | null;
        deliveryLatitude?: string | number | null | undefined;
        deliveryLongitude?: string | number | null | undefined;
        deliveryDistanceMiles?: string | number | null | undefined;
        estimatedDeliveryAt?: string | null | undefined;
    }[];
    page: number;
    limit: number;
}, {
    total: number;
    data: {
        items: string;
        status: string;
        deliveryType: string;
        user: string;
        store: string;
        cart: string | null;
        tip: string;
        address: string | null;
        paymentStatus: string;
        subtotal: string;
        fees: string;
        tax: string;
        total: string;
        serviceFeePercent: string;
        serviceFeeAmount: string;
        netToVendor: string;
        stripePaymentIntentId: string | null;
        stripeChargeId: string | null;
        stripeTransferId: string | null;
        stripeApplicationFeeId: string | null;
        stripeRefundId: string | null;
        addressSnapshot: Record<string, unknown> | null;
        cancelReason: string | null;
        canceledBy: string | null;
        canceledAt: string | null;
        refundReason: string | null;
        refundedAt: string | null;
        events: string;
        tips: string;
        commissions: string;
        userId: string;
        storeId: string;
        cartId: string | null;
        addressId: string | null;
        deliveryLatitude?: string | number | null | undefined;
        deliveryLongitude?: string | number | null | undefined;
        deliveryDistanceMiles?: string | number | null | undefined;
        estimatedDeliveryAt?: string | null | undefined;
    }[];
    page: number;
    limit: number;
}>;
export declare const OrderQuerySchema: z.ZodEffects<z.ZodObject<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>, {
    page: number;
    limit: number;
    filters: Record<string, unknown>;
    orderBy: {
        createdAt: "desc";
    };
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>;
export declare const UpdateOrderStatusSchema: z.ZodEffects<z.ZodObject<{
    status: z.ZodOptional<z.ZodEnum<["PLACED", "ACCEPTED", "PREPARING", "READY", "OUT_FOR_DELIVERY", "DELIVERED", "CANCELED"]>>;
    assignedToUserId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    note: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status?: "PLACED" | "ACCEPTED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELED" | undefined;
    assignedToUserId?: string | null | undefined;
    note?: string | undefined;
}, {
    status?: "PLACED" | "ACCEPTED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELED" | undefined;
    assignedToUserId?: string | null | undefined;
    note?: string | undefined;
}>, {
    status?: "PLACED" | "ACCEPTED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELED" | undefined;
    assignedToUserId?: string | null | undefined;
    note?: string | undefined;
}, {
    status?: "PLACED" | "ACCEPTED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "CANCELED" | undefined;
    assignedToUserId?: string | null | undefined;
    note?: string | undefined;
}>;
export type OrderPlacementInput = z.infer<typeof OrderPlacementInputSchema>;
export type CreateOrderInput = z.infer<typeof CreateOrderInputSchema>;
export type OrderFullRowCreateInput = z.infer<typeof OrderFullRowCreateInputSchema>;
export type UpdateOrderInput = z.infer<typeof UpdateOrderInputSchema>;
export type OrderResponse = z.infer<typeof OrderResponseSchema>;
export type OrderListResponse = z.infer<typeof OrderListResponseSchema>;
export type OrderQuery = z.infer<typeof OrderQuerySchema>;
export type UpdateOrderStatus = z.infer<typeof UpdateOrderStatusSchema>;
//# sourceMappingURL=order.dto.d.ts.map