import { z } from 'zod';
export declare const CreatePromotionInputSchema: z.ZodObject<{
    storeId: z.ZodOptional<z.ZodString>;
    code: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    type: z.ZodString;
    status: z.ZodOptional<z.ZodString>;
    value: z.ZodString;
    minOrderValue: z.ZodOptional<z.ZodString>;
    maxDiscount: z.ZodOptional<z.ZodString>;
    usageLimit: z.ZodOptional<z.ZodNumber>;
    usageCount: z.ZodOptional<z.ZodNumber>;
    usageLimitPerUser: z.ZodOptional<z.ZodNumber>;
    allowStacking: z.ZodOptional<z.ZodBoolean>;
    eligibleUserIds: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    excludedUserIds: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    validFrom: z.ZodString;
    validUntil: z.ZodString;
    isGlobal: z.ZodOptional<z.ZodBoolean>;
    createdById: z.ZodString;
}, "strip", z.ZodTypeAny, {
    code: string;
    type: string;
    value: string;
    name: string;
    createdById: string;
    validFrom: string;
    validUntil: string;
    description?: string | undefined;
    status?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    isGlobal?: boolean | undefined;
}, {
    code: string;
    type: string;
    value: string;
    name: string;
    createdById: string;
    validFrom: string;
    validUntil: string;
    description?: string | undefined;
    status?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    isGlobal?: boolean | undefined;
}>;
export declare const UpdatePromotionInputSchema: z.ZodEffects<z.ZodObject<{
    storeId: z.ZodOptional<z.ZodString>;
    code: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    type: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodString>;
    value: z.ZodOptional<z.ZodString>;
    minOrderValue: z.ZodOptional<z.ZodString>;
    maxDiscount: z.ZodOptional<z.ZodString>;
    usageLimit: z.ZodOptional<z.ZodNumber>;
    usageCount: z.ZodOptional<z.ZodNumber>;
    usageLimitPerUser: z.ZodOptional<z.ZodNumber>;
    allowStacking: z.ZodOptional<z.ZodBoolean>;
    eligibleUserIds: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    excludedUserIds: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    validFrom: z.ZodOptional<z.ZodString>;
    validUntil: z.ZodOptional<z.ZodString>;
    isGlobal: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    code?: string | undefined;
    type?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    value?: string | undefined;
    name?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
    isGlobal?: boolean | undefined;
}, {
    code?: string | undefined;
    type?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    value?: string | undefined;
    name?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
    isGlobal?: boolean | undefined;
}>, {
    code?: string | undefined;
    type?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    value?: string | undefined;
    name?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
    isGlobal?: boolean | undefined;
}, {
    code?: string | undefined;
    type?: string | undefined;
    description?: string | undefined;
    status?: string | undefined;
    value?: string | undefined;
    name?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    usageCount?: number | undefined;
    usageLimitPerUser?: number | undefined;
    allowStacking?: boolean | undefined;
    eligibleUserIds?: Record<string, unknown> | undefined;
    excludedUserIds?: Record<string, unknown> | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
    isGlobal?: boolean | undefined;
}>;
export declare const PromotionResponseSchema: z.ZodObject<{
    storeId: z.ZodNullable<z.ZodString>;
    store: z.ZodNullable<z.ZodString>;
    code: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    type: z.ZodString;
    status: z.ZodNullable<z.ZodString>;
    value: z.ZodString;
    minOrderValue: z.ZodNullable<z.ZodString>;
    maxDiscount: z.ZodNullable<z.ZodString>;
    usageLimit: z.ZodNullable<z.ZodNumber>;
    usageCount: z.ZodNullable<z.ZodNumber>;
    usageLimitPerUser: z.ZodNullable<z.ZodNumber>;
    allowStacking: z.ZodNullable<z.ZodBoolean>;
    eligibleUserIds: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    excludedUserIds: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    validFrom: z.ZodString;
    validUntil: z.ZodString;
    isGlobal: z.ZodNullable<z.ZodBoolean>;
    createdById: z.ZodString;
    createdBy: z.ZodString;
    redemptions: z.ZodString;
}, "strip", z.ZodTypeAny, {
    code: string;
    type: string;
    description: string | null;
    status: string | null;
    value: string;
    store: string | null;
    name: string;
    storeId: string | null;
    createdById: string;
    minOrderValue: string | null;
    maxDiscount: string | null;
    usageLimit: number | null;
    usageCount: number | null;
    usageLimitPerUser: number | null;
    allowStacking: boolean | null;
    eligibleUserIds: Record<string, unknown> | null;
    excludedUserIds: Record<string, unknown> | null;
    validFrom: string;
    validUntil: string;
    isGlobal: boolean | null;
    createdBy: string;
    redemptions: string;
}, {
    code: string;
    type: string;
    description: string | null;
    status: string | null;
    value: string;
    store: string | null;
    name: string;
    storeId: string | null;
    createdById: string;
    minOrderValue: string | null;
    maxDiscount: string | null;
    usageLimit: number | null;
    usageCount: number | null;
    usageLimitPerUser: number | null;
    allowStacking: boolean | null;
    eligibleUserIds: Record<string, unknown> | null;
    excludedUserIds: Record<string, unknown> | null;
    validFrom: string;
    validUntil: string;
    isGlobal: boolean | null;
    createdBy: string;
    redemptions: string;
}>;
export declare const PromotionListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        storeId: z.ZodNullable<z.ZodString>;
        store: z.ZodNullable<z.ZodString>;
        code: z.ZodString;
        name: z.ZodString;
        description: z.ZodNullable<z.ZodString>;
        type: z.ZodString;
        status: z.ZodNullable<z.ZodString>;
        value: z.ZodString;
        minOrderValue: z.ZodNullable<z.ZodString>;
        maxDiscount: z.ZodNullable<z.ZodString>;
        usageLimit: z.ZodNullable<z.ZodNumber>;
        usageCount: z.ZodNullable<z.ZodNumber>;
        usageLimitPerUser: z.ZodNullable<z.ZodNumber>;
        allowStacking: z.ZodNullable<z.ZodBoolean>;
        eligibleUserIds: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        excludedUserIds: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        validFrom: z.ZodString;
        validUntil: z.ZodString;
        isGlobal: z.ZodNullable<z.ZodBoolean>;
        createdById: z.ZodString;
        createdBy: z.ZodString;
        redemptions: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        code: string;
        type: string;
        description: string | null;
        status: string | null;
        value: string;
        store: string | null;
        name: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        usageCount: number | null;
        usageLimitPerUser: number | null;
        allowStacking: boolean | null;
        eligibleUserIds: Record<string, unknown> | null;
        excludedUserIds: Record<string, unknown> | null;
        validFrom: string;
        validUntil: string;
        isGlobal: boolean | null;
        createdBy: string;
        redemptions: string;
    }, {
        code: string;
        type: string;
        description: string | null;
        status: string | null;
        value: string;
        store: string | null;
        name: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        usageCount: number | null;
        usageLimitPerUser: number | null;
        allowStacking: boolean | null;
        eligibleUserIds: Record<string, unknown> | null;
        excludedUserIds: Record<string, unknown> | null;
        validFrom: string;
        validUntil: string;
        isGlobal: boolean | null;
        createdBy: string;
        redemptions: string;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    data: {
        code: string;
        type: string;
        description: string | null;
        status: string | null;
        value: string;
        store: string | null;
        name: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        usageCount: number | null;
        usageLimitPerUser: number | null;
        allowStacking: boolean | null;
        eligibleUserIds: Record<string, unknown> | null;
        excludedUserIds: Record<string, unknown> | null;
        validFrom: string;
        validUntil: string;
        isGlobal: boolean | null;
        createdBy: string;
        redemptions: string;
    }[];
    page: number;
    limit: number;
}, {
    total: number;
    data: {
        code: string;
        type: string;
        description: string | null;
        status: string | null;
        value: string;
        store: string | null;
        name: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        usageCount: number | null;
        usageLimitPerUser: number | null;
        allowStacking: boolean | null;
        eligibleUserIds: Record<string, unknown> | null;
        excludedUserIds: Record<string, unknown> | null;
        validFrom: string;
        validUntil: string;
        isGlobal: boolean | null;
        createdBy: string;
        redemptions: string;
    }[];
    page: number;
    limit: number;
}>;
export declare const PromotionQuerySchema: z.ZodEffects<z.ZodObject<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>, {
    page: number;
    limit: number;
    filters: {};
    orderBy: {
        createdAt: string;
    };
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>;
export type CreatePromotionInput = z.infer<typeof CreatePromotionInputSchema>;
export type UpdatePromotionInput = z.infer<typeof UpdatePromotionInputSchema>;
export type PromotionResponse = z.infer<typeof PromotionResponseSchema>;
export type PromotionListResponse = z.infer<typeof PromotionListResponseSchema>;
export type PromotionQuery = z.infer<typeof PromotionQuerySchema>;
//# sourceMappingURL=promotion.dto.d.ts.map