import { z } from 'zod';
export declare const PromotionTypeSchema: z.ZodEnum<["PERCENTAGE", "FIXED_AMOUNT", "FREE_ITEM", "FREE_DELIVERY"]>;
export declare const PromotionStatusSchema: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]>;
export declare const CreatePromotionInputSchema: z.ZodObject<{
    storeId: z.ZodOptional<z.ZodString>;
    code: z.ZodString;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["PERCENTAGE", "FIXED_AMOUNT", "FREE_ITEM", "FREE_DELIVERY"]>;
    value: z.ZodString;
    minOrderValue: z.ZodOptional<z.ZodString>;
    maxDiscount: z.ZodOptional<z.ZodString>;
    usageLimit: z.ZodOptional<z.ZodNumber>;
    validFrom: z.ZodString;
    validUntil: z.ZodString;
}, "strip", z.ZodTypeAny, {
    value: string;
    code: string;
    type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
    name: string;
    validFrom: string;
    validUntil: string;
    description?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
}, {
    value: string;
    code: string;
    type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
    name: string;
    validFrom: string;
    validUntil: string;
    description?: string | undefined;
    storeId?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
}>;
export declare const UpdatePromotionInputSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]>>;
    value: z.ZodOptional<z.ZodString>;
    minOrderValue: z.ZodOptional<z.ZodString>;
    maxDiscount: z.ZodOptional<z.ZodString>;
    usageLimit: z.ZodOptional<z.ZodNumber>;
    validFrom: z.ZodOptional<z.ZodString>;
    validUntil: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    value?: string | undefined;
    description?: string | undefined;
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    name?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
}, {
    value?: string | undefined;
    description?: string | undefined;
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    name?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
}>, {
    value?: string | undefined;
    description?: string | undefined;
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    name?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
}, {
    value?: string | undefined;
    description?: string | undefined;
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    name?: string | undefined;
    minOrderValue?: string | undefined;
    maxDiscount?: string | undefined;
    usageLimit?: number | undefined;
    validFrom?: string | undefined;
    validUntil?: string | undefined;
}>;
export declare const PromotionResponseSchema: z.ZodObject<{
    id: z.ZodString;
    storeId: z.ZodNullable<z.ZodString>;
    code: z.ZodString;
    name: z.ZodString;
    description: z.ZodNullable<z.ZodString>;
    type: z.ZodEnum<["PERCENTAGE", "FIXED_AMOUNT", "FREE_ITEM", "FREE_DELIVERY"]>;
    status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]>;
    value: z.ZodString;
    minOrderValue: z.ZodNullable<z.ZodString>;
    maxDiscount: z.ZodNullable<z.ZodString>;
    usageLimit: z.ZodNullable<z.ZodNumber>;
    usageCount: z.ZodNumber;
    validFrom: z.ZodString;
    validUntil: z.ZodString;
    isGlobal: z.ZodBoolean;
    createdById: z.ZodString;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    value: string;
    code: string;
    type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
    description: string | null;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
    name: string;
    id: string;
    createdAt: string;
    updatedAt: string;
    storeId: string | null;
    createdById: string;
    minOrderValue: string | null;
    maxDiscount: string | null;
    usageLimit: number | null;
    validFrom: string;
    validUntil: string;
    usageCount: number;
    isGlobal: boolean;
}, {
    value: string;
    code: string;
    type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
    description: string | null;
    status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
    name: string;
    id: string;
    createdAt: string;
    updatedAt: string;
    storeId: string | null;
    createdById: string;
    minOrderValue: string | null;
    maxDiscount: string | null;
    usageLimit: number | null;
    validFrom: string;
    validUntil: string;
    usageCount: number;
    isGlobal: boolean;
}>;
export declare const ListPromotionsQuerySchema: z.ZodEffects<z.ZodObject<{
    storeId: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]>>;
    isActive: z.ZodOptional<z.ZodEffects<z.ZodString, boolean, string>>;
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    storeId?: string | undefined;
    isActive?: boolean | undefined;
}, {
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    storeId?: string | undefined;
    page?: string | undefined;
    isActive?: string | undefined;
    limit?: string | undefined;
}>, {
    page: number;
    limit: number;
    filters: Record<string, unknown>;
    orderBy: {
        createdAt: "desc";
    };
}, {
    status?: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED" | undefined;
    storeId?: string | undefined;
    page?: string | undefined;
    isActive?: string | undefined;
    limit?: string | undefined;
}>;
export declare const PromotionListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        storeId: z.ZodNullable<z.ZodString>;
        code: z.ZodString;
        name: z.ZodString;
        description: z.ZodNullable<z.ZodString>;
        type: z.ZodEnum<["PERCENTAGE", "FIXED_AMOUNT", "FREE_ITEM", "FREE_DELIVERY"]>;
        status: z.ZodEnum<["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]>;
        value: z.ZodString;
        minOrderValue: z.ZodNullable<z.ZodString>;
        maxDiscount: z.ZodNullable<z.ZodString>;
        usageLimit: z.ZodNullable<z.ZodNumber>;
        usageCount: z.ZodNumber;
        validFrom: z.ZodString;
        validUntil: z.ZodString;
        isGlobal: z.ZodBoolean;
        createdById: z.ZodString;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        value: string;
        code: string;
        type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
        description: string | null;
        status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        validFrom: string;
        validUntil: string;
        usageCount: number;
        isGlobal: boolean;
    }, {
        value: string;
        code: string;
        type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
        description: string | null;
        status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        validFrom: string;
        validUntil: string;
        usageCount: number;
        isGlobal: boolean;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    data: {
        value: string;
        code: string;
        type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
        description: string | null;
        status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        validFrom: string;
        validUntil: string;
        usageCount: number;
        isGlobal: boolean;
    }[];
    total: number;
    page: number;
    limit: number;
}, {
    data: {
        value: string;
        code: string;
        type: "PERCENTAGE" | "FIXED_AMOUNT" | "FREE_ITEM" | "FREE_DELIVERY";
        description: string | null;
        status: "DRAFT" | "ACTIVE" | "PAUSED" | "EXPIRED";
        name: string;
        id: string;
        createdAt: string;
        updatedAt: string;
        storeId: string | null;
        createdById: string;
        minOrderValue: string | null;
        maxDiscount: string | null;
        usageLimit: number | null;
        validFrom: string;
        validUntil: string;
        usageCount: number;
        isGlobal: boolean;
    }[];
    total: number;
    page: number;
    limit: number;
}>;
export type CreatePromotionInput = z.infer<typeof CreatePromotionInputSchema>;
export type UpdatePromotionInput = z.infer<typeof UpdatePromotionInputSchema>;
export type PromotionResponse = z.infer<typeof PromotionResponseSchema>;
export type ListPromotionsQuery = z.infer<typeof ListPromotionsQuerySchema>;
export type PromotionListResponse = z.infer<typeof PromotionListResponseSchema>;
export type PromotionType = z.infer<typeof PromotionTypeSchema>;
export type PromotionStatus = z.infer<typeof PromotionStatusSchema>;
//# sourceMappingURL=promotion.dto.d.ts.map