import { z } from 'zod';
export declare const CreateStoreInputSchema: z.ZodObject<{
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodString;
    companyName: z.ZodOptional<z.ZodString>;
    taxId: z.ZodOptional<z.ZodString>;
    phone: z.ZodString;
    email: z.ZodString;
    website: z.ZodString;
    customDomain: z.ZodOptional<z.ZodString>;
    socialLinksJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    isPublished: z.ZodOptional<z.ZodBoolean>;
    status: z.ZodOptional<z.ZodEnum<["ACTIVE", "PAUSED", "DISABLED"]>>;
    disabledAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    disabledByUserId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    disabledReason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    deliveryEnabled: z.ZodOptional<z.ZodBoolean>;
    pickupEnabled: z.ZodOptional<z.ZodBoolean>;
    prepTimeMin: z.ZodOptional<z.ZodNumber>;
    feesJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    hoursJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    deliveryDistance: z.ZodOptional<z.ZodString>;
    deliveryCharge: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodString>;
    longitude: z.ZodOptional<z.ZodString>;
    addressStreet: z.ZodOptional<z.ZodString>;
    addressCity: z.ZodOptional<z.ZodString>;
    addressState: z.ZodOptional<z.ZodString>;
    addressZip: z.ZodOptional<z.ZodString>;
    addressCountry: z.ZodOptional<z.ZodString>;
    geocodedAt: z.ZodOptional<z.ZodString>;
    geocodeSource: z.ZodOptional<z.ZodString>;
    /**
     * Affiliate referral code captured client-side (e.g. /r/:slugOrCode landing).
     * Server resolves it to the affiliate id; raw `referredByAffiliateId` is intentionally
     * not accepted to prevent mass-assignment of arbitrary affiliates by the creator.
     */
    affiliateReferralCode: z.ZodOptional<z.ZodString>;
    stripeAccountId: z.ZodOptional<z.ZodString>;
    stripeOnboarded: z.ZodOptional<z.ZodBoolean>;
    commissionRate: z.ZodOptional<z.ZodString>;
    imageUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    affiliateReferralCode?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    affiliateReferralCode?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}>;
export declare const UpdateStoreInputSchema: z.ZodEffects<z.ZodObject<{
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodString;
    companyName: z.ZodOptional<z.ZodString>;
    taxId: z.ZodOptional<z.ZodString>;
    phone: z.ZodString;
    email: z.ZodString;
    website: z.ZodString;
    customDomain: z.ZodOptional<z.ZodString>;
    socialLinksJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodString>>;
    isPublished: z.ZodOptional<z.ZodBoolean>;
    status: z.ZodOptional<z.ZodEnum<["ACTIVE", "PAUSED", "DISABLED"]>>;
    disabledAt: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    disabledByUserId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    disabledReason: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    deliveryEnabled: z.ZodOptional<z.ZodBoolean>;
    pickupEnabled: z.ZodOptional<z.ZodBoolean>;
    prepTimeMin: z.ZodOptional<z.ZodNumber>;
    feesJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    hoursJson: z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    deliveryDistance: z.ZodOptional<z.ZodString>;
    deliveryCharge: z.ZodOptional<z.ZodString>;
    latitude: z.ZodOptional<z.ZodString>;
    longitude: z.ZodOptional<z.ZodString>;
    addressStreet: z.ZodOptional<z.ZodString>;
    addressCity: z.ZodOptional<z.ZodString>;
    addressState: z.ZodOptional<z.ZodString>;
    addressZip: z.ZodOptional<z.ZodString>;
    addressCountry: z.ZodOptional<z.ZodString>;
    geocodedAt: z.ZodOptional<z.ZodString>;
    geocodeSource: z.ZodOptional<z.ZodString>;
    stripeAccountId: z.ZodOptional<z.ZodString>;
    stripeOnboarded: z.ZodOptional<z.ZodBoolean>;
    commissionRate: z.ZodOptional<z.ZodString>;
    imageUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}>, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}, {
    description: string;
    name: string;
    email: string;
    phone: string;
    website: string;
    slug: string;
    status?: "ACTIVE" | "PAUSED" | "DISABLED" | undefined;
    companyName?: string | undefined;
    commissionRate?: string | undefined;
    taxId?: string | undefined;
    stripeAccountId?: string | undefined;
    customDomain?: string | undefined;
    socialLinksJson?: Record<string, string> | undefined;
    isPublished?: boolean | undefined;
    disabledAt?: string | null | undefined;
    disabledByUserId?: string | null | undefined;
    disabledReason?: string | null | undefined;
    deliveryEnabled?: boolean | undefined;
    pickupEnabled?: boolean | undefined;
    prepTimeMin?: number | undefined;
    feesJson?: Record<string, unknown> | undefined;
    hoursJson?: Record<string, unknown> | undefined;
    deliveryDistance?: string | undefined;
    deliveryCharge?: string | undefined;
    latitude?: string | undefined;
    longitude?: string | undefined;
    addressStreet?: string | undefined;
    addressCity?: string | undefined;
    addressState?: string | undefined;
    addressZip?: string | undefined;
    addressCountry?: string | undefined;
    geocodedAt?: string | undefined;
    geocodeSource?: string | undefined;
    stripeOnboarded?: boolean | undefined;
    imageUrl?: string | undefined;
}>;
export declare const StoreResponseSchema: z.ZodObject<{
    owner: z.ZodString;
    name: z.ZodString;
    slug: z.ZodString;
    description: z.ZodString;
    companyName: z.ZodNullable<z.ZodString>;
    taxId: z.ZodNullable<z.ZodString>;
    phone: z.ZodString;
    email: z.ZodString;
    website: z.ZodString;
    customDomain: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    socialLinksJson: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodString>>>;
    isPublished: z.ZodNullable<z.ZodBoolean>;
    status: z.ZodNullable<z.ZodEnum<["ACTIVE", "PAUSED", "DISABLED"]>>;
    disabledAt: z.ZodNullable<z.ZodString>;
    disabledByUserId: z.ZodNullable<z.ZodString>;
    disabledReason: z.ZodNullable<z.ZodString>;
    deliveryEnabled: z.ZodNullable<z.ZodBoolean>;
    pickupEnabled: z.ZodNullable<z.ZodBoolean>;
    prepTimeMin: z.ZodNullable<z.ZodNumber>;
    feesJson: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    hoursJson: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    deliveryDistance: z.ZodNullable<z.ZodString>;
    deliveryCharge: z.ZodNullable<z.ZodString>;
    deliveryZones: z.ZodString;
    latitude: z.ZodNullable<z.ZodString>;
    longitude: z.ZodNullable<z.ZodString>;
    addressStreet: z.ZodNullable<z.ZodString>;
    addressCity: z.ZodNullable<z.ZodString>;
    addressState: z.ZodNullable<z.ZodString>;
    addressZip: z.ZodNullable<z.ZodString>;
    addressCountry: z.ZodNullable<z.ZodString>;
    geocodedAt: z.ZodNullable<z.ZodString>;
    geocodeSource: z.ZodNullable<z.ZodString>;
    referredByAffiliateId: z.ZodNullable<z.ZodString>;
    referredByAffiliate: z.ZodNullable<z.ZodString>;
    stripeAccountId: z.ZodNullable<z.ZodString>;
    stripeOnboarded: z.ZodNullable<z.ZodBoolean>;
    stripeChargesEnabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    stripePayoutsEnabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
    acceptsOnlineCardPayments: z.ZodOptional<z.ZodBoolean>;
    commissionRate: z.ZodNullable<z.ZodString>;
    media: z.ZodString;
    items: z.ZodString;
    orders: z.ZodString;
    carts: z.ZodString;
    posts: z.ZodString;
    bundles: z.ZodString;
    teamMembers: z.ZodString;
    invitations: z.ZodString;
    Promotion: z.ZodString;
    FavoriteStore: z.ZodString;
}, "strip", z.ZodTypeAny, {
    items: string;
    description: string;
    status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
    Promotion: string;
    FavoriteStore: string;
    name: string;
    referredByAffiliate: string | null;
    referredByAffiliateId: string | null;
    email: string;
    phone: string;
    companyName: string | null;
    carts: string;
    orders: string;
    commissionRate: string | null;
    taxId: string | null;
    website: string;
    stripeAccountId: string | null;
    slug: string;
    isPublished: boolean | null;
    disabledAt: string | null;
    disabledByUserId: string | null;
    disabledReason: string | null;
    deliveryEnabled: boolean | null;
    pickupEnabled: boolean | null;
    prepTimeMin: number | null;
    feesJson: Record<string, unknown> | null;
    hoursJson: Record<string, unknown> | null;
    deliveryDistance: string | null;
    deliveryCharge: string | null;
    latitude: string | null;
    longitude: string | null;
    addressStreet: string | null;
    addressCity: string | null;
    addressState: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    geocodedAt: string | null;
    geocodeSource: string | null;
    stripeOnboarded: boolean | null;
    owner: string;
    deliveryZones: string;
    media: string;
    posts: string;
    bundles: string;
    teamMembers: string;
    invitations: string;
    customDomain?: string | null | undefined;
    socialLinksJson?: Record<string, string> | null | undefined;
    stripeChargesEnabled?: boolean | null | undefined;
    stripePayoutsEnabled?: boolean | null | undefined;
    acceptsOnlineCardPayments?: boolean | undefined;
}, {
    items: string;
    description: string;
    status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
    Promotion: string;
    FavoriteStore: string;
    name: string;
    referredByAffiliate: string | null;
    referredByAffiliateId: string | null;
    email: string;
    phone: string;
    companyName: string | null;
    carts: string;
    orders: string;
    commissionRate: string | null;
    taxId: string | null;
    website: string;
    stripeAccountId: string | null;
    slug: string;
    isPublished: boolean | null;
    disabledAt: string | null;
    disabledByUserId: string | null;
    disabledReason: string | null;
    deliveryEnabled: boolean | null;
    pickupEnabled: boolean | null;
    prepTimeMin: number | null;
    feesJson: Record<string, unknown> | null;
    hoursJson: Record<string, unknown> | null;
    deliveryDistance: string | null;
    deliveryCharge: string | null;
    latitude: string | null;
    longitude: string | null;
    addressStreet: string | null;
    addressCity: string | null;
    addressState: string | null;
    addressZip: string | null;
    addressCountry: string | null;
    geocodedAt: string | null;
    geocodeSource: string | null;
    stripeOnboarded: boolean | null;
    owner: string;
    deliveryZones: string;
    media: string;
    posts: string;
    bundles: string;
    teamMembers: string;
    invitations: string;
    customDomain?: string | null | undefined;
    socialLinksJson?: Record<string, string> | null | undefined;
    stripeChargesEnabled?: boolean | null | undefined;
    stripePayoutsEnabled?: boolean | null | undefined;
    acceptsOnlineCardPayments?: boolean | undefined;
}>;
export declare const StoreListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        owner: z.ZodString;
        name: z.ZodString;
        slug: z.ZodString;
        description: z.ZodString;
        companyName: z.ZodNullable<z.ZodString>;
        taxId: z.ZodNullable<z.ZodString>;
        phone: z.ZodString;
        email: z.ZodString;
        website: z.ZodString;
        customDomain: z.ZodOptional<z.ZodNullable<z.ZodString>>;
        socialLinksJson: z.ZodOptional<z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodString>>>;
        isPublished: z.ZodNullable<z.ZodBoolean>;
        status: z.ZodNullable<z.ZodEnum<["ACTIVE", "PAUSED", "DISABLED"]>>;
        disabledAt: z.ZodNullable<z.ZodString>;
        disabledByUserId: z.ZodNullable<z.ZodString>;
        disabledReason: z.ZodNullable<z.ZodString>;
        deliveryEnabled: z.ZodNullable<z.ZodBoolean>;
        pickupEnabled: z.ZodNullable<z.ZodBoolean>;
        prepTimeMin: z.ZodNullable<z.ZodNumber>;
        feesJson: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        hoursJson: z.ZodNullable<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        deliveryDistance: z.ZodNullable<z.ZodString>;
        deliveryCharge: z.ZodNullable<z.ZodString>;
        deliveryZones: z.ZodString;
        latitude: z.ZodNullable<z.ZodString>;
        longitude: z.ZodNullable<z.ZodString>;
        addressStreet: z.ZodNullable<z.ZodString>;
        addressCity: z.ZodNullable<z.ZodString>;
        addressState: z.ZodNullable<z.ZodString>;
        addressZip: z.ZodNullable<z.ZodString>;
        addressCountry: z.ZodNullable<z.ZodString>;
        geocodedAt: z.ZodNullable<z.ZodString>;
        geocodeSource: z.ZodNullable<z.ZodString>;
        referredByAffiliateId: z.ZodNullable<z.ZodString>;
        referredByAffiliate: z.ZodNullable<z.ZodString>;
        stripeAccountId: z.ZodNullable<z.ZodString>;
        stripeOnboarded: z.ZodNullable<z.ZodBoolean>;
        stripeChargesEnabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
        stripePayoutsEnabled: z.ZodOptional<z.ZodNullable<z.ZodBoolean>>;
        acceptsOnlineCardPayments: z.ZodOptional<z.ZodBoolean>;
        commissionRate: z.ZodNullable<z.ZodString>;
        media: z.ZodString;
        items: z.ZodString;
        orders: z.ZodString;
        carts: z.ZodString;
        posts: z.ZodString;
        bundles: z.ZodString;
        teamMembers: z.ZodString;
        invitations: z.ZodString;
        Promotion: z.ZodString;
        FavoriteStore: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        items: string;
        description: string;
        status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
        Promotion: string;
        FavoriteStore: string;
        name: string;
        referredByAffiliate: string | null;
        referredByAffiliateId: string | null;
        email: string;
        phone: string;
        companyName: string | null;
        carts: string;
        orders: string;
        commissionRate: string | null;
        taxId: string | null;
        website: string;
        stripeAccountId: string | null;
        slug: string;
        isPublished: boolean | null;
        disabledAt: string | null;
        disabledByUserId: string | null;
        disabledReason: string | null;
        deliveryEnabled: boolean | null;
        pickupEnabled: boolean | null;
        prepTimeMin: number | null;
        feesJson: Record<string, unknown> | null;
        hoursJson: Record<string, unknown> | null;
        deliveryDistance: string | null;
        deliveryCharge: string | null;
        latitude: string | null;
        longitude: string | null;
        addressStreet: string | null;
        addressCity: string | null;
        addressState: string | null;
        addressZip: string | null;
        addressCountry: string | null;
        geocodedAt: string | null;
        geocodeSource: string | null;
        stripeOnboarded: boolean | null;
        owner: string;
        deliveryZones: string;
        media: string;
        posts: string;
        bundles: string;
        teamMembers: string;
        invitations: string;
        customDomain?: string | null | undefined;
        socialLinksJson?: Record<string, string> | null | undefined;
        stripeChargesEnabled?: boolean | null | undefined;
        stripePayoutsEnabled?: boolean | null | undefined;
        acceptsOnlineCardPayments?: boolean | undefined;
    }, {
        items: string;
        description: string;
        status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
        Promotion: string;
        FavoriteStore: string;
        name: string;
        referredByAffiliate: string | null;
        referredByAffiliateId: string | null;
        email: string;
        phone: string;
        companyName: string | null;
        carts: string;
        orders: string;
        commissionRate: string | null;
        taxId: string | null;
        website: string;
        stripeAccountId: string | null;
        slug: string;
        isPublished: boolean | null;
        disabledAt: string | null;
        disabledByUserId: string | null;
        disabledReason: string | null;
        deliveryEnabled: boolean | null;
        pickupEnabled: boolean | null;
        prepTimeMin: number | null;
        feesJson: Record<string, unknown> | null;
        hoursJson: Record<string, unknown> | null;
        deliveryDistance: string | null;
        deliveryCharge: string | null;
        latitude: string | null;
        longitude: string | null;
        addressStreet: string | null;
        addressCity: string | null;
        addressState: string | null;
        addressZip: string | null;
        addressCountry: string | null;
        geocodedAt: string | null;
        geocodeSource: string | null;
        stripeOnboarded: boolean | null;
        owner: string;
        deliveryZones: string;
        media: string;
        posts: string;
        bundles: string;
        teamMembers: string;
        invitations: string;
        customDomain?: string | null | undefined;
        socialLinksJson?: Record<string, string> | null | undefined;
        stripeChargesEnabled?: boolean | null | undefined;
        stripePayoutsEnabled?: boolean | null | undefined;
        acceptsOnlineCardPayments?: boolean | undefined;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    data: {
        items: string;
        description: string;
        status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
        Promotion: string;
        FavoriteStore: string;
        name: string;
        referredByAffiliate: string | null;
        referredByAffiliateId: string | null;
        email: string;
        phone: string;
        companyName: string | null;
        carts: string;
        orders: string;
        commissionRate: string | null;
        taxId: string | null;
        website: string;
        stripeAccountId: string | null;
        slug: string;
        isPublished: boolean | null;
        disabledAt: string | null;
        disabledByUserId: string | null;
        disabledReason: string | null;
        deliveryEnabled: boolean | null;
        pickupEnabled: boolean | null;
        prepTimeMin: number | null;
        feesJson: Record<string, unknown> | null;
        hoursJson: Record<string, unknown> | null;
        deliveryDistance: string | null;
        deliveryCharge: string | null;
        latitude: string | null;
        longitude: string | null;
        addressStreet: string | null;
        addressCity: string | null;
        addressState: string | null;
        addressZip: string | null;
        addressCountry: string | null;
        geocodedAt: string | null;
        geocodeSource: string | null;
        stripeOnboarded: boolean | null;
        owner: string;
        deliveryZones: string;
        media: string;
        posts: string;
        bundles: string;
        teamMembers: string;
        invitations: string;
        customDomain?: string | null | undefined;
        socialLinksJson?: Record<string, string> | null | undefined;
        stripeChargesEnabled?: boolean | null | undefined;
        stripePayoutsEnabled?: boolean | null | undefined;
        acceptsOnlineCardPayments?: boolean | undefined;
    }[];
    page: number;
    limit: number;
}, {
    total: number;
    data: {
        items: string;
        description: string;
        status: "ACTIVE" | "PAUSED" | "DISABLED" | null;
        Promotion: string;
        FavoriteStore: string;
        name: string;
        referredByAffiliate: string | null;
        referredByAffiliateId: string | null;
        email: string;
        phone: string;
        companyName: string | null;
        carts: string;
        orders: string;
        commissionRate: string | null;
        taxId: string | null;
        website: string;
        stripeAccountId: string | null;
        slug: string;
        isPublished: boolean | null;
        disabledAt: string | null;
        disabledByUserId: string | null;
        disabledReason: string | null;
        deliveryEnabled: boolean | null;
        pickupEnabled: boolean | null;
        prepTimeMin: number | null;
        feesJson: Record<string, unknown> | null;
        hoursJson: Record<string, unknown> | null;
        deliveryDistance: string | null;
        deliveryCharge: string | null;
        latitude: string | null;
        longitude: string | null;
        addressStreet: string | null;
        addressCity: string | null;
        addressState: string | null;
        addressZip: string | null;
        addressCountry: string | null;
        geocodedAt: string | null;
        geocodeSource: string | null;
        stripeOnboarded: boolean | null;
        owner: string;
        deliveryZones: string;
        media: string;
        posts: string;
        bundles: string;
        teamMembers: string;
        invitations: string;
        customDomain?: string | null | undefined;
        socialLinksJson?: Record<string, string> | null | undefined;
        stripeChargesEnabled?: boolean | null | undefined;
        stripePayoutsEnabled?: boolean | null | undefined;
        acceptsOnlineCardPayments?: boolean | undefined;
    }[];
    page: number;
    limit: number;
}>;
export declare const StoreQuerySchema: z.ZodEffects<z.ZodObject<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "passthrough", z.ZodTypeAny, z.objectOutputType<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, z.ZodTypeAny, "passthrough">, z.objectInputType<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, z.ZodTypeAny, "passthrough">>, {
    page: number;
    limit: number;
    filters: {};
    orderBy: {
        createdAt: string;
    };
}, z.objectInputType<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, z.ZodTypeAny, "passthrough">>;
export type CreateStoreInput = z.infer<typeof CreateStoreInputSchema>;
export type UpdateStoreInput = z.infer<typeof UpdateStoreInputSchema>;
export type StoreResponse = z.infer<typeof StoreResponseSchema>;
export type StoreListResponse = z.infer<typeof StoreListResponseSchema>;
export type StoreQuery = z.infer<typeof StoreQuerySchema>;
//# sourceMappingURL=store.dto.d.ts.map