import { z } from 'zod';
// ========================================
// Store DTOs (Auto-Generated from Prisma)
// ========================================
export const CreateStoreInputSchema = z.object({
    name: z.string(),
    slug: z.string(),
    description: z.string(),
    companyName: z.string().optional(),
    taxId: z.string().optional(),
    phone: z.string(),
    email: z.string(),
    website: z.string(),
    customDomain: z.string().optional(),
    socialLinksJson: z.record(z.string()).optional(),
    isPublished: z.boolean().optional(),
    status: z.enum(['ACTIVE', 'PAUSED', 'DISABLED']).optional(),
    disabledAt: z.string().datetime().nullable().optional(),
    disabledByUserId: z.string().nullable().optional(),
    disabledReason: z.string().nullable().optional(),
    deliveryEnabled: z.boolean().optional(),
    pickupEnabled: z.boolean().optional(),
    prepTimeMin: z.number().int().optional(),
    feesJson: z.record(z.unknown()).optional(),
    hoursJson: z.record(z.unknown()).optional(),
    deliveryDistance: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    deliveryCharge: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    latitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').optional(),
    longitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').optional(),
    addressStreet: z.string().optional(),
    addressCity: z.string().optional(),
    addressState: z.string().optional(),
    addressZip: z.string().optional(),
    addressCountry: z.string().optional(),
    geocodedAt: z.string().datetime().optional(),
    geocodeSource: z.string().optional(),
    /**
     * Affiliate referral code captured client-side (e.g. /r/:slugOrCode landing).
     * Server resolves it to the affiliate id; raw `referredByAffiliateId` is intentionally
     * not accepted to prevent mass-assignment of arbitrary affiliates by the creator.
     */
    affiliateReferralCode: z.string().trim().min(1).max(64).optional(),
    stripeAccountId: z.string().optional(),
    stripeOnboarded: z.boolean().optional(),
    commissionRate: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    imageUrl: z.string().optional(),
});
export const UpdateStoreInputSchema = z.object({
    name: z.string(),
    slug: z.string(),
    description: z.string(),
    companyName: z.string().optional(),
    taxId: z.string().optional(),
    phone: z.string(),
    email: z.string(),
    website: z.string(),
    customDomain: z.string().optional(),
    socialLinksJson: z.record(z.string()).optional(),
    isPublished: z.boolean().optional(),
    status: z.enum(['ACTIVE', 'PAUSED', 'DISABLED']).optional(),
    disabledAt: z.string().datetime().nullable().optional(),
    disabledByUserId: z.string().nullable().optional(),
    disabledReason: z.string().nullable().optional(),
    deliveryEnabled: z.boolean().optional(),
    pickupEnabled: z.boolean().optional(),
    prepTimeMin: z.number().int().optional(),
    feesJson: z.record(z.unknown()).optional(),
    hoursJson: z.record(z.unknown()).optional(),
    deliveryDistance: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    deliveryCharge: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    latitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').optional(),
    longitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').optional(),
    addressStreet: z.string().optional(),
    addressCity: z.string().optional(),
    addressState: z.string().optional(),
    addressZip: z.string().optional(),
    addressCountry: z.string().optional(),
    geocodedAt: z.string().datetime().optional(),
    geocodeSource: z.string().optional(),
    stripeAccountId: z.string().optional(),
    stripeOnboarded: z.boolean().optional(),
    commissionRate: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').optional(),
    imageUrl: z.string().optional(),
}).refine(data => Object.keys(data).length > 0, 'At least one field must be provided');
export const StoreResponseSchema = z.object({
    owner: z.string(),
    name: z.string(),
    slug: z.string(),
    description: z.string(),
    companyName: z.string().nullable(),
    taxId: z.string().nullable(),
    phone: z.string(),
    email: z.string(),
    website: z.string(),
    customDomain: z.string().nullable().optional(),
    socialLinksJson: z.record(z.string()).nullable().optional(),
    isPublished: z.boolean().nullable(),
    status: z.enum(['ACTIVE', 'PAUSED', 'DISABLED']).nullable(),
    disabledAt: z.string().datetime().nullable(),
    disabledByUserId: z.string().nullable(),
    disabledReason: z.string().nullable(),
    deliveryEnabled: z.boolean().nullable(),
    pickupEnabled: z.boolean().nullable(),
    prepTimeMin: z.number().int().nullable(),
    feesJson: z.record(z.unknown()).nullable(),
    hoursJson: z.record(z.unknown()).nullable(),
    deliveryDistance: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').nullable(),
    deliveryCharge: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').nullable(),
    deliveryZones: z.string(),
    latitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').nullable(),
    longitude: z.string().regex(/^-?\d+(\.\d+)?$/, 'Must be a valid decimal').nullable(),
    addressStreet: z.string().nullable(),
    addressCity: z.string().nullable(),
    addressState: z.string().nullable(),
    addressZip: z.string().nullable(),
    addressCountry: z.string().nullable(),
    geocodedAt: z.string().datetime().nullable(),
    geocodeSource: z.string().nullable(),
    referredByAffiliateId: z.string().nullable(),
    referredByAffiliate: z.string().nullable(),
    stripeAccountId: z.string().nullable(),
    stripeOnboarded: z.boolean().nullable(),
    stripeChargesEnabled: z.boolean().nullable().optional(),
    stripePayoutsEnabled: z.boolean().nullable().optional(),
    acceptsOnlineCardPayments: z.boolean().optional(),
    commissionRate: z.string().regex(/^\d+(\.\d{1,2})?$/, 'Must be a valid decimal').nullable(),
    media: z.string(),
    items: z.string(),
    orders: z.string(),
    carts: z.string(),
    posts: z.string(),
    bundles: z.string(),
    teamMembers: z.string(),
    invitations: z.string(),
    Promotion: z.string(),
    FavoriteStore: z.string()
});
export const StoreListResponseSchema = z.object({
    data: z.array(StoreResponseSchema),
    total: z.number(),
    page: z.number(),
    limit: z.number(),
});
export const StoreQuerySchema = z.object({
    page: z.string().transform(Number).default('1'),
    limit: z.string().transform(Number).default('20'),
}).passthrough().transform(data => ({
    page: data.page,
    limit: data.limit,
    filters: Object.keys(data)
        .filter(k => k !== 'page' && k !== 'limit' && data[k] !== undefined)
        .reduce((acc, k) => ({ ...acc, [k]: data[k] }), {}),
    orderBy: { createdAt: 'desc' },
}));
