import { z } from 'zod';
export declare const CreateUserInputSchema: z.ZodObject<{
    role: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    name: z.ZodString;
    phone: z.ZodString;
    isCompany: z.ZodOptional<z.ZodBoolean>;
    companyName: z.ZodOptional<z.ZodString>;
    affiliate: z.ZodOptional<z.ZodString>;
    vendorVerification: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}>;
export declare const UpdateUserInputSchema: z.ZodEffects<z.ZodObject<{
    role: z.ZodOptional<z.ZodString>;
    email: z.ZodString;
    name: z.ZodString;
    phone: z.ZodString;
    isCompany: z.ZodOptional<z.ZodBoolean>;
    companyName: z.ZodOptional<z.ZodString>;
    affiliate: z.ZodOptional<z.ZodString>;
    vendorVerification: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}>, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}, {
    name: string;
    email: string;
    phone: string;
    affiliate?: string | undefined;
    vendorVerification?: string | undefined;
    role?: string | undefined;
    isCompany?: boolean | undefined;
    companyName?: string | undefined;
}>;
export declare const UserResponseSchema: z.ZodObject<{
    role: z.ZodNullable<z.ZodString>;
    email: z.ZodString;
    name: z.ZodString;
    phone: z.ZodString;
    isCompany: z.ZodNullable<z.ZodBoolean>;
    companyName: z.ZodNullable<z.ZodString>;
    addresses: z.ZodString;
    carts: z.ZodString;
    orders: z.ZodString;
    storesOwned: z.ZodString;
    paymentMethods: z.ZodString;
    promotionsCreated: z.ZodString;
    postLikes: z.ZodString;
    comments: z.ZodString;
    affiliate: z.ZodNullable<z.ZodString>;
    vendorVerification: z.ZodNullable<z.ZodString>;
    teamMemberships: z.ZodString;
    invitationsSent: z.ZodString;
    invitationsReceived: z.ZodString;
    FavoriteStore: z.ZodString;
    FavoriteItem: z.ZodString;
}, "strip", z.ZodTypeAny, {
    affiliate: string | null;
    vendorVerification: string | null;
    FavoriteStore: string;
    FavoriteItem: string;
    name: string;
    role: string | null;
    email: string;
    phone: string;
    isCompany: boolean | null;
    companyName: string | null;
    addresses: string;
    carts: string;
    orders: string;
    storesOwned: string;
    paymentMethods: string;
    promotionsCreated: string;
    postLikes: string;
    comments: string;
    teamMemberships: string;
    invitationsSent: string;
    invitationsReceived: string;
}, {
    affiliate: string | null;
    vendorVerification: string | null;
    FavoriteStore: string;
    FavoriteItem: string;
    name: string;
    role: string | null;
    email: string;
    phone: string;
    isCompany: boolean | null;
    companyName: string | null;
    addresses: string;
    carts: string;
    orders: string;
    storesOwned: string;
    paymentMethods: string;
    promotionsCreated: string;
    postLikes: string;
    comments: string;
    teamMemberships: string;
    invitationsSent: string;
    invitationsReceived: string;
}>;
export declare const UserListResponseSchema: z.ZodObject<{
    data: z.ZodArray<z.ZodObject<{
        role: z.ZodNullable<z.ZodString>;
        email: z.ZodString;
        name: z.ZodString;
        phone: z.ZodString;
        isCompany: z.ZodNullable<z.ZodBoolean>;
        companyName: z.ZodNullable<z.ZodString>;
        addresses: z.ZodString;
        carts: z.ZodString;
        orders: z.ZodString;
        storesOwned: z.ZodString;
        paymentMethods: z.ZodString;
        promotionsCreated: z.ZodString;
        postLikes: z.ZodString;
        comments: z.ZodString;
        affiliate: z.ZodNullable<z.ZodString>;
        vendorVerification: z.ZodNullable<z.ZodString>;
        teamMemberships: z.ZodString;
        invitationsSent: z.ZodString;
        invitationsReceived: z.ZodString;
        FavoriteStore: z.ZodString;
        FavoriteItem: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        affiliate: string | null;
        vendorVerification: string | null;
        FavoriteStore: string;
        FavoriteItem: string;
        name: string;
        role: string | null;
        email: string;
        phone: string;
        isCompany: boolean | null;
        companyName: string | null;
        addresses: string;
        carts: string;
        orders: string;
        storesOwned: string;
        paymentMethods: string;
        promotionsCreated: string;
        postLikes: string;
        comments: string;
        teamMemberships: string;
        invitationsSent: string;
        invitationsReceived: string;
    }, {
        affiliate: string | null;
        vendorVerification: string | null;
        FavoriteStore: string;
        FavoriteItem: string;
        name: string;
        role: string | null;
        email: string;
        phone: string;
        isCompany: boolean | null;
        companyName: string | null;
        addresses: string;
        carts: string;
        orders: string;
        storesOwned: string;
        paymentMethods: string;
        promotionsCreated: string;
        postLikes: string;
        comments: string;
        teamMemberships: string;
        invitationsSent: string;
        invitationsReceived: string;
    }>, "many">;
    total: z.ZodNumber;
    page: z.ZodNumber;
    limit: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    data: {
        affiliate: string | null;
        vendorVerification: string | null;
        FavoriteStore: string;
        FavoriteItem: string;
        name: string;
        role: string | null;
        email: string;
        phone: string;
        isCompany: boolean | null;
        companyName: string | null;
        addresses: string;
        carts: string;
        orders: string;
        storesOwned: string;
        paymentMethods: string;
        promotionsCreated: string;
        postLikes: string;
        comments: string;
        teamMemberships: string;
        invitationsSent: string;
        invitationsReceived: string;
    }[];
    page: number;
    limit: number;
}, {
    total: number;
    data: {
        affiliate: string | null;
        vendorVerification: string | null;
        FavoriteStore: string;
        FavoriteItem: string;
        name: string;
        role: string | null;
        email: string;
        phone: string;
        isCompany: boolean | null;
        companyName: string | null;
        addresses: string;
        carts: string;
        orders: string;
        storesOwned: string;
        paymentMethods: string;
        promotionsCreated: string;
        postLikes: string;
        comments: string;
        teamMemberships: string;
        invitationsSent: string;
        invitationsReceived: string;
    }[];
    page: number;
    limit: number;
}>;
export declare const UserQuerySchema: z.ZodEffects<z.ZodObject<{
    page: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    limit: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    page: number;
    limit: number;
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>, {
    page: number;
    limit: number;
    filters: {};
    orderBy: {
        createdAt: string;
    };
}, {
    page?: string | undefined;
    limit?: string | undefined;
}>;
export type CreateUserInput = z.infer<typeof CreateUserInputSchema>;
export type UpdateUserInput = z.infer<typeof UpdateUserInputSchema>;
export type UserResponse = z.infer<typeof UserResponseSchema>;
export type UserListResponse = z.infer<typeof UserListResponseSchema>;
export type UserQuery = z.infer<typeof UserQuerySchema>;
//# sourceMappingURL=user.dto.d.ts.map