/**
 * Item Classification Data
 * Centralized mock data for categories, types, and subtypes
 * with utility functions for dynamic form handling
 * Now supports store type specific categorization
 * Refactored into modular files for better maintainability
 */

// Import restaurant data from modular files
import { RESTAURANT_CATEGORIES } from './categories/restaurantCategories'
import { RESTAURANT_ITEM_TYPES } from './itemTypes/restaurantItemTypes'
import { RESTAURANT_SUB_TYPES } from './subTypes/restaurantSubTypes'

// ============================================
// Store Type Specific Categories
// ============================================

export const STORE_TYPE_CATEGORIES: Record<string, {value: string, label: string}[]> = {
  RESTAURANT: RESTAURANT_CATEGORIES,
  CONVENIENCE: [
    { value: 'snacks', label: '🍿 Snacks' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'frozen-foods', label: '🧊 Frozen Foods' },
    { value: 'prepared-meals', label: '🍱 Prepared Meals' },
    { value: 'household', label: '🏠 Household Items' },
    { value: 'personal-care', label: '🧴 Personal Care' },
    { value: 'tobacco', label: '🚬 Tobacco Products' },
    { value: 'lottery', label: '🎰 Lottery' },
    { value: 'candy-chocolate', label: '🍫 Candy & Chocolate' },
    { value: 'chips-crackers', label: '🥨 Chips & Crackers' },
    { value: 'nuts-seeds', label: '🥜 Nuts & Seeds' },
    { value: 'jerky-meat-snacks', label: '🥓 Jerky & Meat Snacks' },
    { value: 'energy-bars', label: '🍫 Energy & Protein Bars' },
    { value: 'dairy-snacks', label: '🧀 Dairy Snacks' },
    { value: 'fruit-snacks', label: '🍎 Fruit Snacks' },
    { value: 'soft-drinks', label: '🥤 Soft Drinks' },
    { value: 'sports-energy', label: '⚡ Sports & Energy Drinks' },
    { value: 'bottled-water', label: '💧 Bottled Water' },
    { value: 'juice-drinks', label: '🧃 Juice & Drinks' },
    { value: 'coffee-tea', label: '☕ Coffee & Tea' },
    { value: 'frozen-pizza', label: '🍕 Frozen Pizza' },
    { value: 'frozen-entrees', label: '🍽️ Frozen Entrees' },
    { value: 'ice-cream-frozen-desserts', label: '🍦 Ice Cream & Frozen Desserts' },
    { value: 'frozen-breakfast', label: '🥞 Frozen Breakfast' },
    { value: 'hot-pockets-sandwiches', label: '🥪 Hot Pockets & Sandwiches' },
    { value: 'microwave-meals', label: '📦 Microwave Meals' },
    { value: 'cleaning-supplies', label: '🧹 Cleaning Supplies' },
    { value: 'paper-products', label: '🧻 Paper Products' },
    { value: 'batteries', label: '🔋 Batteries' },
    { value: 'automotive', label: '🚗 Automotive' },
    { value: 'pet-supplies', label: '🐕 Pet Supplies' },
    { value: 'over-the-counter', label: '💊 Over-the-Counter Medicine' },
    { value: 'first-aid', label: '🩹 First Aid' },
    { value: 'vitamins-supplements', label: '💊 Vitamins & Supplements' },
    { value: 'sunscreen-insect', label: '☀️ Sunscreen & Insect Repellent' },
    { value: 'phone-accessories', label: '📱 Phone Accessories' },
    { value: 'magazines-books', label: '📚 Magazines & Books' },
    { value: 'gift-cards', label: '🎁 Gift Cards' },
  ],
  GROCERY: [
    { value: 'produce', label: '🥬 Fresh Produce' },
    { value: 'meat', label: '🥩 Meat & Poultry' },
    { value: 'seafood', label: '🐟 Seafood' },
    { value: 'dairy', label: '🥛 Dairy & Eggs' },
    { value: 'bakery', label: '🍞 Bakery' },
    { value: 'canned-goods', label: '🥫 Canned Goods' },
    { value: 'dry-goods', label: '📦 Dry Goods' },
    { value: 'frozen-foods', label: '🧊 Frozen Foods' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'snacks', label: '🍿 Snacks' },
    { value: 'household', label: '🏠 Household' },
    { value: 'personal-care', label: '🧴 Personal Care' },
    { value: 'fresh-vegetables', label: '🥦 Fresh Vegetables' },
    { value: 'fresh-fruits', label: '🍎 Fresh Fruits' },
    { value: 'herbs-spices', label: '🌿 Herbs & Spices' },
    { value: 'organic-produce', label: '🌱 Organic Produce' },
    { value: 'exotic-fruits', label: '🥭 Exotic Fruits' },
    { value: 'berries', label: '🫐 Berries' },
    { value: 'citrus', label: '🍊 Citrus Fruits' },
    { value: 'tropical-fruits', label: '🍍 Tropical Fruits' },
    { value: 'leafy-greens', label: '🥬 Leafy Greens' },
    { value: 'root-vegetables', label: '🥕 Root Vegetables' },
    { value: 'cruciferous', label: '🥦 Cruciferous Vegetables' },
    { value: 'nightshade', label: '🍅 Nightshade Vegetables' },
    { value: 'allium', label: '🧅 Allium Vegetables' },
    { value: 'squash-gourds', label: '🎃 Squash & Gourds' },
    { value: 'beef', label: '🥩 Beef' },
    { value: 'poultry', label: '🍗 Poultry' },
    { value: 'pork', label: '🥓 Pork' },
    { value: 'lamb', label: '🐑 Lamb' },
    { value: 'veal', label: '🐄 Veal' },
    { value: 'deli-meat', label: '🥓 Deli Meat' },
    { value: 'ground-meat', label: '🍔 Ground Meat' },
    { value: 'sausages', label: '🌭 Sausages' },
    { value: 'bacon-cured', label: '🥓 Bacon & Cured Meats' },
    { value: 'fresh-fish', label: '🐟 Fresh Fish' },
    { value: 'shellfish', label: '🦐 Shellfish' },
    { value: 'frozen-seafood', label: '🧊 Frozen Seafood' },
    { value: 'smoked-cured', label: '🍖 Smoked & Cured Seafood' },
    { value: 'milk-cream', label: '🥛 Milk & Cream' },
    { value: 'cheese', label: '🧀 Cheese' },
    { value: 'yogurt', label: '🥛 Yogurt' },
    { value: 'butter-margarine', label: '🧈 Butter & Margarine' },
    { value: 'eggs', label: '🥚 Eggs' },
    { value: 'sour-cream', label: '🥛 Sour Cream & Cream Cheese' },
    { value: 'fresh-bread', label: '🍞 Fresh Bread' },
    { value: 'rolls-buns', label: '🥖 Rolls & Buns' },
    { value: 'pastries', label: '🥐 Pastries' },
    { value: 'tortillas-flatbread', label: '🫓 Tortillas & Flatbread' },
    { value: 'bagels', label: '🥯 Bagels' },
    { value: 'english-muffins', label: '🍞 English Muffins' },
    { value: 'canned-vegetables', label: '🥫 Canned Vegetables' },
    { value: 'canned-fruits', label: '🥫 Canned Fruits' },
    { value: 'canned-soup', label: '🥫 Canned Soup' },
    { value: 'canned-meat-fish', label: '🥫 Canned Meat & Fish' },
    { value: 'canned-beans', label: '🥫 Canned Beans' },
    { value: 'canned-tomatoes', label: '🥫 Canned Tomatoes' },
    { value: 'pasta-rice', label: '🍝 Pasta & Rice' },
    { value: 'grains-cereal', label: '🌾 Grains & Cereal' },
    { value: 'flour-baking', label: '🌾 Flour & Baking' },
    { value: 'beans-legumes', label: '🫘 Beans & Legumes' },
    { value: 'nuts-seeds-dry', label: '🥜 Nuts & Seeds' },
    { value: 'dried-fruit', label: '🍇 Dried Fruit' },
    { value: 'spices-seasonings', label: '🌶️ Spices & Seasonings' },
    { value: 'oils-vinegars', label: '🫒 Oils & Vinegars' },
    { value: 'sauces-condiments', label: '🍯 Sauces & Condiments' },
    { value: 'frozen-vegetables', label: '🧊 Frozen Vegetables' },
    { value: 'frozen-fruits', label: '🧊 Frozen Fruits' },
    { value: 'frozen-meals', label: '🍽️ Frozen Meals' },
    { value: 'frozen-desserts', label: '🍦 Frozen Desserts' },
    { value: 'frozen-bread', label: '🧊 Frozen Bread' },
    { value: 'coffee', label: '☕ Coffee' },
    { value: 'tea', label: '🍵 Tea' },
    { value: 'juice', label: '🧃 Juice' },
    { value: 'soda-carbonated', label: '🥤 Soda & Carbonated' },
    { value: 'water', label: '💧 Water' },
    { value: 'sports-drinks', label: '⚡ Sports Drinks' },
    { value: 'energy-drinks', label: '⚡ Energy Drinks' },
    { value: 'chips-pretzels', label: '🥨 Chips & Pretzels' },
    { value: 'crackers', label: '🍪 Crackers' },
    { value: 'popcorn', label: '🍿 Popcorn' },
    { value: 'granola-bars', label: '🍫 Granola & Bars' },
    { value: 'fruit-snacks', label: '🍎 Fruit Snacks' },
    { value: 'cleaning-products', label: '🧹 Cleaning Products' },
    { value: 'paper-towels', label: '🧻 Paper Towels' },
    { value: 'trash-bags', label: '🗑️ Trash Bags' },
    { value: 'dish-soap', label: '🧴 Dish Soap' },
    { value: 'laundry-detergent', label: '🧺 Laundry Detergent' },
    { value: 'soap-body-wash', label: '🧼 Soap & Body Wash' },
    { value: 'shampoo-conditioner', label: '🧴 Shampoo & Conditioner' },
    { value: 'toothpaste', label: '🦷 Toothpaste' },
    { value: 'deodorant', label: '🦹 Deodorant' },
    { value: 'skincare', label: '🧴 Skincare' },
    { value: 'hair-care', label: '💇 Hair Care' },
    { value: 'oral-care', label: '🦷 Oral Care' },
  ],
  HOME_KITCHEN: [
    { value: 'prepared-meals', label: '🍱 Prepared Meals' },
    { value: 'entrees', label: '🍽️ Entrees' },
    { value: 'sides', label: '🍟 Sides' },
    { value: 'desserts', label: '🍰 Desserts' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'specials', label: '⭐ Daily Specials' },
  ],
  BAKERY: [
    { value: 'bread', label: '🍞 Bread' },
    { value: 'pastries', label: '🥐 Pastries' },
    { value: 'cakes', label: '🎂 Cakes' },
    { value: 'cookies', label: '🍪 Cookies' },
    { value: 'pies', label: '🥧 Pies' },
    { value: 'desserts', label: '🍰 Desserts' },
    { value: 'beverages', label: '☕ Coffee & Tea' },
    { value: 'sandwiches', label: '🥪 Sandwiches' },
    { value: 'specials', label: '⭐ Special Orders' },
    { value: 'artisan-bread', label: '🥖 Artisan Bread' },
    { value: 'sourdough', label: '🍞 Sourdough' },
    { value: 'whole-grain', label: '🌾 Whole Grain' },
    { value: 'gluten-free-bread', label: '🌾 Gluten-Free Bread' },
    { value: 'ciabatta', label: '🥖 Ciabatta' },
    { value: 'focaccia', label: '🫓 Focaccia' },
    { value: 'baguette', label: '🥖 Baguette' },
    { value: 'rye-bread', label: '🍞 Rye Bread' },
    { value: 'pumpernickel', label: '🍞 Pumpernickel' },
    { value: 'multigrain', label: '🌾 Multigrain' },
    { value: 'brioche', label: '🥐 Brioche' },
    { value: 'challah', label: '🥖 Challah' },
    { value: 'french-bread', label: '🥖 French Bread' },
    { value: 'italian-bread', label: '🍞 Italian Bread' },
    { value: 'croissants', label: '🥐 Croissants' },
    { value: 'danish-pastries', label: '🥐 Danish Pastries' },
    { value: 'eclairs', label: '🥐 Éclairs' },
    { value: 'profiteroles', label: '🥐 Profiteroles' },
    { value: 'tarts', label: '🥧 Tarts' },
    { value: 'quiche', label: '🥧 Quiche' },
    { value: 'puff-pastry', label: '🥐 Puff Pastry' },
    { value: 'phyllo-pastry', label: '🥐 Phyllo Pastry' },
    { value: 'baklava', label: '🥐 Baklava' },
    { value: 'strudel', label: '🥐 Strudel' },
    { value: 'birthday-cakes', label: '🎂 Birthday Cakes' },
    { value: 'wedding-cakes', label: '👰 Wedding Cakes' },
    { value: 'cheesecake', label: '🍰 Cheesecake' },
    { value: 'chocolate-cake', label: '🍫 Chocolate Cake' },
    { value: 'vanilla-cake', label: '🍦 Vanilla Cake' },
    { value: 'fruit-cake', label: '🍎 Fruit Cake' },
    { value: 'carrot-cake', label: '🥕 Carrot Cake' },
    { value: 'red-velvet', label: '🍰 Red Velvet' },
    { value: 'angel-food', label: '👼 Angel Food' },
    { value: 'devil-food', label: '😈 Devil Food' },
    { value: 'pound-cake', label: '🍰 Pound Cake' },
    { value: 'sponge-cake', label: '🍰 Sponge Cake' },
    { value: 'genoise', label: '🍰 Genoise' },
    { value: 'chocolate-chip', label: '🍪 Chocolate Chip' },
    { value: 'oatmeal-raisin', label: '🍪 Oatmeal Raisin' },
    { value: 'peanut-butter', label: '🥜 Peanut Butter' },
    { value: 'sugar-cookies', label: '🍪 Sugar Cookies' },
    { value: 'shortbread', label: '🍪 Shortbread' },
    { value: 'gingersnaps', label: '🍪 Gingersnaps' },
    { value: 'macarons', label: '🍪 Macarons' },
    { value: 'biscotti', label: '🍪 Biscotti' },
    { value: 'fortune-cookies', label: '🥠 Fortune Cookies' },
    { value: 'butter-cookies', label: '🍪 Butter Cookies' },
    { value: 'lemon-cookies', label: '🍋 Lemon Cookies' },
    { value: 'apple-pie', label: '🍎 Apple Pie' },
    { value: 'pumpkin-pie', label: '🎃 Pumpkin Pie' },
    { value: 'cherry-pie', label: '🍒 Cherry Pie' },
    { value: 'pecan-pie', label: '🥜 Pecan Pie' },
    { value: 'blueberry-pie', label: '🫐 Blueberry Pie' },
    { value: 'lemon-meringue', label: '🍋 Lemon Meringue' },
    { value: 'key-lime-pie', label: '🍋 Key Lime Pie' },
    { value: 'chocolate-pie', label: '🍫 Chocolate Pie' },
    { value: 'coconut-cream', label: '🥥 Coconut Cream' },
    { value: 'banana-cream', label: '🍌 Banana Cream' },
    { value: 'custard-pies', label: '🍮 Custard Pies' },
    { value: 'mousse', label: '🍮 Mousse' },
    { value: 'pudding', label: '🍮 Pudding' },
    { value: 'flan', label: '🍮 Flan' },
    { value: 'creme-brulee', label: '🍮 Crème Brûlée' },
    { value: 'panna-cotta', label: '🍮 Panna Cotta' },
    { value: 'tiramisu', label: '🍰 Tiramisu' },
    { value: 'gelato', label: '🍨 Gelato' },
    { value: 'sorbet', label: '🍨 Sorbet' },
    { value: 'espresso', label: '☕ Espresso' },
    { value: 'cappuccino', label: '☕ Cappuccino' },
    { value: 'latte', label: '☕ Latte' },
    { value: 'americano', label: '☕ Americano' },
    { value: 'macchiato', label: '☕ Macchiato' },
    { value: 'specialty-coffee', label: '☕ Specialty Coffee' },
    { value: 'iced-coffee', label: '🧊 Iced Coffee' },
    { value: 'hot-tea', label: '🍵 Hot Tea' },
    { value: 'iced-tea', label: '🧊 Iced Tea' },
    { value: 'herbal-tea', label: '🌿 Herbal Tea' },
    { value: 'chai', label: '🍵 Chai' },
    { value: 'club-sandwich', label: '🥪 Club Sandwich' },
    { value: 'blt', label: '🥪 BLT' },
    { value: 'turkey-club', label: '🥪 Turkey Club' },
    { value: 'veg-sandwich', label: '🥪 Veg Sandwich' },
    { value: 'panini', label: '🥪 Panini' },
    { value: 'custom-cakes', label: '🎂 Custom Cakes' },
    { value: 'seasonal-specials', label: '🍂 Seasonal Specials' },
    { value: 'holiday-items', label: '🎄 Holiday Items' },
    { value: 'gluten-free-items', label: '🌾 Gluten-Free Items' },
    { value: 'vegan-items', label: '🌱 Vegan Items' },
  ],
  RETAIL: [
    { value: 'electronics', label: '📱 Electronics' },
    { value: 'clothing', label: '👕 Clothing' },
    { value: 'home-goods', label: '🏠 Home Goods' },
    { value: 'toys', label: '🧸 Toys & Games' },
    { value: 'books', label: '📚 Books' },
    { value: 'sports', label: '⚽ Sports & Outdoors' },
    { value: 'beauty', label: '💄 Beauty & Personal Care' },
    { value: 'automotive', label: '🚗 Automotive' },
    { value: 'seasonal', label: '🎄 Seasonal Items' },
  ],
  OTHER: [
    { value: 'miscellaneous', label: '📦 Miscellaneous' },
    { value: 'services', label: '🔧 Services' },
    { value: 'custom', label: '🎨 Custom Items' },
    { value: 'specials', label: '⭐ Special Items' },
  ],
}

// Legacy categories for backward compatibility
export const CATEGORIES = [
  { value: 'appetizers', label: '🥗 Appetizers' },
  { value: 'entrees', label: '🍽️ Entrees' },
  { value: 'sandwiches', label: '🥪 Sandwiches' },
  { value: 'salads', label: '🥗 Salads' },
  { value: 'soups', label: '🍲 Soups' },
  { value: 'sides', label: '🍟 Sides' },
  { value: 'desserts', label: '🍰 Desserts' },
  { value: 'beverages', label: '🥤 Beverages' },
  { value: 'breakfast', label: '🍳 Breakfast' },
  { value: 'specials', label: '⭐ Specials' },
]

// ============================================
// Item Type Options
// ============================================

export const ITEM_TYPES: Record<string, {value: string, label: string}[]> = {
  ...RESTAURANT_ITEM_TYPES,
  entrees: [
    { value: 'entree', label: '🍽️ Main Entree' },
    { value: 'bundle', label: '📦 Entree Combo' },
    { value: 'beef-entree', label: '🥩 Beef Entree' },
    { value: 'chicken-entree', label: '🍗 Chicken Entree' },
    { value: 'pork-entree', label: '🥓 Pork Entree' },
    { value: 'seafood-entree', label: '🐟 Seafood Entree' },
    { value: 'vegetarian-entree', label: '🥬 Vegetarian Entree' },
    { value: 'vegan-entree', label: '🌱 Vegan Entree' },
    { value: 'lamb-entree', label: '🐑 Lamb Entree' },
    { value: 'duck-entree', label: '🦆 Duck Entree' },
    { value: 'turkey-entree', label: '🦃 Turkey Entree' },
    { value: 'game-entree', label: '🦌 Game Meat Entree' },
    { value: 'pasta-entree', label: '🍝 Pasta Entree' },
    { value: 'rice-entree', label: '🍚 Rice Entree' },
    { value: 'stir-fry-entree', label: '🥢 Stir Fry Entree' },
    { value: 'curry-entree', label: '🍛 Curry Entree' },
    { value: 'roasted-entree', label: '🔥 Roasted Entree' },
    { value: 'grilled-entree', label: '🔥 Grilled Entree' },
    { value: 'pan-seared-entree', label: '🍳 Pan Seared Entree' },
    { value: 'braised-entree', label: '🍲 Braised Entree' },
    { value: 'steamed-entree', label: '💨 Steamed Entree' },
    { value: 'fried-entree', label: '🍟 Fried Entree' },
    { value: 'gluten-free-entree', label: '🌾 Gluten-Free Entree' },
    { value: 'dairy-free-entree', label: '🥛 Dairy-Free Entree' },
    { value: 'light-entree', label: '🥗 Light Entree' },
    { value: 'hearty-entree', label: '🍲 Hearty Entree' },
  ],
  sandwiches: [
    { value: 'sandwich', label: '🥪 Sandwich' },
    { value: 'entree', label: '🍽️ Sandwich Entree' },
    { value: 'bundle', label: '📦 Sandwich Combo' },
    { value: 'cold-sandwich', label: '🥪 Cold Sandwich' },
    { value: 'hot-sandwich', label: '🔥 Hot Sandwich' },
    { value: 'grilled-sandwich', label: '🔥 Grilled Sandwich' },
    { value: 'pressed-sandwich', label: '🍞 Pressed Sandwich' },
    { value: 'wrap-sandwich', label: '🌯 Wrap' },
    { value: 'toasted-sandwich', label: '🍞 Toasted Sandwich' },
    { value: 'open-faced', label: '🍞 Open-Faced' },
    { value: 'club-sandwich', label: '🥪 Club Sandwich' },
    { value: 'submarine', label: '🥖 Submarine' },
    { value: 'panini-sandwich', label: '🔥 Panini' },
    { value: 'baguette-sandwich', label: '🥖 Baguette' },
    { value: 'ciabatta-sandwich', label: '🥖 Ciabatta' },
    { value: 'sourdough-sandwich', label: '🍞 Sourdough' },
    { value: 'rye-sandwich', label: '🍞 Rye' },
    { value: 'whole-wheat', label: '🌾 Whole Wheat' },
    { value: 'gluten-free-sandwich', label: '🌾 Gluten-Free' },
    { value: 'veggie-sandwich', label: '🥬 Veggie Sandwich' },
    { value: 'vegan-sandwich', label: '🌱 Vegan Sandwich' },
    { value: 'chicken-sandwich', label: '🍗 Chicken Sandwich' },
    { value: 'beef-sandwich', label: '🥩 Beef Sandwich' },
    { value: 'seafood-sandwich', label: '🐟 Seafood Sandwich' },
    { value: 'breakfast-sandwich', label: '🍳 Breakfast Sandwich' },
  ],
  salads: [
    { value: 'salad', label: '🥗 Salad' },
    { value: 'side', label: '🍟 Side Salad' },
    { value: 'entree', label: '🍽️ Salad Entree' },
    { value: 'green-salad', label: '🥬 Green Salad' },
    { value: 'pasta-salad', label: '🍝 Pasta Salad' },
    { value: 'potato-salad', label: '🥔 Potato Salad' },
    { value: 'fruit-salad', label: '🍎 Fruit Salad' },
    { value: 'grain-salad', label: '🌾 Grain Salad' },
    { value: 'caesar-salad', label: '🥬 Caesar Salad' },
    { value: 'greek-salad', label: '🫒 Greek Salad' },
    { value: 'cobb-salad', label: '🥗 Cobb Salad' },
    { value: 'chef-salad', label: '👨‍🍳 Chef Salad' },
    { value: 'taco-salad', label: '🌮 Taco Salad' },
    { value: 'chicken-salad', label: '🍗 Chicken Salad' },
    { value: 'tuna-salad', label: '🐟 Tuna Salad' },
    { value: 'egg-salad', label: '🥚 Egg Salad' },
    { value: 'waldorf-salad', label: '🍎 Waldorf Salad' },
    { value: 'tabbouleh', label: '🌿 Tabbouleh' },
    { value: 'quinoa-salad', label: '🌾 Quinoa Salad' },
    { value: 'lentil-salad', label: '🫘 Lentil Salad' },
    { value: 'beet-salad', label: '🍑 Beet Salad' },
    { value: 'caprese-salad', label: '🍅 Caprese Salad' },
    { value: 'asian-salad', label: '🥢 Asian Salad' },
    { value: 'mediterranean-salad', label: '🫒 Mediterranean Salad' },
    { value: 'vegan-salad', label: '🌱 Vegan Salad' },
    { value: 'protein-salad', label: '💪 Protein Salad' },
  ],
  soups: [
    { value: 'soup', label: '🍲 Soup' },
    { value: 'side', label: '🍟 Soup Side' },
    { value: 'entree', label: '🍽️ Soup Entree' },
    { value: 'broth-soup', label: '🍲 Broth Soup' },
    { value: 'cream-soup', label: '🥛 Cream Soup' },
    { value: 'chunky-soup', label: '🥄 Chunky Soup' },
    { value: 'pureed-soup', label: '🥄 Pureed Soup' },
    { value: 'vegetable-soup', label: '🥬 Vegetable Soup' },
    { value: 'chicken-soup', label: '🍗 Chicken Soup' },
    { value: 'beef-soup', label: '🥩 Beef Soup' },
    { value: 'seafood-soup', label: '🐟 Seafood Soup' },
    { value: 'tomato-soup', label: '🍅 Tomato Soup' },
    { value: 'potato-soup', label: '🥔 Potato Soup' },
    { value: 'onion-soup', label: '🧅 Onion Soup' },
    { value: 'mushroom-soup', label: '🍄 Mushroom Soup' },
    { value: 'clam-chowder', label: '🦪 Clam Chowder' },
    { value: 'bisque', label: '🦞 Bisque' },
    { value: 'gazpacho', label: '🥒 Gazpacho' },
    { value: 'minestrone', label: '🥕 Minestrone' },
    { value: 'lentil-soup', label: '🫘 Lentil Soup' },
    { value: 'split-pea', label: '🟢 Split Pea Soup' },
    { value: 'chili', label: '🌶️ Chili' },
    { value: 'stew', label: '🍛 Stew' },
    { value: 'curry-soup', label: '🍛 Curry Soup' },
    { value: 'noodle-soup', label: '🍜 Noodle Soup' },
    { value: 'wonton-soup', label: '🥟 Wonton Soup' },
  ],
  sides: [
    { value: 'side', label: '🍟 Side Dish' },
    { value: 'appetizer', label: '🥗 Side Appetizer' },
    { value: 'vegetable-side', label: '🥬 Vegetable Side' },
    { value: 'starch-side', label: '🍟 Starch Side' },
    { value: 'salad-side', label: '🥗 Salad Side' },
    { value: 'bread-side', label: '🍞 Bread Side' },
    { value: 'potato-side', label: '🥔 Potato Side' },
    { value: 'rice-side', label: '🍚 Rice Side' },
    { value: 'pasta-side', label: '🍝 Pasta Side' },
    { value: 'grilled-vegetables', label: '🔥 Grilled Vegetables' },
    { value: 'steamed-vegetables', label: '💨 Steamed Vegetables' },
    { value: 'roasted-vegetables', label: '🔥 Roasted Vegetables' },
    { value: 'sauteed-vegetables', label: '🍳 Sautéed Vegetables' },
    { value: 'fried-side', label: '🍟 Fried Side' },
    { value: 'mashed-potatoes', label: '🥔 Mashed Potatoes' },
    { value: 'french-fries', label: '🍟 French Fries' },
    { value: 'sweet-potatoes', label: '🍠 Sweet Potatoes' },
    { value: 'corn-side', label: '🌽 Corn Side' },
    { value: 'beans-side', label: '🫘 Beans Side' },
    { value: 'coleslaw', label: '🥗 Coleslaw' },
    { value: 'mac-cheese', label: '🧀 Mac & Cheese' },
    { value: 'stuffing', label: '🍞 Stuffing' },
    { value: 'gravy', label: '🍲 Gravy' },
    { value: 'garlic-bread', label: '🧄 Garlic Bread' },
    { value: 'breadsticks', label: '🥖 Breadsticks' },
  ],
  desserts: [
    { value: 'dessert', label: '🍰 Dessert' },
    { value: 'bundle', label: '📦 Dessert Combo' },
    { value: 'cake-dessert', label: '🎂 Cake' },
    { value: 'pie-dessert', label: '🥧 Pie' },
    { value: 'ice-cream-dessert', label: '🍦 Ice Cream' },
    { value: 'pastry-dessert', label: '🥐 Pastry' },
    { value: 'fruit-dessert', label: '🍎 Fruit Dessert' },
    { value: 'chocolate-dessert', label: '🍫 Chocolate Dessert' },
    { value: 'cheesecake-dessert', label: '🍰 Cheesecake' },
    { value: 'mousse-dessert', label: '🍮 Mousse' },
    { value: 'pudding-dessert', label: '🍮 Pudding' },
    { value: 'tart-dessert', label: '🥧 Tart' },
    { value: 'souffle', label: '🍮 Soufflé' },
    { value: 'creme-brulee', label: '🍮 Crème Brûlée' },
    { value: 'panna-cotta', label: '🍮 Panna Cotta' },
    { value: 'tiramisu', label: '🍰 Tiramisu' },
    { value: 'gelato', label: '🍨 Gelato' },
    { value: 'sorbet', label: '🍨 Sorbet' },
    { value: 'frozen-yogurt', label: '🍦 Frozen Yogurt' },
    { value: 'cookie-dessert', label: '🍪 Cookie' },
    { value: 'brownie', label: '🍫 Brownie' },
    { value: 'blondie', label: '🍪 Blondie' },
    { value: 'fruit-crisp', label: '🍎 Fruit Crisp' },
    { value: 'cobbler', label: '🍑 Cobbler' },
    { value: 'trifle', label: '🍮 Trifle' },
    { value: 'parfait', label: '🥤 Parfait' },
    { value: 'vegan-dessert', label: '🌱 Vegan Dessert' },
    { value: 'gluten-free-dessert', label: '🌾 Gluten-Free Dessert' },
  ],
  beverages: [
    { value: 'drink', label: '🥤 Beverage' },
    { value: 'side', label: '🍟 Drink Side' },
    { value: 'soft-drink-bev', label: '🥤 Soft Drink' },
    { value: 'juice-bev', label: '🧃 Juice' },
    { value: 'coffee-bev', label: '☕ Coffee' },
    { value: 'tea-bev', label: '🍵 Tea' },
    { value: 'smoothie-bev', label: '🥤 Smoothie' },
    { value: 'water-bev', label: '💧 Water' },
    { value: 'sports-drink', label: '⚡ Sports Drink' },
    { value: 'energy-drink', label: '⚡ Energy Drink' },
    { value: 'lemonade', label: '🍋 Lemonade' },
    { value: 'iced-tea', label: '🧊 Iced Tea' },
    { value: 'hot-chocolate', label: '🍫 Hot Chocolate' },
    { value: 'milk-bev', label: '🥛 Milk' },
    { value: 'milkshake', label: '🥤 Milkshake' },
    { value: 'float', label: '🥤 Float' },
    { value: 'fresh-juice', label: '🍊 Fresh Juice' },
    { value: 'vegetable-juice', label: '🥬 Vegetable Juice' },
    { value: 'protein-shake', label: '💪 Protein Shake' },
    { value: 'kombucha', label: '🧃 Kombucha' },
    { value: 'coconut-water', label: '🥥 Coconut Water' },
    { value: 'sparkling-water', label: '💧 Sparkling Water' },
    { value: 'infused-water', label: '🍋 Infused Water' },
    { value: 'herbal-tea', label: '🌿 Herbal Tea' },
    { value: 'chai', label: '🍵 Chai' },
    { value: 'latte', label: '☕ Latte' },
    { value: 'cappuccino', label: '☕ Cappuccino' },
    { value: 'espresso', label: '☕ Espresso' },
  ],
  breakfast: [
    { value: 'breakfast', label: '🍳 Breakfast' },
    { value: 'entree', label: '🍽️ Breakfast Entree' },
    { value: 'bundle', label: '📦 Breakfast Combo' },
    { value: 'eggs-breakfast', label: '🥚 Eggs' },
    { value: 'pancakes-breakfast', label: '🥞 Pancakes' },
    { value: 'waffles-breakfast', label: '🧇 Waffles' },
    { value: 'cereal-breakfast', label: '🥣 Cereal' },
    { value: 'oatmeal-breakfast', label: '🥄 Oatmeal' },
    { value: 'french-toast', label: '🍞 French Toast' },
    { value: 'breakfast-sandwich', label: '🥪 Breakfast Sandwich' },
    { value: 'breakfast-burrito', label: '🌯 Breakfast Burrito' },
    { value: 'breakfast-taco', label: '🌮 Breakfast Taco' },
    { value: 'omelette', label: '🍳 Omelette' },
    { value: 'frittata', label: '🍳 Frittata' },
    { value: 'quiche', label: '🥧 Quiche' },
    { value: 'breakfast-bowl', label: '🥣 Breakfast Bowl' },
    { value: 'yogurt-parfait', label: '🥤 Yogurt Parfait' },
    { value: 'smoothie-bowl', label: '🥤 Smoothie Bowl' },
    { value: 'breakfast-meats', label: '🥓 Breakfast Meats' },
    { value: 'bacon-breakfast', label: '🥓 Bacon' },
    { value: 'sausage-breakfast', label: '🌭 Sausage' },
    { value: 'ham-breakfast', label: '🍖 Ham' },
    { value: 'hash-browns', label: '🥔 Hash Browns' },
    { value: 'home-fries', label: '🍟 Home Fries' },
    { value: 'breakfast-potatoes', label: '🥔 Breakfast Potatoes' },
    { value: 'toast-breakfast', label: '🍞 Toast' },
    { value: 'bagel-breakfast', label: '🥯 Bagel' },
    { value: 'muffin-breakfast', label: '🧁 Muffin' },
    { value: 'pastry-breakfast', label: '🥐 Pastry' },
    { value: 'crepe', label: '🥞 Crepe' },
    { value: 'breakfast-casserole', label: '🍲 Breakfast Casserole' },
  ],
  specials: [
    { value: 'entree', label: '🍽️ Special Entree' },
    { value: 'bundle', label: '📦 Special Combo' },
    { value: 'appetizer', label: '🥗 Special Appetizer' },
    { value: 'dessert', label: '🍰 Special Dessert' },
    { value: 'chef-special', label: '👨‍🍳 Chef Special' },
    { value: 'daily-special', label: '📅 Daily Special' },
    { value: 'seasonal-special', label: '🍂 Seasonal Special' },
    { value: 'weekly-special', label: '📆 Weekly Special' },
    { value: 'limited-time', label: '⏰ Limited Time' },
    { value: 'signature-dish', label: '✍️ Signature Dish' },
    { value: 'house-special', label: '🏠 House Special' },
    { value: 'regional-special', label: '🗺️ Regional Special' },
    { value: 'holiday-special', label: '🎄 Holiday Special' },
    { value: 'festival-special', label: '🎉 Festival Special' },
    { value: 'event-special', label: '🎪 Event Special' },
    { value: 'celebration-special', label: '🎊 Celebration Special' },
    { value: 'anniversary-special', label: '🎂 Anniversary Special' },
    { value: 'birthday-special', label: '🎂 Birthday Special' },
    { value: 'valentine-special', label: '💝 Valentine Special' },
    { value: 'mother-day-special', label: '🌸 Mother\'s Day Special' },
    { value: 'father-day-special', label: '👨 Father\'s Day Special' },
    { value: 'new-year-special', label: '🎊 New Year Special' },
    { value: 'summer-special', label: '☀️ Summer Special' },
    { value: 'winter-special', label: '❄️ Winter Special' },
    { value: 'spring-special', label: '🌸 Spring Special' },
    { value: 'fall-special', label: '🍂 Fall Special' },
    { value: 'weekend-special', label: '🎉 Weekend Special' },
    { value: 'late-night-special', label: '🌙 Late Night Special' },
    { value: 'early-bird-special', label: '🐦 Early Bird Special' },
    { value: 'happy-hour-special', label: '🍻 Happy Hour Special' },
    { value: 'brunch-special', label: '🥞 Brunch Special' },
  ],
  // New restaurant categories
  pasta: [
    { value: 'pasta', label: '🍝 Pasta Dish' },
    { value: 'entree', label: '🍽️ Pasta Entree' },
    { value: 'bundle', label: '📦 Pasta Combo' },
    { value: 'side', label: '🍟 Pasta Side' },
    { value: 'spaghetti-pasta', label: '🍝 Spaghetti' },
    { value: 'penne-pasta', label: '🍝 Penne' },
    { value: 'fettuccine-pasta', label: '🍝 Fettuccine' },
    { value: 'linguine-pasta', label: '🍝 Linguine' },
    { value: 'ravioli-pasta', label: '🥟 Ravioli' },
    { value: 'tortellini-pasta', label: '🥟 Tortellini' },
    { value: 'lasagna-pasta', label: '🍝 Lasagna' },
    { value: 'gnocchi-pasta', label: '🥔 Gnocchi' },
    { value: 'macaroni-pasta', label: '🍝 Macaroni' },
    { value: 'farfalle-pasta', label: '🦋 Farfalle' },
    { value: 'rotini-pasta', label: '🌀 Rotini' },
    { value: 'cavatappi-pasta', label: '🍝 Cavatappi' },
    { value: 'bucatini-pasta', label: '🍝 Bucatini' },
    { value: 'pappardelle-pasta', label: '🍝 Pappardelle' },
    { value: 'orecchiette-pasta', label: '👂 Orecchiette' },
    { value: 'angel-hair-pasta', label: '😇 Angel Hair' },
    { value: 'capellini-pasta', label: '🍝 Capellini' },
    { value: 'vermicelli-pasta', label: '🍝 Vermicelli' },
    { value: 'fusilli-pasta', label: '🌀 Fusilli' },
    { value: 'rigatoni-pasta', label: '🍝 Rigatoni' },
    { value: 'creamy-pasta', label: '🥛 Creamy Pasta' },
    { value: 'tomato-pasta', label: '🍅 Tomato-Based Pasta' },
    { value: 'pesto-pasta', label: '🌿 Pesto Pasta' },
    { value: 'alfredo-pasta', label: '🧈 Alfredo Pasta' },
    { value: 'carbonara-pasta', label: '🥓 Carbonara' },
    { value: 'bolognese-pasta', label: '🍝 Bolognese' },
    { value: 'marinara-pasta', label: '🍅 Marinara' },
    { value: 'arrabbiata-pasta', label: '🌶️ Arrabbiata' },
    { value: 'puttanesca-pasta', label: '🍝 Puttanesca' },
    { value: 'aglio-olio-pasta', label: '🧄 Aglio e Olio' },
    { value: 'vongole-pasta', label: '🦪 Vongole' },
    { value: 'frutti-mare-pasta', label: '🦐 Frutti di Mare' },
  ],
  pizza: [
    { value: 'pizza', label: '🍕 Pizza' },
    { value: 'entree', label: '🍽️ Pizza Entree' },
    { value: 'bundle', label: '📦 Pizza Combo' },
    { value: 'slice', label: '🍕 Pizza Slice' },
    { value: 'margherita-pizza', label: '🍕 Margherita' },
    { value: 'pepperoni-pizza', label: '🍕 Pepperoni' },
    { value: 'hawaiian-pizza', label: '🍕 Hawaiian' },
    { value: 'meat-lovers-pizza', label: '🍕 Meat Lovers' },
    { value: 'veggie-pizza', label: '🥬 Veggie Pizza' },
    { value: 'supreme-pizza', label: '🍕 Supreme' },
    { value: 'bbq-chicken-pizza', label: '🍕 BBQ Chicken' },
    { value: 'buffalo-chicken-pizza', label: '🍕 Buffalo Chicken' },
    { value: 'four-cheese-pizza', label: '🧀 Four Cheese' },
    { value: 'white-pizza', label: '🍕 White Pizza' },
    { value: 'mediterranean-pizza', label: '🫒 Mediterranean' },
    { value: 'pesto-chicken-pizza', label: '🌿 Pesto Chicken' },
    { value: 'truffle-pizza', label: '🍄 Truffle Pizza' },
    { value: 'seafood-pizza', label: '🦐 Seafood Pizza' },
    { value: 'prosciutto-pizza', label: '🥓 Prosciutto' },
    { value: 'mushroom-pizza', label: '🍄 Mushroom Pizza' },
    { value: 'spinach-pizza', label: '🥬 Spinach Pizza' },
    { value: 'artichoke-pizza', label: '🫒 Artichoke Pizza' },
    { value: 'anchovy-pizza', label: '🐟 Anchovy Pizza' },
    { value: 'personal-pizza', label: '🍕 Personal Pizza' },
    { value: 'medium-pizza', label: '🍕 Medium Pizza' },
    { value: 'large-pizza', label: '🍕 Large Pizza' },
    { value: 'extra-large-pizza', label: '🍕 Extra Large' },
    { value: 'family-size-pizza', label: '👨‍👩‍👧‍👦 Family Size' },
    { value: 'party-size-pizza', label: '🎉 Party Size' },
    { value: 'cheese-slice', label: '🧀 Cheese Slice' },
    { value: 'pepperoni-slice', label: '🍕 Pepperoni Slice' },
    { value: 'veggie-slice', label: '🥬 Veggie Slice' },
    { value: 'specialty-slice', label: '⭐ Specialty Slice' },
    { value: 'pizza-combo', label: '📦 Pizza Combo' },
    { value: 'pizza-party', label: '🎉 Pizza Party' },
    { value: 'pizza-feast', label: '🍽️ Pizza Feast' },
  ],
  burgers: [
    { value: 'burger', label: '🍔 Burger' },
    { value: 'entree', label: '🍽️ Burger Entree' },
    { value: 'bundle', label: '📦 Burger Combo' },
    { value: 'slider', label: '🍔 Slider' },
    { value: 'classic-beef-burger', label: '🍔 Classic Beef' },
    { value: 'cheeseburger', label: '🧀 Cheeseburger' },
    { value: 'bacon-burger', label: '🥓 Bacon Burger' },
    { value: 'mushroom-swiss-burger', label: '🍄 Mushroom Swiss' },
    { value: 'bbq-burger', label: '🍕 BBQ Burger' },
    { value: 'blue-cheese-burger', label: '🧀 Blue Cheese Burger' },
    { value: 'jalapeno-burger', label: '🌶️ Jalapeno Burger' },
    { value: 'onion-ring-burger', label: '🧅 Onion Ring Burger' },
    { value: 'guacamole-burger', label: '🥑 Guacamole Burger' },
    { value: 'teriyaki-burger', label: '🥢 Teriyaki Burger' },
    { value: 'buffalo-burger', label: '🍗 Buffalo Burger' },
    { value: 'veggie-burger', label: '🥬 Veggie Burger' },
    { value: 'black-bean-burger', label: '⚫ Black Bean Burger' },
    { value: 'impossible-burger', label: '🌱 Impossible Burger' },
    { value: 'beyond-meat-burger', label: '🌿 Beyond Meat Burger' },
    { value: 'turkey-burger', label: '🦃 Turkey Burger' },
    { value: 'chicken-burger', label: '🍗 Chicken Burger' },
    { value: 'salmon-burger', label: '🐟 Salmon Burger' },
    { value: 'lamb-burger', label: '🐑 Lamb Burger' },
    { value: 'portobello-burger', label: '🍄 Portobello Burger' },
    { value: 'single-burger', label: '🍔 Single Burger' },
    { value: 'double-burger', label: '🍔 Double Burger' },
    { value: 'triple-burger', label: '🍔 Triple Burger' },
    { value: 'quarter-pound-burger', label: '🍔 Quarter Pound' },
    { value: 'half-pound-burger', label: '🍔 Half Pound' },
    { value: 'full-pound-burger', label: '🍔 Full Pound' },
    { value: 'cheese-slider', label: '🧀 Cheese Slider' },
    { value: 'bbq-slider', label: '🍕 BBQ Slider' },
    { value: 'chicken-slider', label: '🍗 Chicken Slider' },
    { value: 'veggie-slider', label: '🥬 Veggie Slider' },
    { value: 'burger-combo', label: '📦 Burger Combo' },
    { value: 'burger-meal', label: '🍽️ Burger Meal' },
    { value: 'slider-pack', label: '📦 Slider Pack' },
  ],
  'seafood-restaurant': [
    { value: 'seafood', label: '🦐 Seafood Dish' },
    { value: 'entree', label: '🍽️ Seafood Entree' },
    { value: 'bundle', label: '📦 Seafood Combo' },
    { value: 'appetizer', label: '🥗 Seafood Appetizer' },
    { value: 'fish-seafood', label: '🐟 Fish Dish' },
    { value: 'shrimp-seafood', label: '🦐 Shrimp Dish' },
    { value: 'lobster-seafood', label: '🦞 Lobster Dish' },
    { value: 'crab-seafood', label: '🦀 Crab Dish' },
    { value: 'scallops-seafood', label: '🦪 Scallops Dish' },
    { value: 'mussels-seafood', label: '🦪 Mussels Dish' },
    { value: 'clams-seafood', label: '🦪 Clams Dish' },
    { value: 'oysters-seafood', label: '🦪 Oysters Dish' },
    { value: 'calamari-seafood', label: '🦑 Calamari Dish' },
    { value: 'salmon-seafood', label: '🐟 Salmon Dish' },
    { value: 'tuna-seafood', label: '🐟 Tuna Dish' },
    { value: 'cod-seafood', label: '🐟 Cod Dish' },
    { value: 'halibut-seafood', label: '🐟 Halibut Dish' },
    { value: 'tilapia-seafood', label: '🐟 Tilapia Dish' },
    { value: 'sea-bass-seafood', label: '🐟 Sea Bass Dish' },
    { value: 'swordfish-seafood', label: '🐟 Swordfish Dish' },
    { value: 'mahi-seafood', label: '🐟 Mahi Mahi Dish' },
    { value: 'grilled-seafood', label: '🔥 Grilled Seafood' },
    { value: 'fried-seafood', label: '🍟 Fried Seafood' },
    { value: 'steamed-seafood', label: '💨 Steamed Seafood' },
    { value: 'raw-seafood', label: '🥗 Raw Seafood' },
    { value: 'ceviche-seafood', label: '🍋 Ceviche' },
    { value: 'seafood-platter', label: '🍽️ Seafood Platter' },
    { value: 'seafood-boil', label: '🍲 Seafood Boil' },
    { value: 'fish-tacos', label: '🌮 Fish Tacos' },
    { value: 'shrimp-cocktail', label: '🦐 Shrimp Cocktail' },
    { value: 'crab-cakes', label: '🦀 Crab Cakes' },
  ],
  'steak-house': [
    { value: 'steak', label: '🥩 Steak' },
    { value: 'entree', label: '🍽️ Steak Entree' },
    { value: 'bundle', label: '📦 Steak Combo' },
    { value: 'premium', label: '💎 Premium Cut' },
    { value: 'ribeye-steak', label: '🥩 Ribeye' },
    { value: 'sirloin-steak', label: '🥩 Sirloin' },
    { value: 'filet-steak', label: '🥩 Filet Mignon' },
    { value: 't-bone-steak', label: '🥩 T-Bone' },
    { value: 'porterhouse-steak', label: '🥩 Porterhouse' },
    { value: 'new-york-steak', label: '🥩 New York Strip' },
    { value: 'flat-iron-steak', label: '🥩 Flat Iron' },
    { value: 'skirt-steak', label: '🥩 Skirt Steak' },
    { value: 'flank-steak', label: '🥩 Flank Steak' },
    { value: 'prime-rib-steak', label: '🥩 Prime Rib' },
    { value: 'brisket-steak', label: '🥩 Brisket' },
    { value: 'tri-tip-steak', label: '🥩 Tri-Tip' },
    { value: 'wagyu-steak', label: '🥩 Wagyu' },
    { value: 'kobe-steak', label: '🥩 Kobe' },
    { value: 'aged-steak', label: '🥩 Aged Steak' },
    { value: 'grilled-steak', label: '🔥 Grilled Steak' },
    { value: 'pan-seared-steak', label: '🍳 Pan Seared Steak' },
    { value: 'broiled-steak', label: '🔥 Broiled Steak' },
    { value: 'well-done-steak', label: '🔥 Well Done' },
    { value: 'medium-steak', label: '🍽️ Medium' },
    { value: 'rare-steak', label: '🔴 Rare' },
    { value: 'steak-dinner', label: '🍽️ Steak Dinner' },
    { value: 'steak-combo', label: '📦 Steak Combo' },
    { value: 'steak-feast', label: '🍽️ Steak Feast' },
    { value: 'surf-turf', label: '🦞 Surf & Turf' },
    { value: 'steak-sandwich', label: '🥪 Steak Sandwich' },
    { value: 'steak-salad', label: '🥗 Steak Salad' },
  ],
  'bbq-grill': [
    { value: 'bbq', label: '🔥 BBQ Dish' },
    { value: 'entree', label: '🍽️ BBQ Entree' },
    { value: 'bundle', label: '📦 BBQ Combo' },
    { value: 'platter', label: '🍽️ BBQ Platter' },
    { value: 'ribs-bbq', label: '🍖 Ribs' },
    { value: 'brisket-bbq', label: '🥩 Brisket' },
    { value: 'pulled-pork', label: '🥖 Pulled Pork' },
    { value: 'pulled-chicken', label: '🍗 Pulled Chicken' },
    { value: 'bbq-chicken', label: '🍗 BBQ Chicken' },
    { value: 'bbq-beef', label: '🥩 BBQ Beef' },
    { value: 'smoked-turkey', label: '🦃 Smoked Turkey' },
    { value: 'smoked-salmon', label: '🐟 Smoked Salmon' },
    { value: 'burnt-ends', label: '🔥 Burnt Ends' },
    { value: 'bbq-sausage', label: '🌭 BBQ Sausage' },
    { value: 'bbq-mac', label: '🧀 BBQ Mac & Cheese' },
    { value: 'baked-beans', label: '🫘 Baked Beans' },
    { value: 'coleslaw-bbq', label: '🥗 Coleslaw' },
    { value: 'potato-salad', label: '🥔 Potato Salad' },
    { value: 'corn-bread', label: '🌽 Corn Bread' },
    { value: 'grilled-corn', label: '🌽 Grilled Corn' },
    { value: 'grilled-vegetables', label: '🥬 Grilled Vegetables' },
    { value: 'bbq-sandwich', label: '🥪 BBQ Sandwich' },
    { value: 'bbq-taco', label: '🌮 BBQ Taco' },
    { value: 'bbq-pizza', label: '🍕 BBQ Pizza' },
    { value: 'bbq-burger', label: '🍔 BBQ Burger' },
    { value: 'bbq-wings', label: '🍗 BBQ Wings' },
    { value: 'bbq-feast', label: '🍽️ BBQ Feast' },
    { value: 'family-platter', label: '👨‍👩‍👧‍👦 Family Platter' },
    { value: 'party-platter', label: '🎉 Party Platter' },
    { value: 'bbq-combo', label: '📦 BBQ Combo' },
  ],
  mexican: [
    { value: 'mexican', label: '🌮 Mexican Dish' },
    { value: 'entree', label: '🍽️ Mexican Entree' },
    { value: 'bundle', label: '📦 Mexican Combo' },
    { value: 'taco', label: '🌮 Taco' },
    { value: 'burrito', label: '🌯 Burrito' },
    { value: 'enchilada', label: '🌯 Enchilada' },
    { value: 'quesadilla', label: '🫓 Quesadilla' },
    { value: 'tamale', label: '🫔 Tamale' },
    { value: 'tostada', label: '🫔 Tostada' },
    { value: 'chile-relleno', label: '🌶️ Chile Relleno' },
    { value: 'fajitas', label: '🥘 Fajitas' },
    { value: 'nachos', label: '🫔 Nachos' },
    { value: 'carnitas', label: '🥖 Carnitas' },
    { value: 'al-pastor', label: '🥖 Al Pastor' },
    { value: 'barbacoa', label: '🥩 Barbacoa' },
    { value: 'carne-asada', label: '🥩 Carne Asada' },
    { value: 'pollo-asado', label: '🍗 Pollo Asado' },
    { value: 'fish-tacos', label: '🐟 Fish Tacos' },
    { value: 'shrimp-tacos', label: '🦐 Shrimp Tacos' },
    { value: 'veggie-tacos', label: '🥬 Veggie Tacos' },
    { value: 'breakfast-burrito', label: '🌯 Breakfast Burrito' },
    { value: 'wet-burrito', label: '🌯 Wet Burrito' },
    { value: 'bowl-burrito', label: '🥣 Burrito Bowl' },
    { value: 'taco-salad', label: '🥗 Taco Salad' },
    { value: 'mexican-rice', label: '🍚 Mexican Rice' },
    { value: 'refried-beans', label: '🫘 Refried Beans' },
    { value: 'guacamole', label: '🥑 Guacamole' },
    { value: 'salsa', label: '🍅 Salsa' },
    { value: 'queso', label: '🧀 Queso' },
    { value: 'chips-salsa', label: '🫔 Chips & Salsa' },
    { value: 'mexican-combo', label: '📦 Mexican Combo' },
    { value: 'family-platter', label: '👨‍👩‍👧‍👦 Family Platter' },
    { value: 'fiesta-platter', label: '🎉 Fiesta Platter' },
  ],
  italian: [
    { value: 'italian', label: '🍝 Italian Dish' },
    { value: 'entree', label: '🍽️ Italian Entree' },
    { value: 'bundle', label: '📦 Italian Combo' },
    { value: 'classic', label: '🍝 Italian Classic' },
    { value: 'lasagna-italian', label: '🍝 Lasagna' },
    { value: 'spaghetti-italian', label: '🍝 Spaghetti' },
    { value: 'carbonara-italian', label: '🥓 Carbonara' },
    { value: 'bolognese-italian', label: '🍝 Bolognese' },
    { value: 'alfredo-italian', label: '🧈 Alfredo' },
    { value: 'pesto-italian', label: '🌿 Pesto' },
    { value: 'marinara-italian', label: '🍅 Marinara' },
    { value: 'arrabbiata-italian', label: '🌶️ Arrabbiata' },
    { value: 'puttanesca-italian', label: '🍝 Puttanesca' },
    { value: 'vongole-italian', label: '🦪 Vongole' },
    { value: 'osso-buco', label: '🥩 Osso Buco' },
    { value: 'veal-italian', label: '🐄 Veal Dish' },
    { value: 'chicken-italian', label: '🍗 Chicken Italian' },
    { value: 'seafood-italian', label: '🦐 Seafood Italian' },
    { value: 'risotto-italian', label: '🍚 Risotto' },
    { value: 'gnocchi-italian', label: '🥔 Gnocchi' },
    { value: 'ravioli-italian', label: '🥟 Ravioli' },
    { value: 'tortellini-italian', label: '🥟 Tortellini' },
    { value: 'minestrone-italian', label: '🥕 Minestrone' },
    { value: 'bruschetta', label: '🍞 Bruschetta' },
    { value: 'caprese-italian', label: '🍅 Caprese' },
    { value: 'antipasto', label: '🥗 Antipasto' },
    { value: 'calzone', label: '🫔 Calzone' },
    { value: 'stromboli', label: '🫔 Stromboli' },
    { value: 'italian-combo', label: '📦 Italian Combo' },
    { value: 'family-feast', label: '👨‍👩‍👧‍👦 Family Feast' },
    { value: 'regional-specialty', label: '🗺️ Regional Specialty' },
  ],
  asian: [
    { value: 'asian', label: '🥢 Asian Dish' },
    { value: 'entree', label: '🍽️ Asian Entree' },
    { value: 'bundle', label: '📦 Asian Combo' },
    { value: 'stir-fry', label: '🥢 Stir Fry' },
    { value: 'chinese-asian', label: '🥡 Chinese Dish' },
    { value: 'japanese-asian', label: '🍱 Japanese Dish' },
    { value: 'thai-asian', label: '🍜 Thai Dish' },
    { value: 'vietnamese-asian', label: '🍲 Vietnamese Dish' },
    { value: 'korean-asian', label: '🥘 Korean Dish' },
    { value: 'indian-asian', label: '🍛 Indian Dish' },
    { value: 'sushi', label: '🍣 Sushi' },
    { value: 'sashimi', label: '🐟 Sashimi' },
    { value: 'ramen', label: '🍜 Ramen' },
    { value: 'udon', label: '🍜 Udon' },
    { value: 'soba', label: '🍜 Soba' },
    { value: 'pho', label: '🍲 Pho' },
    { value: 'bun-cha', label: '🥖 Bún Chả' },
    { value: 'pad-thai', label: '🍜 Pad Thai' },
    { value: 'curry-asian', label: '🍛 Curry' },
    { value: 'korma', label: '🍛 Korma' },
    { value: 'tikka', label: '🍗 Tikka' },
    { value: 'biryani', label: '🍚 Biryani' },
    { value: 'kimchi', label: '🥬 Kimchi' },
    { value: 'bibimbap', label: '🥘 Bibimbap' },
    { value: 'bulgogi', label: '🥩 Bulgogi' },
    { value: 'dim-sum', label: '🥟 Dim Sum' },
    { value: 'dumplings', label: '🥟 Dumplings' },
    { value: 'spring-rolls', label: '🥟 Spring Rolls' },
    { value: 'egg-rolls', label: '🥚 Egg Rolls' },
    { value: 'wontons', label: '🥟 Wontons' },
    { value: 'fried-rice', label: '🍚 Fried Rice' },
    { value: 'lo-mein', label: '🍜 Lo Mein' },
    { value: 'chow-mein', label: '🍜 Chow Mein' },
    { value: 'asian-combo', label: '📦 Asian Combo' },
    { value: 'family-platter', label: '👨‍👩‍👧‍👦 Family Platter' },
    { value: 'bento-box', label: '🍱 Bento Box' },
  ],
  mediterranean: [
    { value: 'mediterranean', label: '🫒 Mediterranean Dish' },
    { value: 'entree', label: '🍽️ Mediterranean Entree' },
    { value: 'bundle', label: '📦 Mediterranean Combo' },
    { value: 'meze', label: '🫒 Meze' },
    { value: 'greek-salad', label: '🫒 Greek Salad' },
    { value: 'hummus', label: '🫒 Hummus' },
    { value: 'falafel', label: '🫔 Falafel' },
    { value: 'gyro', label: '🥖 Gyro' },
    { value: 'souvlaki', label: '🥖 Souvlaki' },
    { value: 'dolmas', label: '🫔 Dolmas' },
    { value: 'tabbouleh', label: '🌿 Tabbouleh' },
    { value: 'baba-ghanoush', label: '🫒 Baba Ghanoush' },
    { value: 'tzatziki', label: '🥛 Tzatziki' },
    { value: 'pita', label: '🫓 Pita' },
    { value: 'feta-cheese', label: '🧀 Feta Cheese' },
    { value: 'olives', label: '🫒 Olives' },
    { value: 'grilled-fish', label: '🐟 Grilled Fish' },
    { value: 'lamb-mediterranean', label: '🐑 Lamb Dish' },
    { value: 'chicken-mediterranean', label: '🍗 Chicken Mediterranean' },
    { value: 'vegetable-platter', label: '🥬 Vegetable Platter' },
    { value: 'mediterranean-rice', label: '🍚 Mediterranean Rice' },
    { value: 'couscous', label: '🌾 Couscous' },
    { value: 'orzo-pasta', label: '🍝 Orzo' },
    { value: 'mediterranean-soup', label: '🍲 Mediterranean Soup' },
    { value: 'stuffed-vegetables', label: '🫔 Stuffed Vegetables' },
    { value: 'mediterranean-combo', label: '📦 Mediterranean Combo' },
    { value: 'family-platter', label: '👨‍👩‍👧‍👦 Family Platter' },
    { value: 'meze-platter', label: '🫒 Meze Platter' },
  ],
  vegetarian: [
    { value: 'vegetarian', label: '🌱 Vegetarian Dish' },
    { value: 'entree', label: '🍽️ Vegetarian Entree' },
    { value: 'bundle', label: '📦 Vegetarian Combo' },
    { value: 'plant-based', label: '🌿 Plant-Based' },
    { value: 'tofu-dish', label: '🧈 Tofu Dish' },
    { value: 'tempeh-dish', label: '🫒 Tempeh Dish' },
    { value: 'seitan-dish', label: '🥩 Seitan Dish' },
    { value: 'vegetarian-pasta', label: '🍝 Vegetarian Pasta' },
    { value: 'vegetarian-pizza', label: '🍕 Vegetarian Pizza' },
    { value: 'vegetarian-burger', label: '🍔 Veggie Burger' },
    { value: 'vegetarian-taco', label: '🌮 Veggie Taco' },
    { value: 'vegetarian-curry', label: '🍛 Veggie Curry' },
    { value: 'vegetarian-stir-fry', label: '🥢 Veggie Stir Fry' },
    { value: 'vegetarian-salad', label: '🥗 Veggie Salad' },
    { value: 'vegetarian-soup', label: '🍲 Veggie Soup' },
    { value: 'vegetarian-sandwich', label: '🥪 Veggie Sandwich' },
    { value: 'vegetarian-wrap', label: '🌯 Veggie Wrap' },
    { value: 'vegetarian-bowl', label: '🥣 Veggie Bowl' },
    { value: 'grilled-vegetables', label: '🔥 Grilled Vegetables' },
    { value: 'roasted-vegetables', label: '🔥 Roasted Vegetables' },
    { value: 'steamed-vegetables', label: '💨 Steamed Vegetables' },
    { value: 'stuffed-vegetables', label: '🫔 Stuffed Vegetables' },
    { value: 'vegetarian-lasagna', label: '🍝 Veggie Lasagna' },
    { value: 'vegetarian-chili', label: '🌶️ Veggie Chili' },
    { value: 'vegetarian-stew', label: '🍛 Veggie Stew' },
    { value: 'vegetarian-casserole', label: '🍲 Veggie Casserole' },
    { value: 'vegetarian-quiche', label: '🥧 Veggie Quiche' },
    { value: 'vegetarian-frittata', label: '🍳 Veggie Frittata' },
    { value: 'vegetarian-combo', label: '📦 Vegetarian Combo' },
    { value: 'garden-platter', label: '🌱 Garden Platter' },
    { value: 'harvest-bowl', label: '🍂 Harvest Bowl' },
  ],
  vegan: [
    { value: 'vegan', label: '🥬 Vegan Dish' },
    { value: 'entree', label: '🍽️ Vegan Entree' },
    { value: 'bundle', label: '📦 Vegan Combo' },
    { value: 'raw', label: '🥗 Raw Vegan' },
    { value: 'vegan-tofu', label: '🧈 Vegan Tofu' },
    { value: 'vegan-tempeh', label: '🫒 Vegan Tempeh' },
    { value: 'vegan-seitan', label: '🥩 Vegan Seitan' },
    { value: 'vegan-pasta', label: '🍝 Vegan Pasta' },
    { value: 'vegan-pizza', label: '🍕 Vegan Pizza' },
    { value: 'vegan-burger', label: '🍔 Vegan Burger' },
    { value: 'vegan-taco', label: '🌮 Vegan Taco' },
    { value: 'vegan-curry', label: '🍛 Vegan Curry' },
    { value: 'vegan-stir-fry', label: '🥢 Vegan Stir Fry' },
    { value: 'vegan-salad', label: '🥗 Vegan Salad' },
    { value: 'vegan-soup', label: '🍲 Vegan Soup' },
    { value: 'vegan-sandwich', label: '🥪 Vegan Sandwich' },
    { value: 'vegan-wrap', label: '🌯 Vegan Wrap' },
    { value: 'vegan-bowl', label: '🥣 Vegan Bowl' },
    { value: 'vegan-smoothie', label: '🥤 Vegan Smoothie' },
    { value: 'vegan-juice', label: '🧃 Vegan Juice' },
    { value: 'vegan-dessert', label: '🍰 Vegan Dessert' },
    { value: 'vegan-pastry', label: '🥐 Vegan Pastry' },
    { value: 'vegan-chocolate', label: '🍫 Vegan Chocolate' },
    { value: 'vegan-ice-cream', label: '🍦 Vegan Ice Cream' },
    { value: 'vegan-cheese', label: '🧀 Vegan Cheese' },
    { value: 'vegan-milk', label: '🥛 Vegan Milk' },
    { value: 'vegan-yogurt', label: '🥛 Vegan Yogurt' },
    { value: 'vegan-protein', label: '💪 Vegan Protein' },
    { value: 'vegan-energy', label: '⚡ Vegan Energy' },
    { value: 'vegan-combo', label: '📦 Vegan Combo' },
    { value: 'plant-based-feast', label: '🌱 Plant-Based Feast' },
    { value: 'vegan-platter', label: '🥗 Vegan Platter' },
  ],
  'gluten-free': [
    { value: 'gluten-free', label: '🌾 Gluten-Free Dish' },
    { value: 'entree', label: '🍽️ Gluten-Free Entree' },
    { value: 'bundle', label: '📦 Gluten-Free Combo' },
    { value: 'certified', label: '✅ Certified GF' },
    { value: 'gf-pasta', label: '🍝 GF Pasta' },
    { value: 'gf-pizza', label: '🍕 GF Pizza' },
    { value: 'gf-burger', label: '🍔 GF Burger' },
    { value: 'gf-sandwich', label: '🥪 GF Sandwich' },
    { value: 'gf-bread', label: '🍞 GF Bread' },
    { value: 'gf-tortillas', label: '🫓 GF Tortillas' },
    { value: 'gf-pancakes', label: '🥞 GF Pancakes' },
    { value: 'gf-waffles', label: '🧇 GF Waffles' },
    { value: 'gf-dessert', label: '🍰 GF Dessert' },
    { value: 'gf-cake', label: '🎂 GF Cake' },
    { value: 'gf-cookies', label: '🍪 GF Cookies' },
    { value: 'gf-pastry', label: '🥐 GF Pastry' },
    { value: 'gf-crust', label: '🫓 GF Crust' },
    { value: 'gf-breading', label: '🍟 GF Breading' },
    { value: 'gf-gravy', label: '🍲 GF Gravy' },
    { value: 'gf-sauce', label: '🍯 GF Sauce' },
    { value: 'gf-soup', label: '🍲 GF Soup' },
    { value: 'gf-salad', label: '🥗 GF Salad' },
    { value: 'gf-bowl', label: '🥣 GF Bowl' },
    { value: 'gf-wrap', label: '🌯 GF Wrap' },
    { value: 'gf-taco', label: '🌮 GF Taco' },
    { value: 'gf-combo', label: '📦 GF Combo' },
    { value: 'gf-platter', label: '🍽️ GF Platter' },
    { value: 'gf-family-meal', label: '👨‍👩‍👧‍👦 GF Family Meal' },
    { value: 'gf-kids-meal', label: '👶 GF Kids Meal' },
    { value: 'gf-breakfast', label: '🍳 GF Breakfast' },
    { value: 'gf-brunch', label: '🥞 GF Brunch' },
    { value: 'gf-lunch', label: '🍽️ GF Lunch' },
    { value: 'gf-dinner', label: '🍽️ GF Dinner' },
  ],
  'kids-menu': [
    { value: 'kids', label: '👶 Kids Meal' },
    { value: 'entree', label: '🍽️ Kids Entree' },
    { value: 'bundle', label: '📦 Kids Combo' },
    { value: 'side', label: '🍟 Kids Side' },
    { value: 'kids-pizza', label: '🍕 Kids Pizza' },
    { value: 'kids-burger', label: '🍔 Kids Burger' },
    { value: 'kids-chicken', label: '🍗 Kids Chicken' },
    { value: 'kids-pasta', label: '🍝 Kids Pasta' },
    { value: 'kids-mac-cheese', label: '🧀 Kids Mac & Cheese' },
    { value: 'kids-hot-dog', label: '🌭 Kids Hot Dog' },
    { value: 'kids-grilled-cheese', label: '🧀 Kids Grilled Cheese' },
    { value: 'kids-tacos', label: '🌮 Kids Tacos' },
    { value: 'kids-quesadilla', label: '🫓 Kids Quesadilla' },
    { value: 'kids-nuggets', label: '🍗 Kids Nuggets' },
    { value: 'kids-fingers', label: '🍗 Kids Fingers' },
    { value: 'kids-fries', label: '🍟 Kids Fries' },
    { value: 'kids-vegetables', label: '🥬 Kids Vegetables' },
    { value: 'kids-fruit', label: '🍎 Kids Fruit' },
    { value: 'kids-dessert', label: '🍰 Kids Dessert' },
    { value: 'kids-ice-cream', label: '🍦 Kids Ice Cream' },
    { value: 'kids-pudding', label: '🍮 Kids Pudding' },
    { value: 'kids-jello', label: '🍮 Kids Jello' },
    { value: 'kids-drink', label: '🥤 Kids Drink' },
    { value: 'kids-juice', label: '🧃 Kids Juice' },
    { value: 'kids-milk', label: '🥛 Kids Milk' },
    { value: 'kids-chocolate', label: '🍫 Kids Chocolate' },
    { value: 'kids-candy', label: '🍬 Kids Candy' },
    { value: 'kids-toy', label: '🧸 Kids Toy' },
    { value: 'kids-lunchable', label: '🥪 Kids Lunchable' },
    { value: 'kids-bento', label: '🍱 Kids Bento' },
    { value: 'kids-party', label: '🎉 Kids Party' },
    { value: 'kids-celebration', label: '🎊 Kids Celebration' },
    { value: 'kids-special', label: '⭐ Kids Special' },
    { value: 'kids-adventure', label: '🗺️ Kids Adventure' },
  ],
  'tapas-small-plates': [
    { value: 'tapas', label: '🍤 Tapas' },
    { value: 'small-plate', label: '🍤 Small Plate' },
    { value: 'bundle', label: '📦 Tapas Combo' },
    { value: 'shareable', label: '👥 Shareable' },
    { value: 'spanish-tapas', label: '🫒 Spanish Tapas' },
    { value: 'meze-tapas', label: '🫒 Meze Tapas' },
    { value: 'antipasto-tapas', label: '🥗 Antipasto Tapas' },
    { value: 'bruschetta-tapas', label: '🍞 Bruschetta Tapas' },
    { value: 'crostini-tapas', label: '🍞 Crostini Tapas' },
    { value: 'olives-tapas', label: '🫒 Olives Tapas' },
    { value: 'cheese-tapas', label: '🧀 Cheese Tapas' },
    { value: 'cured-meats', label: '🥖 Cured Meats' },
    { value: 'marinated-vegetables', label: '🫒 Marinated Vegetables' },
    { value: 'stuffed-mushrooms', label: '🍄 Stuffed Mushrooms' },
    { value: 'stuffed-peppers', label: '🌶️ Stuffed Peppers' },
    { value: 'shrimp-cocktail', label: '🦐 Shrimp Cocktail' },
    { value: 'crab-cakes-tapas', label: '🦀 Crab Cakes' },
    { value: 'tuna-tartare', label: '🐟 Tuna Tartare' },
    { value: 'beef-carpaccio', label: '🥩 Beef Carpaccio' },
    { value: 'prosciutto-tapas', label: '🥓 Prosciutto' },
    { value: 'salami-tapas', label: '🥖 Salami' },
    { value: 'chorizo-tapas', label: '🌭 Chorizo' },
    { value: 'patatas-bravas', label: '🥔 Patatas Bravas' },
    { value: 'gambas-al-ajillo', label: '🦐 Gambas al Ajillo' },
    { value: 'pulpo-a-la-gallega', label: '🐙 Pulpo a la Gallega' },
    { value: 'tortilla-espanola', label: '🫔 Tortilla Española' },
    { value: 'pimientos-de-padron', label: '🌶️ Pimientos de Padron' },
    { value: 'boquerones', label: '🐟 Boquerones' },
    { value: 'aceitunas', label: '🫒 Aceitunas' },
    { value: 'tapas-platter', label: '🍽️ Tapas Platter' },
    { value: 'tapas-flight', label: '🍤 Tapas Flight' },
    { value: 'tapas-combo', label: '📦 Tapas Combo' },
    { value: 'tapas-party', label: '🎉 Tapas Party' },
    { value: 'tapas-sharing', label: '👥 Tapas Sharing' },
  ],
  'raw-bar': [
    { value: 'raw', label: '🦪 Raw Item' },
    { value: 'appetizer', label: '🥗 Raw Appetizer' },
    { value: 'bundle', label: '📦 Raw Combo' },
    { value: 'oyster', label: '🦪 Oyster' },
    { value: 'clams-raw', label: '🦪 Clams' },
    { value: 'mussels-raw', label: '🦪 Mussels' },
    { value: 'scallops-raw', label: '🦪 Scallops' },
    { value: 'shrimp-cocktail', label: '🦐 Shrimp Cocktail' },
    { value: 'tuna-tartare', label: '🐟 Tuna Tartare' },
    { value: 'salmon-tartare', label: '🐟 Salmon Tartare' },
    { value: 'beef-carpaccio', label: '🥩 Beef Carpaccio' },
    { value: 'tuna-carpaccio', label: '🐟 Tuna Carpaccio' },
    { value: 'salmon-carpaccio', label: '🐟 Salmon Carpaccio' },
    { value: 'seafood-crudo', label: '🦐 Seafood Crudo' },
    { value: 'ceviche-raw', label: '🍋 Ceviche' },
    { value: 'tiradito', label: '🐟 Tiradito' },
    { value: 'poke-bowl', label: '🥣 Poke Bowl' },
    { value: 'tuna-poke', label: '🐟 Tuna Poke' },
    { value: 'salmon-poke', label: '🐟 Salmon Poke' },
    { value: 'octopus-raw', label: '🐙 Octopus' },
    { value: 'squid-raw', label: '🦑 Squid' },
    { value: 'uni', label: '🦪 Uni' },
    { value: 'ikura', label: '🦪 Ikura' },
    { value: 'masago', label: '🦪 Masago' },
    { value: 'raw-platter', label: '🦪 Raw Platter' },
    { value: 'oyster-shooter', label: '🦪 Oyster Shooter' },
    { value: 'raw-bar-combo', label: '📦 Raw Bar Combo' },
    { value: 'seafood-tower', label: '🦪 Seafood Tower' },
    { value: 'raw-bar-flight', label: '🦪 Raw Bar Flight' },
    { value: 'raw-bar-special', label: '⭐ Raw Bar Special' },
    { value: 'daily-catch', label: '🐟 Daily Catch' },
  ],
  'comfort-food': [
    { value: 'comfort', label: '🍲 Comfort Food' },
    { value: 'entree', label: '🍽️ Comfort Entree' },
    { value: 'bundle', label: '📦 Comfort Combo' },
    { value: 'homestyle', label: '🏠 Homestyle' },
    { value: 'mac-cheese', label: '🧀 Mac & Cheese' },
    { value: 'meatloaf', label: '🥩 Meatloaf' },
    { value: 'fried-chicken', label: '🍗 Fried Chicken' },
    { value: 'chicken-noodle', label: '🍜 Chicken Noodle Soup' },
    { value: 'beef-stew', label: '🍲 Beef Stew' },
    { value: 'pot-roast', label: '🥩 Pot Roast' },
    { value: 'roast-chicken', label: '� Roast Chicken' },
    { value: 'shepherd-pie', label: '🥧 Shepherd Pie' },
    { value: 'cottage-pie', label: '�🏠 Cottage Pie' },
    { value: 'mashed-potatoes', label: '🥔 Mashed Potatoes' },
    { value: 'gravy', label: '🍲 Gravy' },
    { value: 'stuffing', label: '🍞 Stuffing' },
    { value: 'biscuits-gravy', label: '🍞 Biscuits & Gravy' },
    { value: 'chicken-dumplings', label: '🍗 Chicken & Dumplings' },
    { value: 'beef-noodles', label: '🥩 Beef & Noodles' },
    { value: 'pork-chops', label: '🥖 Pork Chops' },
    { value: 'lamb-shank', label: '🐑 Lamb Shank' },
    { value: 'pot-pie', label: '🥧 Pot Pie' },
    { value: 'casserole', label: '🍲 Casserole' },
    { value: 'hot-dish', label: '🍲 Hot Dish' },
    { value: 'tuna-casserole', label: '🐟 Tuna Casserole' },
    { value: 'green-bean-casserole', label: '🥬 Green Bean Casserole' },
    { value: 'sweet-potato-casserole', label: '🍠 Sweet Potato Casserole' },
    { value: 'comfort-combo', label: '📦 Comfort Combo' },
    { value: 'family-dinner', label: '👨‍👩‍👧‍👦 Family Dinner' },
    { value: 'sunday-dinner', label: '🍽️ Sunday Dinner' },
    { value: 'grandma-special', label: '👵 Grandma Special' },
    { value: 'hearty-meal', label: '🍲 Hearty Meal' },
    { value: 'cozy-meal', label: '🏠 Cozy Meal' },
    { value: 'warm-meal', label: '🔥 Warm Meal' },
    { value: 'nostalgic-meal', label: '🕰 Nostalgic Meal' },
    { value: 'childhood-favorite', label: '👶 Childhood Favorite' },
    { value: 'comfort-platter', label: '🍽️ Comfort Platter' },
    { value: 'comfort-feast', label: '🍲 Comfort Feast' },
  ],
  'healthy-light': [
    { value: 'healthy', label: '🥗 Healthy Dish' },
    { value: 'entree', label: '🍽️ Healthy Entree' },
    { value: 'bundle', label: '📦 Healthy Combo' },
    { value: 'light', label: '🥗 Light Option' },
    { value: 'salad-healthy', label: '🥗 Healthy Salad' },
    { value: 'wrap-healthy', label: '🌯 Healthy Wrap' },
    { value: 'bowl-healthy', label: '🥣 Healthy Bowl' },
    { value: 'grilled-healthy', label: '🔥 Grilled Healthy' },
    { value: 'steamed-healthy', label: '💨 Steamed Healthy' },
    { value: 'raw-healthy', label: '🥗 Raw Healthy' },
    { value: 'vegan-healthy', label: '🌱 Vegan Healthy' },
    { value: 'vegetarian-healthy', label: '🥬 Vegetarian Healthy' },
    { value: 'pescatarian', label: '🐟 Pescatarian' },
    { value: 'keto-friendly', label: '🥑 Keto Friendly' },
    { value: 'paleo-friendly', label: '🥩 Paleo Friendly' },
    { value: 'low-carb', label: '🥬 Low Carb' },
    { value: 'low-fat', label: '🥛 Low Fat' },
    { value: 'low-calorie', label: '🔢 Low Calorie' },
    { value: 'high-protein', label: '💪 High Protein' },
    { value: 'superfood', label: '🌿 Superfood' },
    { value: 'organic-healthy', label: '🌱 Organic Healthy' },
    { value: 'fresh-healthy', label: '🍎 Fresh Healthy' },
    { value: 'seasonal-healthy', label: '🍂 Seasonal Healthy' },
    { value: 'detox', label: '🍋 Detox' },
    { value: 'cleanse', label: '💧 Cleanse' },
    { value: 'juice-cleanse', label: '🧃 Juice Cleanse' },
    { value: 'smoothie-healthy', label: '🥤 Healthy Smoothie' },
    { value: 'protein-bowl', label: '💪 Protein Bowl' },
    { value: 'grain-bowl', label: '🌾 Grain Bowl' },
    { value: 'power-bowl', label: '⚡ Power Bowl' },
    { value: 'energy-bowl', label: '⚡ Energy Bowl' },
    { value: 'zen-bowl', label: '🧘 Zen Bowl' },
    { value: 'healthy-combo', label: '📦 Healthy Combo' },
    { value: 'fit-feast', label: '💪 Fit Feast' },
    { value: 'wellness-plate', label: '🌿 Wellness Plate' },
    { value: 'vitality-meal', label: '💚 Vitality Meal' },
    { value: 'nourish-bowl', label: '🥣 Nourish Bowl' },
    { value: 'renew-plate', label: '🔄 Renew Plate' },
  ],
  'late-night': [
    { value: 'late-night', label: '🌙 Late Night Dish' },
    { value: 'entree', label: '🍽️ Late Night Entree' },
    { value: 'bundle', label: '📦 Late Night Combo' },
    { value: 'snack', label: '🍿 Late Night Snack' },
    { value: 'pizza-late', label: '🍕 Late Night Pizza' },
    { value: 'burger-late', label: '🍔 Late Night Burger' },
    { value: 'tacos-late', label: '🌮 Late Night Tacos' },
    { value: 'wings-late', label: '🍗 Late Night Wings' },
    { value: 'nachos-late', label: '🫔 Late Night Nachos' },
    { value: 'fries-late', label: '🍟 Late Night Fries' },
    { value: 'mozzarella-sticks', label: '🧀 Mozzarella Sticks' },
    { value: 'onion-rings', label: '🧅 Onion Rings' },
    { value: 'jalapeno-poppers', label: '🌶️ Jalapeno Poppers' },
    { value: 'loaded-fries', label: '🍟 Loaded Fries' },
    { value: 'poutine', label: '🍟 Poutine' },
    { value: 'chili-cheese-fries', label: '🌶️ Chili Cheese Fries' },
    { value: 'garlic-bread-late', label: '🧄 Garlic Bread' },
    { value: 'breadsticks-late', label: '🥖 Breadsticks' },
    { value: 'calzone-late', label: '🫔 Calzone' },
    { value: 'stromboli-late', label: '🫔 Stromboli' },
    { value: 'sandwich-late', label: '🥪 Late Night Sandwich' },
    { value: 'sub-late', label: '🥖 Late Night Sub' },
    { value: 'wrap-late', label: '🌯 Late Night Wrap' },
    { value: 'hot-dog-late', label: '🌭 Late Night Hot Dog' },
    { value: 'corn-dog-late', label: '🌽 Late Night Corn Dog' },
    { value: 'pretzel-late', label: '🥨 Late Night Pretzel' },
    { value: 'soft-pretzel', label: '🥨 Soft Pretzel' },
    { value: 'cinnamon-rolls', label: '🍞 Cinnamon Rolls' },
    { value: 'dessert-late', label: '🍰 Late Night Dessert' },
    { value: 'milkshake-late', label: '🥤 Late Night Milkshake' },
    { value: 'float-late', label: '🥤 Late Night Float' },
    { value: 'sundae-late', label: '🍦 Late Night Sundae' },
    { value: 'late-night-combo', label: '📦 Late Night Combo' },
    { value: 'midnight-feast', label: '🌙 Midnight Feast' },
    { value: 'after-hours', label: '🕐 After Hours' },
    { value: 'munchies', label: '🍿 Munchies' },
    { value: 'cravings', label: '🍔 Cravings' },
    { value: 'late-night-platter', label: '🍽️ Late Night Platter' },
    { value: 'party-plate', label: '🎉 Party Plate' },
    { value: 'social-plate', label: '👥 Social Plate' },
  ],
  brunch: [
    { value: 'brunch', label: '🥞 Brunch Dish' },
    { value: 'entree', label: '🍽️ Brunch Entree' },
    { value: 'bundle', label: '📦 Brunch Combo' },
    { value: 'bottomless', label: '🥞 Bottomless Brunch' },
    { value: 'eggs-benedict', label: '🥚 Eggs Benedict' },
    { value: 'eggs-florentine', label: '🥚 Eggs Florentine' },
    { value: 'eggs-royale', label: '👑 Eggs Royale' },
    { value: 'shakshuka', label: '🍅 Shakshuka' },
    { value: 'huevos-rancheros', label: '🌮 Huevos Rancheros' },
    { value: 'migas', label: '🥚 Migas' },
    { value: 'breakfast-burrito', label: '🌯 Breakfast Burrito' },
    { value: 'breakfast-tacos', label: '🌮 Breakfast Tacos' },
    { value: 'breakfast-quesadilla', label: '🫓 Breakfast Quesadilla' },
    { value: 'french-toast-brunch', label: '🍞 French Toast' },
    { value: 'stuffed-french-toast', label: '🍞 Stuffed French Toast' },
    { value: 'pancakes-brunch', label: '🥞 Pancakes' },
    { value: 'waffles-brunch', label: '🧇 Waffles' },
    { value: 'crepes-brunch', label: '🥞 Crepes' },
    { value: 'brunch-salad', label: '🥗 Brunch Salad' },
    { value: 'brunch-bowl', label: '🥣 Brunch Bowl' },
    { value: 'brunch-platter', label: '🍽️ Brunch Platter' },
    { value: 'brunch-sandwich', label: '🥪 Brunch Sandwich' },
    { value: 'brunch-burger', label: '🍔 Brunch Burger' },
    { value: 'brunch-pizza', label: '🍕 Brunch Pizza' },
    { value: 'brunch-pasta', label: '🍝 Brunch Pasta' },
    { value: 'brunch-steak', label: '🥩 Brunch Steak' },
    { value: 'brunch-seafood', label: '🦐 Brunch Seafood' },
    { value: 'brunch-chicken', label: '🍗 Brunch Chicken' },
    { value: 'brunch-vegetarian', label: '🥬 Brunch Vegetarian' },
    { value: 'brunch-vegan', label: '🌱 Brunch Vegan' },
    { value: 'brunch-combo', label: '📦 Brunch Combo' },
    { value: 'brunch-feast', label: '🍽️ Brunch Feast' },
    { value: 'weekend-brunch', label: '🎉 Weekend Brunch' },
    { value: 'family-brunch', label: '👨‍👩‍👧‍👦 Family Brunch' },
    { value: 'bottomless-mimosas', label: '🥤 Bottomless Mimosas' },
    { value: 'bottomless-sangria', label: '🍷 Bottomless Sangria' },
    { value: 'brunch-cocktails', label: '🍸 Brunch Cocktails' },
    { value: 'brunch-special', label: '⭐ Brunch Special' },
    { value: 'brunch-celebration', label: '🎊 Brunch Celebration' },
  ],
  'happy-hour': [
    { value: 'happy-hour', label: '🍻 Happy Hour Item' },
    { value: 'special', label: '⭐ Happy Hour Special' },
    { value: 'bundle', label: '📦 Happy Hour Combo' },
    { value: 'drink', label: '🍻 Happy Hour Drink' },
    { value: 'appetizer-special', label: '🥗 Appetizer Special' },
    { value: 'cocktail-special', label: '🍸 Cocktail Special' },
    { value: 'beer-special', label: '🍺 Beer Special' },
    { value: 'wine-special', label: '🍷 Wine Special' },
    { value: 'shot-special', label: '🥃 Shot Special' },
    { value: 'drink-combo', label: '🥤 Drink Combo' },
    { value: 'beer-flight', label: '🍺 Beer Flight' },
    { value: 'wine-flight', label: '🍷 Wine Flight' },
    { value: 'cocktail-flight', label: '🍸 Cocktail Flight' },
    { value: 'tasting-menu', label: '🍽️ Tasting Menu' },
    { value: 'small-plates', label: '🍤 Small Plates' },
    { value: 'shareable-plates', label: '👥 Shareable Plates' },
    { value: 'bar-snacks', label: '🍿 Bar Snacks' },
    { value: 'happy-hour-wings', label: '🍗 Happy Hour Wings' },
    { value: 'happy-hour-nachos', label: '🫔 Happy Hour Nachos' },
    { value: 'happy-hour-fries', label: '🍟 Happy Hour Fries' },
    { value: 'happy-hour-sliders', label: '🍔 Happy Hour Sliders' },
    { value: 'happy-hour-tacos', label: '🌮 Happy Hour Tacos' },
    { value: 'happy-hour-pizza', label: '🍕 Happy Hour Pizza' },
    { value: 'happy-hour-burger', label: '🍔 Happy Hour Burger' },
    { value: 'happy-hour-sandwich', label: '🥪 Happy Hour Sandwich' },
    { value: 'happy-hour-wrap', label: '🌯 Happy Hour Wrap' },
    { value: 'happy-hour-salad', label: '🥗 Happy Hour Salad' },
    { value: 'happy-hour-soup', label: '🍲 Happy Hour Soup' },
    { value: 'happy-hour-seafood', label: '🦐 Happy Hour Seafood' },
    { value: 'happy-hour-dessert', label: '🍰 Happy Hour Dessert' },
    { value: 'happy-hour-combo', label: '📦 Happy Hour Combo' },
    { value: 'happy-hour-platter', label: '🍽️ Happy Hour Platter' },
    { value: 'happy-hour-feast', label: '🍻 Happy Hour Feast' },
    { value: 'after-work', label: '🏢 After Work Special' },
    { value: 'wind-down', label: '🌅 Wind Down' },
    { value: 'social-hour', label: '👥 Social Hour' },
    { value: 'networking-hour', label: '🤝 Networking Hour' },
    { value: 'team-happy-hour', label: '👥 Team Happy Hour' },
    { value: 'celebration-drinks', label: '🎊 Celebration Drinks' },
    { value: 'seasonal-cocktails', label: '🍂 Seasonal Cocktails' },
    { value: 'signature-drinks', label: '✍️ Signature Drinks' },
    { value: 'craft-cocktails', label: '🍸 Craft Cocktails' },
    { value: 'local-brews', label: '🍺 Local Brews' },
    { value: 'imported-beers', label: '🌍 Imported Beers' },
    { value: 'happy-hour-specialty', label: '⭐ Happy Hour Specialty' },
    { value: 'late-happy-hour', label: '🌙 Late Happy Hour' },
    { value: 'extended-happy-hour', label: '⏰ Extended Happy Hour' },
    { value: 'reverse-happy-hour', label: '🔄 Reverse Happy Hour' },
    { value: 'happy-hour-deal', label: '💰 Happy Hour Deal' },
    { value: 'happy-hour-bargain', label: '💸 Happy Hour Bargain' },
    { value: 'happy-hour-value', label: '💎 Happy Hour Value' },
    { value: 'happy-hour-premium', label: '👑 Happy Hour Premium' },
    { value: 'happy-hour-exclusive', label: '🔒 Happy Hour Exclusive' },
    { value: 'happy-hour-limited', label: '⏰ Happy Hour Limited' },
    { value: 'happy-hour-favorite', label: '⭐ Happy Hour Favorite' },
    { value: 'happy-hour-classic', label: '🍻 Happy Hour Classic' },
    { value: 'happy-hour-trending', label: '📈 Happy Hour Trending' },
    { value: 'happy-hour-new', label: '🆕 Happy Hour New' },
    { value: 'happy-hour-featured', label: '🌟 Happy Hour Featured' },
  ],
  // Convenience store categories
  snacks: [
    { value: 'snack', label: '🍿 Snack' },
    { value: 'bundle', label: '📦 Snack Pack' },
    { value: 'single', label: '🍿 Single Serve' },
    { value: 'family', label: '👨‍👩‍👧‍👦 Family Size' },
  ],
  'candy-chocolate': [
    { value: 'candy', label: '🍫 Candy' },
    { value: 'chocolate', label: '🍫 Chocolate' },
    { value: 'bundle', label: '📦 Candy Pack' },
    { value: 'premium', label: '💎 Premium Chocolate' },
  ],
  'chips-crackers': [
    { value: 'chips', label: '🥨 Chips' },
    { value: 'crackers', label: '🍪 Crackers' },
    { value: 'bundle', label: '📦 Variety Pack' },
    { value: 'single', label: '🥨 Single Bag' },
  ],
  'nuts-seeds': [
    { value: 'nuts', label: '🥜 Nuts' },
    { value: 'seeds', label: '🌰 Seeds' },
    { value: 'bundle', label: '📦 Nut Mix' },
    { value: 'trail-mix', label: '🥾 Trail Mix' },
  ],
  'jerky-meat-snacks': [
    { value: 'jerky', label: '🥓 Jerky' },
    { value: 'meat-stick', label: '🥓 Meat Stick' },
    { value: 'bundle', label: '📦 Jerky Pack' },
    { value: 'single', label: '🥓 Single Serve' },
  ],
  'energy-bars': [
    { value: 'energy-bar', label: '🍫 Energy Bar' },
    { value: 'protein-bar', label: '💪 Protein Bar' },
    { value: 'bundle', label: '📦 Bar Box' },
    { value: 'meal-replacement', label: '🍽️ Meal Replacement' },
  ],
  'dairy-snacks': [
    { value: 'dairy', label: '🧀 Dairy Snack' },
    { value: 'cheese', label: '🧀 Cheese' },
    { value: 'bundle', label: '📦 Cheese Pack' },
    { value: 'single', label: '🧀 Single Serve' },
  ],
  'fruit-snacks': [
    { value: 'fruit', label: '🍎 Fruit Snack' },
    { value: 'dried', label: '🍇 Dried Fruit' },
    { value: 'bundle', label: '📦 Fruit Pack' },
    { value: 'organic', label: '🌱 Organic Fruit' },
  ],
  'desserts-bakery': [
    { value: 'dessert', label: '🍰 Dessert' },
    { value: 'single', label: '🍰 Single Dessert' },
    { value: 'platter', label: '🍽️ Dessert Platter' },
    { value: 'specialty', label: '⭐ Specialty Dessert' },
  ],
  'sandwiches-bakery': [
    { value: 'sandwich', label: '🥪 Sandwich' },
    { value: 'fresh', label: '🥪 Fresh Sandwich' },
    { value: 'grilled', label: '🔥 Grilled Sandwich' },
    { value: 'specialty', label: '⭐ Specialty Sandwich' },
  ],
  'specials-bakery': [
    { value: 'special', label: '⭐ Special' },
    { value: 'seasonal', label: '🍂 Seasonal Special' },
    { value: 'limited', label: '⏰ Limited Time' },
    { value: 'custom', label: '🎨 Custom Special' },
  ],
}

export const DEFAULT_ITEM_TYPES = [
  { value: 'entree', label: '🍽️ Main Entree' },
  { value: 'side', label: '🍟 Side Dish' },
  { value: 'drink', label: '🥤 Beverage' },
  { value: 'dessert', label: '🍰 Dessert' },
  { value: 'appetizer', label: '🥗 Appetizer' },
  { value: 'salad', label: '🥗 Salad' },
  { value: 'sandwich', label: '🥪 Sandwich' },
  { value: 'soup', label: '🍲 Soup' },
  { value: 'breakfast', label: '🍳 Breakfast' },
  { value: 'bundle', label: '📦 Bundle/Combo' },
]

// ============================================
// Sub Type Options
// ============================================

export const SUB_TYPES: Record<string, Record<string, {value: string, label: string}[]>> = {
  ...RESTAURANT_SUB_TYPES,
}

export const DEFAULT_SUB_TYPES = [
  { value: 'regular', label: '📝 Regular' },
  { value: 'special', label: '⭐ Special' },
  { value: 'premium', label: '💎 Premium' },
]

// ============================================
// Utility Functions
// ============================================

export function getCategoriesForStoreType(storeType: string): {value: string, label: string}[] {
  return STORE_TYPE_CATEGORIES[storeType] || CATEGORIES
}

export function getAvailableItemTypes(category: string): {value: string, label: string}[] {
  return ITEM_TYPES[category] || DEFAULT_ITEM_TYPES
}

export function isTypeValidForCategory(type: string, category: string): boolean {
  const availableTypes = getAvailableItemTypes(category)
  return availableTypes.some(itemType => itemType.value === type)
}

export function getAvailableSubTypes(category: string, type: string): {value: string, label: string}[] {
  if (!category || !type) return DEFAULT_SUB_TYPES
  return SUB_TYPES[category]?.[type] || DEFAULT_SUB_TYPES
}

export function isSubTypeValidForCategoryType(subtype: string, category: string, type: string): boolean {
  const availableSubTypes = getAvailableSubTypes(category, type)
  return availableSubTypes.some(subType => subType.value === subtype)
}
