/**
 * Item Classification Data
 * Centralized mock data for categories, types, and subtypes
 * with utility functions for dynamic form handling
 * Now supports store type specific categorization
 */

// ============================================
// Store Type Specific Categories
// ============================================

export const STORE_TYPE_CATEGORIES: Record<string, Array<{value: string, label: string}>> = {
  RESTAURANT: [
    { value: 'appetizers', label: '🥗 Appetizers' },
    { value: 'entrees', label: '🍽️ Entrees' },
    { value: 'sandwiches', label: '🥪 Sandwiches' },
    { value: 'salads', label: '🥗 Salads' },
    { value: 'soups', label: '🍲 Soups' },
    { value: 'sides', label: '🍟 Sides' },
    { value: 'desserts', label: '🍰 Desserts' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'breakfast', label: '🍳 Breakfast' },
    { value: 'specials', label: '⭐ Specials' },
    { value: 'pasta', label: '🍝 Pasta & Noodles' },
    { value: 'pizza', label: '🍕 Pizza' },
    { value: 'burgers', label: '🍔 Burgers' },
    { value: 'seafood', label: '🦐 Seafood' },
    { value: 'steak-house', label: '🥩 Steak House' },
    { value: 'bbq-grill', label: '🔥 BBQ & Grill' },
    { value: 'mexican', label: '🌮 Mexican Cuisine' },
    { value: 'italian', label: '🍝 Italian Cuisine' },
    { value: 'asian', label: '🥢 Asian Cuisine' },
    { value: 'mediterranean', label: '🫒 Mediterranean' },
    { value: 'vegetarian', label: '🌱 Vegetarian' },
    { value: 'vegan', label: '🥬 Vegan' },
    { value: 'gluten-free', label: '🌾 Gluten-Free' },
    { value: 'kids-menu', label: '👶 Kids Menu' },
    { value: 'tapas-small-plates', label: '🍤 Tapas & Small Plates' },
    { value: 'raw-bar', label: '🦪 Raw Bar' },
    { value: 'comfort-food', label: '🍲 Comfort Food' },
    { value: 'healthy-light', label: '🥗 Healthy & Light' },
    { value: 'late-night', label: '🌙 Late Night' },
    { value: 'brunch', label: '🥞 Brunch' },
    { value: 'happy-hour', label: '🍻 Happy Hour' },
  ],
  CONVENIENCE: [
    { value: 'snacks', label: '🍿 Snacks' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'frozen-foods', label: '🧊 Frozen Foods' },
    { value: 'prepared-meals', label: '🍱 Prepared Meals' },
    { value: 'household', label: '🏠 Household Items' },
    { value: 'personal-care', label: '🧴 Personal Care' },
    { value: 'tobacco', label: '🚬 Tobacco Products' },
    { value: 'lottery', label: '🎰 Lottery' },
    { value: 'candy-chocolate', label: '🍫 Candy & Chocolate' },
    { value: 'chips-crackers', label: '🥨 Chips & Crackers' },
    { value: 'nuts-seeds', label: '🥜 Nuts & Seeds' },
    { value: 'jerky-meat-snacks', label: '🥓 Jerky & Meat Snacks' },
    { value: 'energy-bars', label: '🍫 Energy & Protein Bars' },
    { value: 'dairy-snacks', label: '🧀 Dairy Snacks' },
    { value: 'fruit-snacks', label: '🍎 Fruit Snacks' },
    { value: 'soft-drinks', label: '🥤 Soft Drinks' },
    { value: 'sports-energy', label: '⚡ Sports & Energy Drinks' },
    { value: 'bottled-water', label: '💧 Bottled Water' },
    { value: 'juice-drinks', label: '🧃 Juice & Drinks' },
    { value: 'coffee-tea', label: '☕ Coffee & Tea' },
    { value: 'frozen-pizza', label: '🍕 Frozen Pizza' },
    { value: 'frozen-entrees', label: '🍽️ Frozen Entrees' },
    { value: 'ice-cream-frozen-desserts', label: '🍦 Ice Cream & Frozen Desserts' },
    { value: 'frozen-breakfast', label: '🥞 Frozen Breakfast' },
    { value: 'hot-pockets-sandwiches', label: '🥪 Hot Pockets & Sandwiches' },
    { value: 'microwave-meals', label: '📦 Microwave Meals' },
    { value: 'cleaning-supplies', label: '🧹 Cleaning Supplies' },
    { value: 'paper-products', label: '🧻 Paper Products' },
    { value: 'batteries', label: '🔋 Batteries' },
    { value: 'automotive', label: '🚗 Automotive' },
    { value: 'pet-supplies', label: '🐕 Pet Supplies' },
    { value: 'over-the-counter', label: '💊 Over-the-Counter Medicine' },
    { value: 'first-aid', label: '🩹 First Aid' },
    { value: 'vitamins-supplements', label: '💊 Vitamins & Supplements' },
    { value: 'sunscreen-insect', label: '☀️ Sunscreen & Insect Repellent' },
    { value: 'phone-accessories', label: '📱 Phone Accessories' },
    { value: 'magazines-books', label: '📚 Magazines & Books' },
    { value: 'gift-cards', label: '🎁 Gift Cards' },
  ],
  GROCERY: [
    { value: 'produce', label: '🥬 Fresh Produce' },
    { value: 'meat', label: '🥩 Meat & Poultry' },
    { value: 'seafood', label: '🐟 Seafood' },
    { value: 'dairy', label: '🥛 Dairy & Eggs' },
    { value: 'bakery', label: '🍞 Bakery' },
    { value: 'canned-goods', label: '🥫 Canned Goods' },
    { value: 'dry-goods', label: '📦 Dry Goods' },
    { value: 'frozen-foods', label: '🧊 Frozen Foods' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'snacks', label: '🍿 Snacks' },
    { value: 'household', label: '🏠 Household' },
    { value: 'personal-care', label: '🧴 Personal Care' },
    { value: 'fresh-vegetables', label: '🥦 Fresh Vegetables' },
    { value: 'fresh-fruits', label: '🍎 Fresh Fruits' },
    { value: 'herbs-spices', label: '🌿 Herbs & Spices' },
    { value: 'organic-produce', label: '🌱 Organic Produce' },
    { value: 'exotic-fruits', label: '🥭 Exotic Fruits' },
    { value: 'berries', label: '🫐 Berries' },
    { value: 'citrus', label: '🍊 Citrus Fruits' },
    { value: 'tropical-fruits', label: '🍍 Tropical Fruits' },
    { value: 'leafy-greens', label: '🥬 Leafy Greens' },
    { value: 'root-vegetables', label: '🥕 Root Vegetables' },
    { value: 'cruciferous', label: '🥦 Cruciferous Vegetables' },
    { value: 'nightshade', label: '🍅 Nightshade Vegetables' },
    { value: 'allium', label: '🧅 Allium Vegetables' },
    { value: 'squash-gourds', label: '🎃 Squash & Gourds' },
    { value: 'beef', label: '🥩 Beef' },
    { value: 'poultry', label: '🍗 Poultry' },
    { value: 'pork', label: '🥓 Pork' },
    { value: 'lamb', label: '🐑 Lamb' },
    { value: 'veal', label: '🐄 Veal' },
    { value: 'deli-meat', label: '🥓 Deli Meat' },
    { value: 'ground-meat', label: '🍔 Ground Meat' },
    { value: 'sausages', label: '🌭 Sausages' },
    { value: 'bacon-cured', label: '🥓 Bacon & Cured Meats' },
    { value: 'fresh-fish', label: '🐟 Fresh Fish' },
    { value: 'shellfish', label: '🦐 Shellfish' },
    { value: 'frozen-seafood', label: '🧊 Frozen Seafood' },
    { value: 'smoked-cured', label: '🍖 Smoked & Cured Seafood' },
    { value: 'milk-cream', label: '🥛 Milk & Cream' },
    { value: 'cheese', label: '🧀 Cheese' },
    { value: 'yogurt', label: '🥛 Yogurt' },
    { value: 'butter-margarine', label: '🧈 Butter & Margarine' },
    { value: 'eggs', label: '🥚 Eggs' },
    { value: 'sour-cream', label: '🥛 Sour Cream & Cream Cheese' },
    { value: 'fresh-bread', label: '🍞 Fresh Bread' },
    { value: 'rolls-buns', label: '🥖 Rolls & Buns' },
    { value: 'pastries', label: '🥐 Pastries' },
    { value: 'tortillas-flatbread', label: '🫓 Tortillas & Flatbread' },
    { value: 'bagels', label: '🥯 Bagels' },
    { value: 'english-muffins', label: '🍞 English Muffins' },
    { value: 'canned-vegetables', label: '🥫 Canned Vegetables' },
    { value: 'canned-fruits', label: '🥫 Canned Fruits' },
    { value: 'canned-soup', label: '🥫 Canned Soup' },
    { value: 'canned-meat-fish', label: '🥫 Canned Meat & Fish' },
    { value: 'canned-beans', label: '🥫 Canned Beans' },
    { value: 'canned-tomatoes', label: '🥫 Canned Tomatoes' },
    { value: 'pasta-rice', label: '🍝 Pasta & Rice' },
    { value: 'grains-cereal', label: '🌾 Grains & Cereal' },
    { value: 'flour-baking', label: '🌾 Flour & Baking' },
    { value: 'beans-legumes', label: '🫘 Beans & Legumes' },
    { value: 'nuts-seeds-dry', label: '🥜 Nuts & Seeds' },
    { value: 'dried-fruit', label: '🍇 Dried Fruit' },
    { value: 'spices-seasonings', label: '🌶️ Spices & Seasonings' },
    { value: 'oils-vinegars', label: '🫒 Oils & Vinegars' },
    { value: 'sauces-condiments', label: '🍯 Sauces & Condiments' },
    { value: 'frozen-vegetables', label: '🧊 Frozen Vegetables' },
    { value: 'frozen-fruits', label: '🧊 Frozen Fruits' },
    { value: 'frozen-meals', label: '🍽️ Frozen Meals' },
    { value: 'frozen-desserts', label: '🍦 Frozen Desserts' },
    { value: 'frozen-bread', label: '🧊 Frozen Bread' },
    { value: 'coffee', label: '☕ Coffee' },
    { value: 'tea', label: '🍵 Tea' },
    { value: 'juice', label: '🧃 Juice' },
    { value: 'soda-carbonated', label: '🥤 Soda & Carbonated' },
    { value: 'water', label: '💧 Water' },
    { value: 'sports-drinks', label: '⚡ Sports Drinks' },
    { value: 'energy-drinks', label: '⚡ Energy Drinks' },
    { value: 'chips-pretzels', label: '🥨 Chips & Pretzels' },
    { value: 'crackers', label: '🍪 Crackers' },
    { value: 'popcorn', label: '🍿 Popcorn' },
    { value: 'granola-bars', label: '🍫 Granola & Bars' },
    { value: 'fruit-snacks', label: '🍎 Fruit Snacks' },
    { value: 'cleaning-products', label: '🧹 Cleaning Products' },
    { value: 'paper-towels', label: '🧻 Paper Towels' },
    { value: 'trash-bags', label: '🗑️ Trash Bags' },
    { value: 'dish-soap', label: '🧴 Dish Soap' },
    { value: 'laundry-detergent', label: '🧺 Laundry Detergent' },
    { value: 'soap-body-wash', label: '🧼 Soap & Body Wash' },
    { value: 'shampoo-conditioner', label: '🧴 Shampoo & Conditioner' },
    { value: 'toothpaste', label: '🦷 Toothpaste' },
    { value: 'deodorant', label: '🦹 Deodorant' },
    { value: 'skincare', label: '🧴 Skincare' },
    { value: 'hair-care', label: '💇 Hair Care' },
    { value: 'oral-care', label: '🦷 Oral Care' },
  ],
  HOME_KITCHEN: [
    { value: 'prepared-meals', label: '🍱 Prepared Meals' },
    { value: 'entrees', label: '🍽️ Entrees' },
    { value: 'sides', label: '🍟 Sides' },
    { value: 'desserts', label: '🍰 Desserts' },
    { value: 'beverages', label: '🥤 Beverages' },
    { value: 'specials', label: '⭐ Daily Specials' },
  ],
  BAKERY: [
    { value: 'bread', label: '🍞 Bread' },
    { value: 'pastries', label: '🥐 Pastries' },
    { value: 'cakes', label: '🎂 Cakes' },
    { value: 'cookies', label: '🍪 Cookies' },
    { value: 'pies', label: '🥧 Pies' },
    { value: 'desserts', label: '🍰 Desserts' },
    { value: 'beverages', label: '☕ Coffee & Tea' },
    { value: 'sandwiches', label: '🥪 Sandwiches' },
    { value: 'specials', label: '⭐ Special Orders' },
    { value: 'artisan-bread', label: '🥖 Artisan Bread' },
    { value: 'sourdough', label: '🍞 Sourdough' },
    { value: 'whole-grain', label: '🌾 Whole Grain' },
    { value: 'gluten-free-bread', label: '🌾 Gluten-Free Bread' },
    { value: 'ciabatta', label: '🥖 Ciabatta' },
    { value: 'focaccia', label: '🫓 Focaccia' },
    { value: 'baguette', label: '🥖 Baguette' },
    { value: 'rye-bread', label: '🍞 Rye Bread' },
    { value: 'pumpernickel', label: '🍞 Pumpernickel' },
    { value: 'multigrain', label: '🌾 Multigrain' },
    { value: 'brioche', label: '🥐 Brioche' },
    { value: 'challah', label: '🥖 Challah' },
    { value: 'french-bread', label: '🥖 French Bread' },
    { value: 'italian-bread', label: '🍞 Italian Bread' },
    { value: 'croissants', label: '🥐 Croissants' },
    { value: 'danish-pastries', label: '🥐 Danish Pastries' },
    { value: 'eclairs', label: '🥐 Éclairs' },
    { value: 'profiteroles', label: '🥐 Profiteroles' },
    { value: 'tarts', label: '🥧 Tarts' },
    { value: 'quiche', label: '🥧 Quiche' },
    { value: 'puff-pastry', label: '🥐 Puff Pastry' },
    { value: 'phyllo-pastry', label: '🥐 Phyllo Pastry' },
    { value: 'baklava', label: '🥐 Baklava' },
    { value: 'strudel', label: '🥐 Strudel' },
    { value: 'birthday-cakes', label: '🎂 Birthday Cakes' },
    { value: 'wedding-cakes', label: '👰 Wedding Cakes' },
    { value: 'cheesecake', label: '🍰 Cheesecake' },
    { value: 'chocolate-cake', label: '🍫 Chocolate Cake' },
    { value: 'vanilla-cake', label: '🍦 Vanilla Cake' },
    { value: 'fruit-cake', label: '🍎 Fruit Cake' },
    { value: 'carrot-cake', label: '🥕 Carrot Cake' },
    { value: 'red-velvet', label: '🍰 Red Velvet' },
    { value: 'angel-food', label: '👼 Angel Food' },
    { value: 'devil-food', label: '😈 Devil Food' },
    { value: 'pound-cake', label: '🍰 Pound Cake' },
    { value: 'sponge-cake', label: '🍰 Sponge Cake' },
    { value: 'genoise', label: '🍰 Genoise' },
    { value: 'chocolate-chip', label: '🍪 Chocolate Chip' },
    { value: 'oatmeal-raisin', label: '🍪 Oatmeal Raisin' },
    { value: 'peanut-butter', label: '🥜 Peanut Butter' },
    { value: 'sugar-cookies', label: '🍪 Sugar Cookies' },
    { value: 'shortbread', label: '🍪 Shortbread' },
    { value: 'gingersnaps', label: '🍪 Gingersnaps' },
    { value: 'macarons', label: '🍪 Macarons' },
    { value: 'biscotti', label: '🍪 Biscotti' },
    { value: 'fortune-cookies', label: '🥠 Fortune Cookies' },
    { value: 'butter-cookies', label: '🍪 Butter Cookies' },
    { value: 'lemon-cookies', label: '🍋 Lemon Cookies' },
    { value: 'apple-pie', label: '🍎 Apple Pie' },
    { value: 'pumpkin-pie', label: '🎃 Pumpkin Pie' },
    { value: 'cherry-pie', label: '🍒 Cherry Pie' },
    { value: 'pecan-pie', label: '🥜 Pecan Pie' },
    { value: 'blueberry-pie', label: '🫐 Blueberry Pie' },
    { value: 'lemon-meringue', label: '🍋 Lemon Meringue' },
    { value: 'key-lime-pie', label: '🍋 Key Lime Pie' },
    { value: 'chocolate-pie', label: '🍫 Chocolate Pie' },
    { value: 'coconut-cream', label: '🥥 Coconut Cream' },
    { value: 'banana-cream', label: '🍌 Banana Cream' },
    { value: 'custard-pies', label: '🍮 Custard Pies' },
    { value: 'mousse', label: '🍮 Mousse' },
    { value: 'pudding', label: '🍮 Pudding' },
    { value: 'flan', label: '🍮 Flan' },
    { value: 'creme-brulee', label: '🍮 Crème Brûlée' },
    { value: 'panna-cotta', label: '🍮 Panna Cotta' },
    { value: 'tiramisu', label: '🍰 Tiramisu' },
    { value: 'gelato', label: '🍨 Gelato' },
    { value: 'sorbet', label: '🍨 Sorbet' },
    { value: 'espresso', label: '☕ Espresso' },
    { value: 'cappuccino', label: '☕ Cappuccino' },
    { value: 'latte', label: '☕ Latte' },
    { value: 'americano', label: '☕ Americano' },
    { value: 'macchiato', label: '☕ Macchiato' },
    { value: 'specialty-coffee', label: '☕ Specialty Coffee' },
    { value: 'iced-coffee', label: '🧊 Iced Coffee' },
    { value: 'hot-tea', label: '🍵 Hot Tea' },
    { value: 'iced-tea', label: '🧊 Iced Tea' },
    { value: 'herbal-tea', label: '🌿 Herbal Tea' },
    { value: 'chai', label: '🍵 Chai' },
    { value: 'club-sandwich', label: '🥪 Club Sandwich' },
    { value: 'blt', label: '🥪 BLT' },
    { value: 'turkey-club', label: '🥪 Turkey Club' },
    { value: 'veg-sandwich', label: '🥪 Veg Sandwich' },
    { value: 'panini', label: '🥪 Panini' },
    { value: 'custom-cakes', label: '🎂 Custom Cakes' },
    { value: 'seasonal-specials', label: '🍂 Seasonal Specials' },
    { value: 'holiday-items', label: '🎄 Holiday Items' },
    { value: 'gluten-free-items', label: '🌾 Gluten-Free Items' },
    { value: 'vegan-items', label: '🌱 Vegan Items' },
  ],
  RETAIL: [
    { value: 'electronics', label: '📱 Electronics' },
    { value: 'clothing', label: '👕 Clothing' },
    { value: 'home-goods', label: '🏠 Home Goods' },
    { value: 'toys', label: '🧸 Toys & Games' },
    { value: 'books', label: '📚 Books' },
    { value: 'sports', label: '⚽ Sports & Outdoors' },
    { value: 'beauty', label: '💄 Beauty & Personal Care' },
    { value: 'automotive', label: '🚗 Automotive' },
    { value: 'seasonal', label: '🎄 Seasonal Items' },
  ],
  OTHER: [
    { value: 'miscellaneous', label: '📦 Miscellaneous' },
    { value: 'services', label: '🔧 Services' },
    { value: 'custom', label: '🎨 Custom Items' },
    { value: 'specials', label: '⭐ Special Items' },
  ],
}

// Legacy categories for backward compatibility
export const CATEGORIES = [
  { value: 'appetizers', label: '🥗 Appetizers' },
  { value: 'entrees', label: '🍽️ Entrees' },
  { value: 'sandwiches', label: '🥪 Sandwiches' },
  { value: 'salads', label: '🥗 Salads' },
  { value: 'soups', label: '🍲 Soups' },
  { value: 'sides', label: '🍟 Sides' },
  { value: 'desserts', label: '🍰 Desserts' },
  { value: 'beverages', label: '🥤 Beverages' },
  { value: 'breakfast', label: '🍳 Breakfast' },
  { value: 'specials', label: '⭐ Specials' },
]

// ============================================
// Item Type Options
// ============================================

export const ITEM_TYPES: Record<string, Array<{value: string, label: string}>> = {
  appetizers: [
    { value: 'appetizer', label: '🥗 Appetizer' },
    { value: 'side', label: '🍟 Side Dish' },
    { value: 'bundle', label: '📦 Appetizer Combo' },
  ],
  entrees: [
    { value: 'entree', label: '🍽️ Main Entree' },
    { value: 'bundle', label: '📦 Entree Combo' },
  ],
  sandwiches: [
    { value: 'sandwich', label: '🥪 Sandwich' },
    { value: 'entree', label: '🍽️ Sandwich Entree' },
    { value: 'bundle', label: '📦 Sandwich Combo' },
  ],
  salads: [
    { value: 'salad', label: '🥗 Salad' },
    { value: 'side', label: '🍟 Side Salad' },
    { value: 'entree', label: '🍽️ Salad Entree' },
  ],
  soups: [
    { value: 'soup', label: '🍲 Soup' },
    { value: 'side', label: '🍟 Soup Side' },
    { value: 'entree', label: '🍽️ Soup Entree' },
  ],
  sides: [
    { value: 'side', label: '🍟 Side Dish' },
    { value: 'appetizer', label: '🥗 Side Appetizer' },
  ],
  desserts: [
    { value: 'dessert', label: '🍰 Dessert' },
    { value: 'bundle', label: '📦 Dessert Combo' },
  ],
  beverages: [
    { value: 'drink', label: '🥤 Beverage' },
    { value: 'side', label: '🍟 Drink Side' },
  ],
  breakfast: [
    { value: 'breakfast', label: '🍳 Breakfast' },
    { value: 'entree', label: '🍽️ Breakfast Entree' },
    { value: 'bundle', label: '📦 Breakfast Combo' },
  ],
  specials: [
    { value: 'entree', label: '🍽️ Special Entree' },
    { value: 'bundle', label: '📦 Special Combo' },
    { value: 'appetizer', label: '🥗 Special Appetizer' },
    { value: 'dessert', label: '🍰 Special Dessert' },
  ],
  // New restaurant categories
  pasta: [
    { value: 'pasta', label: '🍝 Pasta Dish' },
    { value: 'entree', label: '🍽️ Pasta Entree' },
    { value: 'bundle', label: '📦 Pasta Combo' },
    { value: 'side', label: '🍟 Pasta Side' },
  ],
  pizza: [
    { value: 'pizza', label: '🍕 Pizza' },
    { value: 'entree', label: '🍽️ Pizza Entree' },
    { value: 'bundle', label: '📦 Pizza Combo' },
    { value: 'slice', label: '🍕 Pizza Slice' },
  ],
  burgers: [
    { value: 'burger', label: '🍔 Burger' },
    { value: 'entree', label: '🍽️ Burger Entree' },
    { value: 'bundle', label: '📦 Burger Combo' },
    { value: 'slider', label: '🍔 Slider' },
  ],
  'seafood-restaurant': [
    { value: 'seafood', label: '🦐 Seafood Dish' },
    { value: 'entree', label: '🍽️ Seafood Entree' },
    { value: 'bundle', label: '📦 Seafood Combo' },
    { value: 'appetizer', label: '🥗 Seafood Appetizer' },
  ],
  'steak-house': [
    { value: 'steak', label: '🥩 Steak' },
    { value: 'entree', label: '🍽️ Steak Entree' },
    { value: 'bundle', label: '📦 Steak Combo' },
    { value: 'premium', label: '💎 Premium Cut' },
  ],
  'bbq-grill': [
    { value: 'bbq', label: '🔥 BBQ Dish' },
    { value: 'entree', label: '🍽️ BBQ Entree' },
    { value: 'bundle', label: '📦 BBQ Combo' },
    { value: 'platter', label: '🍽️ BBQ Platter' },
  ],
  mexican: [
    { value: 'mexican', label: '🌮 Mexican Dish' },
    { value: 'entree', label: '🍽️ Mexican Entree' },
    { value: 'bundle', label: '📦 Mexican Combo' },
    { value: 'taco', label: '🌮 Taco' },
  ],
  italian: [
    { value: 'italian', label: '🍝 Italian Dish' },
    { value: 'entree', label: '🍽️ Italian Entree' },
    { value: 'bundle', label: '📦 Italian Combo' },
    { value: 'classic', label: '🍝 Italian Classic' },
  ],
  asian: [
    { value: 'asian', label: '🥢 Asian Dish' },
    { value: 'entree', label: '🍽️ Asian Entree' },
    { value: 'bundle', label: '📦 Asian Combo' },
    { value: 'stir-fry', label: '🥢 Stir Fry' },
  ],
  mediterranean: [
    { value: 'mediterranean', label: '🫒 Mediterranean Dish' },
    { value: 'entree', label: '🍽️ Mediterranean Entree' },
    { value: 'bundle', label: '📦 Mediterranean Combo' },
    { value: 'meze', label: '🫒 Meze' },
  ],
  vegetarian: [
    { value: 'vegetarian', label: '🌱 Vegetarian Dish' },
    { value: 'entree', label: '🍽️ Vegetarian Entree' },
    { value: 'bundle', label: '📦 Vegetarian Combo' },
    { value: 'plant-based', label: '🌿 Plant-Based' },
  ],
  vegan: [
    { value: 'vegan', label: '🥬 Vegan Dish' },
    { value: 'entree', label: '🍽️ Vegan Entree' },
    { value: 'bundle', label: '📦 Vegan Combo' },
    { value: 'raw', label: '🥗 Raw Vegan' },
  ],
  'gluten-free': [
    { value: 'gluten-free', label: '🌾 Gluten-Free Dish' },
    { value: 'entree', label: '🍽️ Gluten-Free Entree' },
    { value: 'bundle', label: '📦 Gluten-Free Combo' },
    { value: 'certified', label: '✅ Certified GF' },
  ],
  'kids-menu': [
    { value: 'kids', label: '👶 Kids Meal' },
    { value: 'entree', label: '🍽️ Kids Entree' },
    { value: 'bundle', label: '📦 Kids Combo' },
    { value: 'side', label: '🍟 Kids Side' },
  ],
  'tapas-small-plates': [
    { value: 'tapas', label: '🍤 Tapas' },
    { value: 'small-plate', label: '🍤 Small Plate' },
    { value: 'bundle', label: '📦 Tapas Combo' },
    { value: 'shareable', label: '👥 Shareable' },
  ],
  'raw-bar': [
    { value: 'raw', label: '🦪 Raw Item' },
    { value: 'appetizer', label: '🥗 Raw Appetizer' },
    { value: 'bundle', label: '📦 Raw Combo' },
    { value: 'oyster', label: '🦪 Oyster' },
  ],
  'comfort-food': [
    { value: 'comfort', label: '🍲 Comfort Food' },
    { value: 'entree', label: '🍽️ Comfort Entree' },
    { value: 'bundle', label: '📦 Comfort Combo' },
    { value: 'homestyle', label: '🏠 Homestyle' },
  ],
  'healthy-light': [
    { value: 'healthy', label: '🥗 Healthy Dish' },
    { value: 'entree', label: '🍽️ Healthy Entree' },
    { value: 'bundle', label: '📦 Healthy Combo' },
    { value: 'light', label: '🥗 Light Option' },
  ],
  'late-night': [
    { value: 'late-night', label: '🌙 Late Night Dish' },
    { value: 'entree', label: '🍽️ Late Night Entree' },
    { value: 'bundle', label: '📦 Late Night Combo' },
    { value: 'snack', label: '🍿 Late Night Snack' },
  ],
  brunch: [
    { value: 'brunch', label: '🥞 Brunch Dish' },
    { value: 'entree', label: '🍽️ Brunch Entree' },
    { value: 'bundle', label: '📦 Brunch Combo' },
    { value: 'bottomless', label: '🥞 Bottomless Brunch' },
  ],
  'happy-hour': [
    { value: 'happy-hour', label: '🍻 Happy Hour Item' },
    { value: 'special', label: '⭐ Happy Hour Special' },
    { value: 'bundle', label: '📦 Happy Hour Combo' },
    { value: 'drink', label: '🍻 Happy Hour Drink' },
  ],
  // Convenience store categories
  snacks: [
    { value: 'snack', label: '🍿 Snack' },
    { value: 'bundle', label: '📦 Snack Pack' },
    { value: 'single', label: '🍿 Single Serve' },
    { value: 'family', label: '👨‍👩‍👧‍👦 Family Size' },
  ],
  'candy-chocolate': [
    { value: 'candy', label: '🍫 Candy' },
    { value: 'chocolate', label: '🍫 Chocolate' },
    { value: 'bundle', label: '📦 Candy Pack' },
    { value: 'premium', label: '💎 Premium Chocolate' },
  ],
  'chips-crackers': [
    { value: 'chips', label: '🥨 Chips' },
    { value: 'crackers', label: '🍪 Crackers' },
    { value: 'bundle', label: '📦 Variety Pack' },
    { value: 'single', label: '🥨 Single Bag' },
  ],
  'nuts-seeds': [
    { value: 'nuts', label: '🥜 Nuts' },
    { value: 'seeds', label: '🌰 Seeds' },
    { value: 'bundle', label: '📦 Nut Mix' },
    { value: 'trail-mix', label: '🥾 Trail Mix' },
  ],
  'jerky-meat-snacks': [
    { value: 'jerky', label: '🥓 Jerky' },
    { value: 'meat-stick', label: '🥓 Meat Stick' },
    { value: 'bundle', label: '📦 Jerky Pack' },
    { value: 'single', label: '🥓 Single Serve' },
  ],
  'energy-bars': [
    { value: 'energy-bar', label: '🍫 Energy Bar' },
    { value: 'protein-bar', label: '💪 Protein Bar' },
    { value: 'bundle', label: '📦 Bar Box' },
    { value: 'meal-replacement', label: '🍽️ Meal Replacement' },
  ],
  'dairy-snacks': [
    { value: 'dairy', label: '🧀 Dairy Snack' },
    { value: 'cheese', label: '🧀 Cheese' },
    { value: 'bundle', label: '📦 Cheese Pack' },
    { value: 'single', label: '🧀 Single Serve' },
  ],
  'fruit-snacks': [
    { value: 'fruit', label: '🍎 Fruit Snack' },
    { value: 'dried', label: '🍇 Dried Fruit' },
    { value: 'bundle', label: '📦 Fruit Pack' },
    { value: 'organic', label: '🌱 Organic Fruit' },
  ],
  'soft-drinks': [
    { value: 'soft-drink', label: '🥤 Soft Drink' },
    { value: 'soda', label: '🥤 Soda' },
    { value: 'bundle', label: '📦 Drink Pack' },
    { value: 'diet', label: '🥤 Diet Option' },
  ],
  'sports-energy': [
    { value: 'sports', label: '⚡ Sports Drink' },
    { value: 'energy', label: '⚡ Energy Drink' },
    { value: 'bundle', label: '📦 Energy Pack' },
    { value: 'zero-sugar', label: '🚫 Zero Sugar' },
  ],
  'bottled-water': [
    { value: 'water', label: '💧 Water' },
    { value: 'spring', label: '💧 Spring Water' },
    { value: 'mineral', label: '💧 Mineral Water' },
    { value: 'bundle', label: '📦 Water Pack' },
  ],
  'juice-drinks': [
    { value: 'juice', label: '🧃 Juice' },
    { value: 'drink', label: '🥤 Fruit Drink' },
    { value: 'bundle', label: '📦 Juice Pack' },
    { value: 'fresh', label: '🍊 Fresh Juice' },
  ],
  'coffee-tea': [
    { value: 'coffee', label: '☕ Coffee' },
    { value: 'tea', label: '🍵 Tea' },
    { value: 'ready-to-drink', label: '🥤 Ready to Drink' },
    { value: 'instant', label: '⚡ Instant' },
  ],
  'frozen-foods': [
    { value: 'frozen', label: '🧊 Frozen Food' },
    { value: 'meal', label: '🍽️ Frozen Meal' },
    { value: 'bundle', label: '📦 Frozen Pack' },
    { value: 'single', label: '🧊 Single Serve' },
  ],
  'prepared-meals': [
    { value: 'prepared', label: '🍱 Prepared Meal' },
    { value: 'fresh', label: '🍕 Fresh Meal' },
    { value: 'bundle', label: '📦 Meal Pack' },
    { value: 'single', label: '🍱 Single Meal' },
  ],
  household: [
    { value: 'household', label: '🏠 Household Item' },
    { value: 'cleaning', label: '🧹 Cleaning Supply' },
    { value: 'paper', label: '🧻 Paper Product' },
    { value: 'bundle', label: '📦 Household Pack' },
  ],
  'personal-care': [
    { value: 'personal', label: '🧴 Personal Care' },
    { value: 'health', label: '💊 Health Item' },
    { value: 'beauty', label: '💄 Beauty Product' },
    { value: 'bundle', label: '📦 Care Pack' },
  ],
  tobacco: [
    { value: 'tobacco', label: '🚬 Tobacco' },
    { value: 'cigarettes', label: '🚬 Cigarettes' },
    { value: 'cigars', label: '🚬 Cigars' },
    { value: 'accessories', label: '🔧 Accessories' },
  ],
  lottery: [
    { value: 'lottery', label: '🎰 Lottery' },
    { value: 'ticket', label: '🎫 Lottery Ticket' },
    { value: 'scratch', label: '🎲 Scratch Card' },
    { value: 'instant', label: '⚡ Instant Win' },
  ],
  // Grocery categories (simplified for brevity, but following the same pattern)
  produce: [
    { value: 'produce', label: '🥬 Produce' },
    { value: 'fresh', label: '🍎 Fresh Produce' },
    { value: 'organic', label: '🌱 Organic Produce' },
    { value: 'bundle', label: '📦 Produce Pack' },
  ],
  meat: [
    { value: 'meat', label: '🥩 Meat' },
    { value: 'fresh', label: '🍖 Fresh Meat' },
    { value: 'packaged', label: '📦 Packaged Meat' },
    { value: 'organic', label: '🌱 Organic Meat' },
  ],
  seafood: [
    { value: 'seafood', label: '🐟 Seafood' },
    { value: 'fresh', label: '🦐 Fresh Seafood' },
    { value: 'frozen', label: '🧊 Frozen Seafood' },
    { value: 'packaged', label: '📦 Packaged Seafood' },
  ],
  dairy: [
    { value: 'dairy', label: '🥛 Dairy' },
    { value: 'milk', label: '🥛 Milk' },
    { value: 'cheese', label: '🧀 Cheese' },
    { value: 'yogurt', label: '🥛 Yogurt' },
  ],
  bakery: [
    { value: 'bakery', label: '🍞 Bakery' },
    { value: 'bread', label: '🍞 Bread' },
    { value: 'pastry', label: '🥐 Pastry' },
    { value: 'fresh', label: '🍕 Fresh Bakery' },
  ],
  'canned-goods': [
    { value: 'canned', label: '🥫 Canned Goods' },
    { value: 'vegetables', label: '🥫 Canned Vegetables' },
    { value: 'fruits', label: '🥫 Canned Fruits' },
    { value: 'soups', label: '🥫 Canned Soups' },
  ],
  'dry-goods': [
    { value: 'dry', label: '📦 Dry Goods' },
    { value: 'grains', label: '🌾 Grains' },
    { value: 'pasta', label: '🍝 Pasta' },
    { value: 'beans', label: '🫘 Beans' },
  ],
  'beverages-grocery': [
    { value: 'beverage', label: '🥤 Beverage' },
    { value: 'drink', label: '🥤 Drink' },
    { value: 'juice', label: '🧃 Juice' },
    { value: 'water', label: '💧 Water' },
  ],
  // Bakery categories
  bread: [
    { value: 'bread', label: '🍞 Bread' },
    { value: 'loaf', label: '🍞 Loaf' },
    { value: 'artisan', label: '🥖 Artisan' },
    { value: 'specialty', label: '⭐ Specialty' },
  ],
  pastries: [
    { value: 'pastry', label: '🥐 Pastry' },
    { value: 'fresh', label: '🥐 Fresh Pastry' },
    { value: 'frozen', label: '🧊 Frozen Pastry' },
    { value: 'specialty', label: '⭐ Specialty Pastry' },
  ],
  cakes: [
    { value: 'cake', label: '🎂 Cake' },
    { value: 'slice', label: '🍰 Cake Slice' },
    { value: 'whole', label: '🎂 Whole Cake' },
    { value: 'custom', label: '🎨 Custom Cake' },
  ],
  cookies: [
    { value: 'cookie', label: '🍪 Cookie' },
    { value: 'pack', label: '📦 Cookie Pack' },
    { value: 'single', label: '🍪 Single Cookie' },
    { value: 'gourmet', label: '💎 Gourmet' },
  ],
  pies: [
    { value: 'pie', label: '🥧 Pie' },
    { value: 'slice', label: '🥧 Pie Slice' },
    { value: 'whole', label: '🥧 Whole Pie' },
    { value: 'specialty', label: '⭐ Specialty Pie' },
  ],
  'desserts-bakery': [
    { value: 'dessert', label: '🍰 Dessert' },
    { value: 'single', label: '🍰 Single Dessert' },
    { value: 'platter', label: '🍽️ Dessert Platter' },
    { value: 'specialty', label: '⭐ Specialty Dessert' },
  ],
  'sandwiches-bakery': [
    { value: 'sandwich', label: '🥪 Sandwich' },
    { value: 'fresh', label: '🥪 Fresh Sandwich' },
    { value: 'grilled', label: '🔥 Grilled Sandwich' },
    { value: 'specialty', label: '⭐ Specialty Sandwich' },
  ],
  'specials-bakery': [
    { value: 'special', label: '⭐ Special' },
    { value: 'seasonal', label: '🍂 Seasonal Special' },
    { value: 'limited', label: '⏰ Limited Time' },
    { value: 'custom', label: '🎨 Custom Special' },
  ],
}

export const DEFAULT_ITEM_TYPES = [
  { value: 'entree', label: '🍽️ Main Entree' },
  { value: 'side', label: '🍟 Side Dish' },
  { value: 'drink', label: '🥤 Beverage' },
  { value: 'dessert', label: '🍰 Dessert' },
  { value: 'appetizer', label: '🥗 Appetizer' },
  { value: 'salad', label: '🥗 Salad' },
  { value: 'sandwich', label: '🥪 Sandwich' },
  { value: 'soup', label: '🍲 Soup' },
  { value: 'breakfast', label: '🍳 Breakfast' },
  { value: 'bundle', label: '📦 Bundle/Combo' },
]

// ============================================
// Sub Type Options
// ============================================

export const SUB_TYPES: Record<string, Record<string, Array<{value: string, label: string}>>> = {
  appetizers: {
    appetizer: [
      { value: 'cold', label: '🥒 Cold Appetizer' },
      { value: 'hot', label: '🔥 Hot Appetizer' },
      { value: 'fried', label: '🍟 Fried Appetizer' },
      { value: 'grilled', label: '🔥 Grilled Appetizer' },
      { value: 'baked', label: '🍕 Baked Appetizer' },
      { value: 'steamed', label: '💨 Steamed Appetizer' },
      { value: 'raw', label: '🥗 Raw Appetizer' },
      { value: 'marinated', label: '🫒 Marinated Appetizer' },
      { value: 'stuffed', label: '🥟 Stuffed Appetizer' },
      { value: 'dipped', label: '🫕 Dipped Appetizer' },
    ],
    side: [
      { value: 'small', label: '🥗 Small Side' },
      { value: 'medium', label: '🍽️ Medium Side' },
      { value: 'large', label: '🍽️ Large Side' },
      { value: 'shareable', label: '👥 Shareable Side' },
    ],
    bundle: [
      { value: 'sampler', label: '🎯 Appetizer Sampler' },
      { value: 'combo', label: '📦 Appetizer Combo' },
      { value: 'platter', label: '🍽️ Appetizer Platter' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Platter' },
      { value: 'party', label: '🎉 Party Pack' },
    ],
  },
  entrees: {
    entree: [
      { value: 'beef', label: '🥩 Beef Entree' },
      { value: 'chicken', label: '🍗 Chicken Entree' },
      { value: 'pork', label: '🥓 Pork Entree' },
      { value: 'seafood', label: '🐟 Seafood Entree' },
      { value: 'vegetarian', label: '🥬 Vegetarian Entree' },
      { value: 'vegan', label: '🌱 Vegan Entree' },
      { value: 'lamb', label: '🐑 Lamb Entree' },
      { value: 'duck', label: '🦆 Duck Entree' },
      { value: 'turkey', label: '🦃 Turkey Entree' },
      { value: 'game', label: '🦌 Game Meat' },
      { value: 'pasta', label: '🍝 Pasta Entree' },
      { value: 'rice', label: '🍚 Rice Entree' },
      { value: 'stir-fry', label: '🥢 Stir Fry' },
      { value: 'curry', label: '🍛 Curry' },
      { value: 'roasted', label: '🔥 Roasted' },
      { value: 'grilled', label: '🔥 Grilled' },
      { value: 'pan-seared', label: '🍳 Pan Seared' },
      { value: 'braised', label: '🍲 Braised' },
      { value: 'steamed', label: '💨 Steamed' },
      { value: 'fried', label: '🍟 Fried' },
    ],
    bundle: [
      { value: 'dinner', label: '🍽️ Dinner Bundle' },
      { value: 'family', label: '👨‍👩‍👧‍👦 Family Bundle' },
      { value: 'couple', label: '💑 Couple Bundle' },
      { value: 'executive', label: '💼 Executive Bundle' },
      { value: 'celebration', label: '🎉 Celebration Bundle' },
    ],
  },
  sandwiches: {
    sandwich: [
      { value: 'cold', label: '🥪 Cold Sandwich' },
      { value: 'hot', label: '🔥 Hot Sandwich' },
      { value: 'grilled', label: '🔥 Grilled Sandwich' },
      { value: 'pressed', label: '🍞 Pressed Sandwich' },
      { value: 'wrap', label: '🌯 Wrap' },
      { value: 'toasted', label: '🍞 Toasted Sandwich' },
      { value: 'open-faced', label: '🍞 Open-Faced' },
      { value: 'club', label: '🥪 Club Sandwich' },
      { value: 'submarine', label: '🥖 Submarine' },
      { value: 'panini', label: '🔥 Panini' },
      { value: 'baguette', label: '🥖 Baguette' },
      { value: 'ciabatta', label: '🥖 Ciabatta' },
      { value: 'sourdough', label: '🍞 Sourdough' },
      { value: 'rye', label: '🍞 Rye' },
      { value: 'whole-wheat', label: '🌾 Whole Wheat' },
      { value: 'gluten-free', label: '🌾 Gluten-Free' },
    ],
    entree: [
      { value: 'full', label: '🍽️ Full Sandwich Entree' },
      { value: 'half', label: '🥪 Half Sandwich Entree' },
    ],
    bundle: [
      { value: 'sandwich-meal', label: '🍔 Sandwich Meal' },
      { value: 'sandwich-combo', label: '📦 Sandwich Combo' },
      { value: 'sandwich-platter', label: '🍽️ Sandwich Platter' },
    ],
  },
  // New comprehensive restaurant categories
  pasta: {
    pasta: [
      { value: 'spaghetti', label: '🍝 Spaghetti' },
      { value: 'penne', label: '🍝 Penne' },
      { value: 'fettuccine', label: '🍝 Fettuccine' },
      { value: 'linguine', label: '🍝 Linguine' },
      { value: 'ravioli', label: '🥟 Ravioli' },
      { value: 'tortellini', label: '🥟 Tortellini' },
      { value: 'lasagna', label: '🍝 Lasagna' },
      { value: 'gnocchi', label: '🥔 Gnocchi' },
      { value: 'macaroni', label: '🍝 Macaroni' },
      { value: 'farfalle', label: '🦋 Farfalle' },
      { value: 'rotini', label: '🌀 Rotini' },
      { value: 'cavatappi', label: '🍝 Cavatappi' },
      { value: 'bucatini', label: '🍝 Bucatini' },
      { value: 'pappardelle', label: '🍝 Pappardelle' },
      { value: 'orecchiette', label: '👂 Orecchiette' },
      { value: 'angel-hair', label: '😇 Angel Hair' },
      { value: 'capellini', label: '🍝 Capellini' },
      { value: 'vermicelli', label: '🍝 Vermicelli' },
      { value: 'fusilli', label: '🌀 Fusilli' },
      { value: 'rigatoni', label: '🍝 Rigatoni' },
    ],
    entree: [
      { value: 'creamy', label: '🥛 Creamy Pasta' },
      { value: 'tomato-based', label: '🍅 Tomato-Based' },
      { value: 'pesto', label: '🌿 Pesto' },
      { value: 'alfredo', label: '🧈 Alfredo' },
      { value: 'carbonara', label: '🥓 Carbonara' },
      { value: 'bolognese', label: '🍝 Bolognese' },
      { value: 'marinara', label: '🍅 Marinara' },
      { value: 'arrabbiata', label: '🌶️ Arrabbiata' },
      { value: 'puttanesca', label: '🍝 Puttanesca' },
      { value: 'aglio-e-olio', label: '🧄 Aglio e Olio' },
      { value: 'vongole', label: '🦪 Vongole' },
      { value: 'frutti-di-mare', label: '🦐 Frutti di Mare' },
    ],
    side: [
      { value: 'small', label: '🥗 Small Pasta Side' },
      { value: 'medium', label: '🍽️ Medium Pasta Side' },
      { value: 'garlic-bread', label: '🧄 Garlic Bread Pasta' },
    ],
    bundle: [
      { value: 'pasta-combo', label: '📦 Pasta Combo' },
      { value: 'pasta-family', label: '👨‍👩‍👧‍👦 Pasta Family' },
      { value: 'pasta-feast', label: '🍽️ Pasta Feast' },
    ],
  },
  pizza: {
    pizza: [
      { value: 'margherita', label: '🍕 Margherita' },
      { value: 'pepperoni', label: '🍕 Pepperoni' },
      { value: 'hawaiian', label: '🍕 Hawaiian' },
      { value: 'meat-lovers', label: '🍕 Meat Lovers' },
      { value: 'veggie', label: '🥬 Veggie Pizza' },
      { value: 'supreme', label: '🍕 Supreme' },
      { value: 'bbq-chicken', label: '🍕 BBQ Chicken' },
      { value: 'buffalo-chicken', label: '🍕 Buffalo Chicken' },
      { value: 'margherita', label: '🍕 Margherita' },
      { value: 'four-cheese', label: '🧀 Four Cheese' },
      { value: 'white-pizza', label: '🍕 White Pizza' },
      { value: 'mediterranean', label: '🫒 Mediterranean' },
      { value: 'pesto-chicken', label: '🌿 Pesto Chicken' },
      { value: 'truffle', label: '🍄 Truffle Pizza' },
      { value: 'seafood', label: '🦐 Seafood Pizza' },
      { value: 'prosciutto', label: '🥓 Prosciutto' },
      { value: 'mushroom', label: '🍄 Mushroom Pizza' },
      { value: 'spinach', label: '🥬 Spinach Pizza' },
      { value: 'artichoke', label: '🫒 Artichoke Pizza' },
      { value: 'anchovy', label: '🐟 Anchovy Pizza' },
    ],
    entree: [
      { value: 'personal', label: '🍕 Personal Pizza' },
      { value: 'medium', label: '🍕 Medium Pizza' },
      { value: 'large', label: '🍕 Large Pizza' },
      { value: 'extra-large', label: '🍕 Extra Large' },
      { value: 'family-size', label: '👨‍👩‍👧‍👦 Family Size' },
      { value: 'party-size', label: '🎉 Party Size' },
    ],
    slice: [
      { value: 'cheese-slice', label: '🧀 Cheese Slice' },
      { value: 'pepperoni-slice', label: '🍕 Pepperoni Slice' },
      { value: 'veggie-slice', label: '🥬 Veggie Slice' },
      { value: 'specialty-slice', label: '⭐ Specialty Slice' },
    ],
    bundle: [
      { value: 'pizza-combo', label: '📦 Pizza Combo' },
      { value: 'pizza-party', label: '🎉 Pizza Party' },
      { value: 'pizza-feast', label: '🍽️ Pizza Feast' },
    ],
  },
  burgers: {
    burger: [
      { value: 'classic-beef', label: '🍔 Classic Beef' },
      { value: 'cheeseburger', label: '🧀 Cheeseburger' },
      { value: 'bacon-burger', label: '🥓 Bacon Burger' },
      { value: 'mushroom-swiss', label: '🍄 Mushroom Swiss' },
      { value: 'bbq-burger', label: '🍕 BBQ Burger' },
      { value: 'blue-cheese', label: '🧀 Blue Cheese Burger' },
      { value: 'jalapeno', label: '🌶️ Jalapeno Burger' },
      { value: 'onion-ring', label: '🧅 Onion Ring Burger' },
      { value: 'guacamole', label: '🥑 Guacamole Burger' },
      { value: 'teriyaki', label: '🥢 Teriyaki Burger' },
      { value: 'buffalo', label: '🍗 Buffalo Burger' },
      { value: 'veggie-burger', label: '🥬 Veggie Burger' },
      { value: 'black-bean', label: '⚫ Black Bean Burger' },
      { value: 'impossible', label: '🌱 Impossible Burger' },
      { value: 'beyond-meat', label: '🌿 Beyond Meat Burger' },
      { value: 'turkey-burger', label: '🦃 Turkey Burger' },
      { value: 'chicken-burger', label: '🍗 Chicken Burger' },
      { value: 'salmon-burger', label: '🐟 Salmon Burger' },
      { value: 'lamb-burger', label: '🐑 Lamb Burger' },
      { value: 'portobello', label: '🍄 Portobello Burger' },
    ],
    entree: [
      { value: 'single', label: '🍔 Single Burger' },
      { value: 'double', label: '🍔 Double Burger' },
      { value: 'triple', label: '🍔 Triple Burger' },
      { value: 'quarter-pound', label: '🍔 Quarter Pound' },
      { value: 'half-pound', label: '🍔 Half Pound' },
      { value: 'full-pound', label: '🍔 Full Pound' },
    ],
    slider: [
      { value: 'cheese-slider', label: '🧀 Cheese Slider' },
      { value: 'bbq-slider', label: '🍕 BBQ Slider' },
      { value: 'chicken-slider', label: '🍗 Chicken Slider' },
      { value: 'veggie-slider', label: '🥬 Veggie Slider' },
    ],
    bundle: [
      { value: 'burger-combo', label: '📦 Burger Combo' },
      { value: 'burger-meal', label: '🍽️ Burger Meal' },
      { value: 'slider-pack', label: '📦 Slider Pack' },
    ],
  },
  salads: {
    salad: [
      { value: 'green', label: '🥬 Green Salad' },
      { value: 'pasta', label: '🍝 Pasta Salad' },
      { value: 'potato', label: '🥔 Potato Salad' },
      { value: 'fruit', label: '🍎 Fruit Salad' },
      { value: 'grain', label: '🌾 Grain Salad' },
      { value: 'caesar', label: '🥬 Caesar Salad' },
      { value: 'greek', label: '🫒 Greek Salad' },
      { value: 'cobb', label: '🥗 Cobb Salad' },
      { value: 'chef', label: '👨‍🍳 Chef Salad' },
      { value: 'taco', label: '🌮 Taco Salad' },
      { value: 'chicken', label: '🍗 Chicken Salad' },
      { value: 'tuna', label: '🐟 Tuna Salad' },
      { value: 'egg', label: '🥚 Egg Salad' },
      { value: 'waldorf', label: '🍎 Waldorf Salad' },
      { value: 'tabbouleh', label: '🌿 Tabbouleh' },
      { value: 'quinoa', label: '🌾 Quinoa Salad' },
      { value: 'lentil', label: '🫘 Lentil Salad' },
      { value: 'beet', label: '🍑 Beet Salad' },
      { value: 'caprese', label: '🍅 Caprese Salad' },
      { value: 'asian', label: '🥢 Asian Salad' },
    ],
    side: [
      { value: 'small', label: '🥗 Small Side Salad' },
      { value: 'large', label: '🍽️ Large Side Salad' },
    ],
    entree: [
      { value: 'chicken', label: '🍗 Chicken Salad Entree' },
      { value: 'seafood', label: '🐟 Seafood Salad Entree' },
      { value: 'vegetarian', label: '🥬 Vegetarian Salad Entree' },
      { value: 'vegan', label: '🌱 Vegan Salad Entree' },
      { value: 'protein', label: '💪 Protein Salad Entree' },
    ],
  },
  // Convenience store categories
  snacks: {
    snack: [
      { value: 'potato-chips', label: '🥔 Potato Chips' },
      { value: 'tortilla-chips', label: '🌮 Tortilla Chips' },
      { value: 'corn-chips', label: '🌽 Corn Chips' },
      { value: 'pita-chips', label: '🫓 Pita Chips' },
      { value: 'kettle-chips', label: '🔥 Kettle Chips' },
      { value: 'baked-chips', label: '🍕 Baked Chips' },
      { value: 'veggie-chips', label: '🥬 Veggie Chips' },
      { value: 'pretzels', label: '🥨 Pretzels' },
      { value: 'popcorn', label: '🍿 Popcorn' },
      { value: 'cheese-puffs', label: '🧀 Cheese Puffs' },
      { value: 'corn-puffs', label: '🌽 Corn Puffs' },
      { value: 'pork-rinds', label: '🥓 Pork Rinds' },
      { value: 'beef-jerky', label: '🥩 Beef Jerky' },
      { value: 'turkey-jerky', label: '🦃 Turkey Jerky' },
      { value: 'salmon-jerky', label: '🐟 Salmon Jerky' },
      { value: 'fruit-leather', label: '🍎 Fruit Leather' },
      { value: 'fruit-chips', label: '🍎 Fruit Chips' },
      { value: 'kale-chips', label: '🥬 Kale Chips' },
      { value: 'banana-chips', label: '🍌 Banana Chips' },
      { value: 'plantain-chips', label: '🍌 Plantain Chips' },
    ],
    bundle: [
      { value: 'snack-pack', label: '📦 Snack Pack' },
      { value: 'variety-pack', label: '🎯 Variety Pack' },
      { value: 'party-mix', label: '🎉 Party Mix' },
      { value: 'trail-mix', label: '🥾 Trail Mix' },
      { value: 'gift-basket', label: '🎁 Gift Basket' },
    ],
    single: [
      { value: 'single-serve', label: '🍿 Single Serve' },
      { value: 'personal-size', label: '👤 Personal Size' },
      { value: 'grab-bag', label: '🛍️ Grab Bag' },
    ],
    family: [
      { value: 'family-size', label: '👨‍👩‍👧‍👦 Family Size' },
      { value: 'value-pack', label: '💰 Value Pack' },
      { value: 'bulk-pack', label: '📦 Bulk Pack' },
    ],
  },
  'candy-chocolate': {
    candy: [
      { value: 'gummy-bears', label: '🐻 Gummy Bears' },
      { value: 'gummy-worms', label: '🪱 Gummy Worms' },
      { value: 'sour-patch', label: '🍋 Sour Patch' },
      { value: 'swedish-fish', label: '🐟 Swedish Fish' },
      { value: 'jelly-beans', label: '🫘 Jelly Beans' },
      { value: 'candy-corn', label: '🌽 Candy Corn' },
      { value: 'candy-canes', label: '🍬 Candy Canes' },
      { value: 'lollipops', label: '🍭 Lollipops' },
      { value: 'hard-candy', label: '🍬 Hard Candy' },
      { value: 'chewy-candy', label: '🍫 Chewy Candy' },
      { value: 'taffy', label: '🍬 Taffy' },
      { value: 'caramel', label: '🍮 Caramel' },
      { value: 'toffee', label: '🍮 Toffee' },
      { value: 'butterscotch', label: '🟡 Butterscotch' },
      { value: 'licorice', label: '⚫ Licorice' },
      { value: 'marshmallows', label: '🦆 Marshmallows' },
      { value: 'cotton-candy', label: '🍬 Cotton Candy' },
      { value: 'rock-candy', label: '💎 Rock Candy' },
      { value: 'fruit-snacks', label: '🍎 Fruit Snacks' },
    ],
    chocolate: [
      { value: 'milk-chocolate', label: '🍫 Milk Chocolate' },
      { value: 'dark-chocolate', label: '🍫 Dark Chocolate' },
      { value: 'white-chocolate', label: '⚪ White Chocolate' },
      { value: 'semi-sweet', label: '🍫 Semi-Sweet' },
      { value: 'bittersweet', label: '🍫 Bittersweet' },
      { value: 'chocolate-bar', label: '🍫 Chocolate Bar' },
      { value: 'truffles', label: '🍄 Truffles' },
      { value: 'bonbons', label: '🍬 Bonbons' },
      { value: 'chocolate-covered', label: '🍫 Chocolate Covered' },
      { value: 'chocolate-mints', label: '🍫 Chocolate Mints' },
      { value: 'chocolate-caramel', label: '🍫 Chocolate Caramel' },
      { value: 'chocolate-nuts', label: '🍫 Chocolate Nuts' },
      { value: 'chocolate-fruit', label: '🍫 Chocolate Fruit' },
      { value: 'chocolate-coconut', label: '🍫 Chocolate Coconut' },
      { value: 'chocolate-peanut-butter', label: '🍫 Chocolate Peanut Butter' },
      { value: 'chocolate-mint', label: '🍫 Chocolate Mint' },
      { value: 'chocolate-orange', label: '🍊 Chocolate Orange' },
      { value: 'chocolate-raspberry', label: '🍫 Chocolate Raspberry' },
      { value: 'chocolate-almond', label: '🍫 Chocolate Almond' },
      { value: 'chocolate-hazelnut', label: '🍫 Chocolate Hazelnut' },
    ],
    bundle: [
      { value: 'candy-pack', label: '📦 Candy Pack' },
      { value: 'chocolate-box', label: '🎁 Chocolate Box' },
      { value: 'assorted-candy', label: '🎯 Assorted Candy' },
      { value: 'holiday-mix', label: '🎄 Holiday Mix' },
    ],
    premium: [
      { value: 'gourmet-chocolate', label: '💎 Gourmet Chocolate' },
      { value: 'artisan-candy', label: '🎨 Artisan Candy' },
      { value: 'imported-chocolate', label: '🌍 Imported Chocolate' },
      { value: 'belgian-chocolate', label: '🇧🇪 Belgian Chocolate' },
    ],
  },
  'chips-crackers': {
    chips: [
      { value: 'regular-chips', label: '🥨 Regular Chips' },
      { value: 'barbecue-chips', label: '🍖 Barbecue Chips' },
      { value: 'sour-cream-chips', label: '🥛 Sour Cream Chips' },
      { value: 'salt-vinegar', label: '🧂 Salt & Vinegar' },
      { value: 'ranch-chips', label: '🌿 Ranch Chips' },
      { value: 'cheese-chips', label: '🧀 Cheese Chips' },
      { value: 'spicy-chips', label: '🌶️ Spicy Chips' },
      { value: 'jalepeno-chips', label: '🌶️ Jalapeno Chips' },
      { value: 'buffalo-chips', label: '🍗 Buffalo Chips' },
      { value: 'pizza-chips', label: '🍕 Pizza Chips' },
      { value: 'loaded-chips', label: '🍟 Loaded Chips' },
      { value: 'kettle-cooked', label: '🔥 Kettle Cooked' },
      { value: 'wavy-chips', label: '🌊 Wavy Chips' },
      { value: 'ridged-chips', label: '🏔️ Ridged Chips' },
      { value: 'thin-crisp', label: '🍪 Thin Crisp' },
    ],
    crackers: [
      { value: 'saltine', label: '🧂 Saltine' },
      { value: 'butter-cracker', label: '🧈 Butter Cracker' },
      { value: 'cheese-cracker', label: '🧀 Cheese Cracker' },
      { value: 'wheat-cracker', label: '🌾 Wheat Cracker' },
      { value: 'multi-grain', label: '🌾 Multi-Grain' },
      { value: 'sea-salt', label: '🧂 Sea Salt' },
      { value: 'black-pepper', label: '⚫ Black Pepper' },
      { value: 'garlic-herb', label: '🧄 Garlic Herb' },
      { value: 'rosemary', label: '🌿 Rosemary' },
      { value: 'sesame', label: '🫘 Sesame' },
      { value: 'poppy-seed', label: '🌾 Poppy Seed' },
      { value: 'onion', label: '🧅 Onion' },
      { value: 'ranch', label: '🌿 Ranch' },
      { value: 'pizza', label: '🍕 Pizza' },
      { value: 'ritz', label: '🍪 Ritz' },
      { value: 'graham', label: '🍪 Graham' },
      { value: 'animal', label: '🦁 Animal' },
      { value: 'goldfish', label: '🐠 Goldfish' },
      { value: 'pretzel-cracker', label: '🥨 Pretzel Cracker' },
      { value: 'water-cracker', label: '💧 Water Cracker' },
    ],
    bundle: [
      { value: 'variety-pack', label: '🎯 Variety Pack' },
      { value: 'family-size', label: '👨‍👩‍👧‍👦 Family Size' },
      { value: 'snack-mix', label: '🥨 Snack Mix' },
      { value: 'party-pack', label: '🎉 Party Pack' },
    ],
    single: [
      { value: 'single-bag', label: '🥨 Single Bag' },
      { value: 'individual-pack', label: '👤 Individual Pack' },
      { value: 'travel-size', label: '✈️ Travel Size' },
    ],
  },
  soups: {
    soup: [
      { value: 'broth', label: '🍲 Broth Soup' },
      { value: 'cream', label: '🥛 Cream Soup' },
      { value: 'chunky', label: '🥄 Chunky Soup' },
      { value: 'pureed', label: '🥄 Pureed Soup' },
    ],
    side: [
      { value: 'cup', label: '☕ Cup Size' },
      { value: 'bowl', label: '🥣 Bowl Size' },
    ],
    entree: [
      { value: 'hearty', label: '🍲 Hearty Soup Entree' },
      { value: 'stew', label: '🍛 Stew Entree' },
    ],
  },
  sides: {
    side: [
      { value: 'vegetable', label: '🥬 Vegetable Side' },
      { value: 'starch', label: '🍟 Starch Side' },
      { value: 'salad', label: '🥗 Salad Side' },
      { value: 'bread', label: '🍞 Bread Side' },
    ],
    appetizer: [
      { value: 'small', label: '🥗 Small Appetizer' },
      { value: 'shareable', label: '👥 Shareable Appetizer' },
    ],
  },
  desserts: {
    dessert: [
      { value: 'cake', label: '🎂 Cake' },
      { value: 'pie', label: '🥧 Pie' },
      { value: 'ice-cream', label: '🍦 Ice Cream' },
      { value: 'pastry', label: '🥐 Pastry' },
      { value: 'fruit', label: '🍎 Fruit Dessert' },
    ],
    bundle: [
      { value: 'dessert-platter', label: '🍽️ Dessert Platter' },
      { value: 'sampler', label: '🎯 Dessert Sampler' },
      { value: 'combo', label: '📦 Dessert Combo' },
    ],
  },
  beverages: {
    drink: [
      { value: 'soft-drink', label: '🥤 Soft Drink' },
      { value: 'juice', label: '🧃 Juice' },
      { value: 'coffee', label: '☕ Coffee' },
      { value: 'tea', label: '🍵 Tea' },
      { value: 'smoothie', label: '🥤 Smoothie' },
    ],
    side: [
      { value: 'small', label: '🥤 Small Drink' },
      { value: 'medium', label: '🥤 Medium Drink' },
      { value: 'large', label: '🥤 Large Drink' },
    ],
  },
  breakfast: {
    breakfast: [
      { value: 'eggs', label: '🥚 Eggs' },
      { value: 'pancakes', label: '🥞 Pancakes' },
      { value: 'waffles', label: '🧇 Waffles' },
      { value: 'cereal', label: '🥣 Cereal' },
      { value: 'oatmeal', label: '🥄 Oatmeal' },
    ],
    entree: [
      { value: 'full-breakfast', label: '🍽️ Full Breakfast' },
      { value: 'light-breakfast', label: '🥐 Light Breakfast' },
    ],
    bundle: [
      { value: 'breakfast-combo', label: '🍳 Breakfast Combo' },
      { value: 'family-breakfast', label: '👨‍👩‍👧‍👦 Family Breakfast' },
    ],
  },
  specials: {
    entree: [
      { value: 'chef-special', label: '👨‍🍳 Chef Special' },
      { value: 'daily-special', label: '📅 Daily Special' },
      { value: 'seasonal', label: '🍂 Seasonal Special' },
    ],
    bundle: [
      { value: 'special-combo', label: '📦 Special Combo' },
      { value: 'limited-time', label: '⏰ Limited Time Bundle' },
    ],
    appetizer: [
      { value: 'special-appetizer', label: '🌟 Special Appetizer' },
      { value: 'signature', label: '✍️ Signature Appetizer' },
    ],
    dessert: [
      { value: 'special-dessert', label: '🍰 Special Dessert' },
      { value: 'chef-dessert', label: '👨‍🍳 Chef Dessert' },
    ],
  },
}

export const DEFAULT_SUB_TYPES = [
  { value: 'regular', label: '📝 Regular' },
  { value: 'special', label: '⭐ Special' },
  { value: 'premium', label: '💎 Premium' },
]

// ============================================
// Utility Functions
// ============================================

export function getCategoriesForStoreType(storeType: string): Array<{value: string, label: string}> {
  return STORE_TYPE_CATEGORIES[storeType] || CATEGORIES
}

export function getAvailableItemTypes(category: string): Array<{value: string, label: string}> {
  return ITEM_TYPES[category] || DEFAULT_ITEM_TYPES
}

export function isTypeValidForCategory(type: string, category: string): boolean {
  const availableTypes = getAvailableItemTypes(category)
  return availableTypes.some(itemType => itemType.value === type)
}

export function getAvailableSubTypes(category: string, type: string): Array<{value: string, label: string}> {
  if (!category || !type) return DEFAULT_SUB_TYPES
  return SUB_TYPES[category]?.[type] || DEFAULT_SUB_TYPES
}

export function isSubTypeValidForCategoryType(subtype: string, category: string, type: string): boolean {
  const availableSubTypes = getAvailableSubTypes(category, type)
  return availableSubTypes.some(subType => subType.value === subtype)
}
