/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checkout/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create checkout session */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete checkout */
        post: operations["completeCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout/status/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get checkout status */
        get: operations["getCheckoutStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
            message: string;
            requestId?: string;
            /** @description Validation details are included outside production only. */
            details?: unknown;
        } & Record<string, unknown>;
        CheckoutItem: {
            /** Format: uuid */
            itemId: string;
            quantity: number;
            specialInstructions?: string;
        };
        /** @enum {string} */
        DeliveryType: "PICKUP" | "DELIVERY";
        /** @enum {string} */
        DeliveryMode: "PICKUP" | "STORE_MANAGED_DELIVERY" | "PLATFORM_DRIVER" | "THIRD_PARTY_PROVIDER";
        DeliveryAddress: {
            street: string;
            city: string;
            state: string;
            zipCode: string;
            instructions?: string;
        };
        /** @enum {string} */
        PaymentMethodType: "CREDIT_CARD" | "DEBIT_CARD" | "DIGITAL_WALLET";
        PaymentMethod: {
            type: components["schemas"]["PaymentMethodType"];
            token: string;
        };
        CreateCheckoutSessionRequest: {
            items: components["schemas"]["CheckoutItem"][];
            deliveryType: components["schemas"]["DeliveryType"];
            deliveryMode: components["schemas"]["DeliveryMode"];
            deliveryAddress?: components["schemas"]["DeliveryAddress"];
            paymentMethod: components["schemas"]["PaymentMethod"];
            tipAmount?: number;
            promoCode?: string;
        } & unknown;
        CreateCheckoutSessionResponse: {
            /** Format: uuid */
            sessionId: string;
            total: number;
            /** Format: date-time */
            estimatedDelivery: string;
        };
        CompleteCheckoutRequest: {
            /** Format: uuid */
            sessionId: string;
            paymentMethod: components["schemas"]["PaymentMethod"];
            tipAmount?: number;
            promoCode?: string;
            /** CARD (Stripe) vs COD when enabled server-side */
            paymentRail?: "CARD" | "COD";
            /** Referral code captured client-side (/r/:slugOrCode); snapped onto the user once when currently unattributed. */
            affiliateReferralCode?: string;
        };
        CompleteCheckoutResponse: {
            order: components["schemas"]["CheckoutOrderSummary"];
            /** Stripe PI id, or null for COD */
            paymentId: string | null;
            /** True when an affiliate referral attribution was applied to this order. */
            referralCodeApplied?: boolean;
        };
        CheckoutOrderSummary: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["OrderStatus"];
            total: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        CheckoutStatus: "pending" | "awaiting_payment" | "completed";
        /** @enum {string} */
        CartStatus: "ACTIVE" | "SUBMITTED" | "ABANDONED";
        /** @enum {string} */
        OrderStatus: "PENDING_PAYMENT" | "PLACED" | "ACCEPTED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "DELIVERED" | "COMPLETED" | "CANCELED";
        /** @enum {string} */
        PaymentStatus: "UNPAID" | "PAID" | "REFUNDED";
        CheckoutStatusOrder: {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["OrderStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            deliveryType: components["schemas"]["DeliveryType"];
            subtotal: number;
            fees: number;
            tax: number;
            tip: number;
            total: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CheckoutStatusResponse: {
            /** Format: uuid */
            sessionId: string;
            cartStatus: components["schemas"]["CartStatus"];
            status: components["schemas"]["CheckoutStatus"];
            order: components["schemas"]["CheckoutStatusOrder"] | null;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Bad request or validation failure. */
        BadRequest: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated user cannot access this checkout session. */
        Forbidden: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Checkout session was not found. */
        NotFound: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Checkout session already has an order. */
        Conflict: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Checkout session has expired. */
        Gone: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error. */
        InternalServerError: {
            headers: Record<string, unknown>;
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Optional idempotency key for non-GET checkout requests. If supplied, it must match ^[a-zA-Z0-9_-]{8,64}$ and successful 2xx responses are cached for 24 hours. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /** @description Present when the request omitted X-Idempotency-Key. */
        GeneratedIdempotencyKey: string;
        /** @description Present with value "true" when the response was served from the idempotency cache. */
        IdempotencyResponse: "true";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createCheckoutSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional idempotency key for non-GET checkout requests. If supplied, it must match ^[a-zA-Z0-9_-]{8,64}$ and successful 2xx responses are cached for 24 hours. */
                "X-Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Checkout session created. */
            200: {
                headers: {
                    "X-Idempotency-Key": components["headers"]["GeneratedIdempotencyKey"];
                    "X-Idempotency-Response": components["headers"]["IdempotencyResponse"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCheckoutSessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeCheckout: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional idempotency key for non-GET checkout requests. If supplied, it must match ^[a-zA-Z0-9_-]{8,64}$ and successful 2xx responses are cached for 24 hours. */
                "X-Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteCheckoutRequest"];
            };
        };
        responses: {
            /** @description Order record created and payment processing requested. */
            200: {
                headers: {
                    "X-Idempotency-Key": components["headers"]["GeneratedIdempotencyKey"];
                    "X-Idempotency-Response": components["headers"]["IdempotencyResponse"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompleteCheckoutResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["Gone"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCheckoutStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Checkout session status. */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["CheckoutStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
