/**
 * Centralized Resource Configuration
 * 
 * ⚠️  AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated from: Prisma schemas (100% schema-driven, parallel processing)
 * 
 * This configuration is derived from our Prisma schemas to ensure
 * perfect alignment between backend types and frontend API contracts.
 */

export interface ResourceConfig {
  // Core identification
  name: string
  type: string
  createType?: string
  
  // SDK Configuration
  apiClass: string
  sdkType: string
  sdkListMethod: string
  sdkGetMethod: string
  sdkCreateMethod?: string
  sdkUpdateMethod?: string
  sdkDeleteMethod?: string
  
  // Explicit request parameter names
  sdkCreateRequestParam?: string
  sdkUpdateRequestParam?: string
  
  // Method parameters
  listParams?: string
  
  // Feature flags
  hasCreate?: boolean
  hasUpdate?: boolean
  hasDelete?: boolean
  
  // Custom implementations
  updateCustom?: string
  
  // React Query configuration
  invalidates?: string[]
  methods?: string[]
  hooks?: {
    useList?: string
    useOne?: string
    useCreate?: string
    useUpdate?: string
    useDelete?: string
  }
  
  // Type extensions
  extensions?: Record<string, string>
  computed?: string
}

/**
 * Master resource configuration
 * Generated from Prisma schemas to ensure alignment
 */
export const RESOURCE_CONFIGS: ResourceConfig[] = [
  {
    name: 'users',
    type: 'User',
    createType: 'CreateUserInput',
    apiClass: 'UsersApi',
    sdkType: 'ListUsers200ResponseDataInner',
    sdkListMethod: 'listUsers',
    sdkGetMethod: 'getUserById',
    sdkCreateMethod: 'createUser',
    sdkUpdateMethod: 'updateUser',
    sdkDeleteMethod: 'deleteUser',
    sdkCreateRequestParam: 'createUserRequest',
    sdkUpdateRequestParam: 'updateUserRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useUsers',
      useOne: 'useUser',
      useCreate: 'useCreateUser',
      useUpdate: 'useUpdateUser',
      useDelete: 'useDeleteUser'
    },
  },
  {
    name: 'stores',
    type: 'Store',
    createType: 'CreateStoreInput',
    apiClass: 'StoresApi',
    sdkType: 'ListStores200ResponseDataInner',
    sdkListMethod: 'listStores',
    sdkGetMethod: 'getStoreById',
    sdkCreateMethod: 'createStore',
    sdkUpdateMethod: 'updateStore',
    sdkDeleteMethod: 'deleteStore',
    sdkCreateRequestParam: 'createStoreRequest',
    sdkUpdateRequestParam: 'updateStoreRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useStores',
      useOne: 'useStore',
      useCreate: 'useCreateStore',
      useUpdate: 'useUpdateStore',
      useDelete: 'useDeleteStore'
    },
    extensions: {
      deliveryFee: 'number',
      minOrder: 'number',
      distance: 'number | undefined',
    },
    computed: ``,
  },
  {
    name: 'geocodingcaches',
    type: 'GeocodingCache',
    createType: 'CreateGeocodingCacheInput',
    apiClass: 'GeocodingCachesApi',
    sdkType: 'ListGeocodingCaches200ResponseDataInner',
    sdkListMethod: 'listGeocodingCaches',
    sdkGetMethod: 'getGeocodingCacheById',
    sdkCreateMethod: 'createGeocodingCache',
    sdkUpdateMethod: 'updateGeocodingCache',
    sdkDeleteMethod: 'deleteGeocodingCache',
    sdkCreateRequestParam: 'createGeocodingCacheRequest',
    sdkUpdateRequestParam: 'updateGeocodingCacheRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useGeocodingCaches',
      useOne: 'useGeocodingCache',
      useCreate: 'useCreateGeocodingCache',
      useUpdate: 'useUpdateGeocodingCache',
      useDelete: 'useDeleteGeocodingCache'
    },
  },
  {
    name: 'items',
    type: 'Item',
    createType: 'CreateItemInput',
    apiClass: 'ItemsApi',
    sdkType: 'ListItems200ResponseDataInner',
    sdkListMethod: 'listItems',
    sdkGetMethod: 'getItemById',
    sdkCreateMethod: 'createItem',
    sdkUpdateMethod: 'updateItem',
    sdkDeleteMethod: 'deleteItem',
    sdkCreateRequestParam: 'createItemRequest',
    sdkUpdateRequestParam: 'updateItemRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useItems',
      useOne: 'useItem',
      useCreate: 'useCreateItem',
      useUpdate: 'useUpdateItem',
      useDelete: 'useDeleteItem'
    },
  },
  {
    name: 'mediaassets',
    type: 'MediaAsset',
    createType: 'CreateMediaAssetInput',
    apiClass: 'MediaAssetsApi',
    sdkType: 'ListMediaAssets200ResponseDataInner',
    sdkListMethod: 'listMediaAssets',
    sdkGetMethod: 'getMediaAssetById',
    sdkCreateMethod: 'createMediaAsset',
    sdkUpdateMethod: 'updateMediaAsset',
    sdkDeleteMethod: 'deleteMediaAsset',
    sdkCreateRequestParam: 'createMediaAssetRequest',
    sdkUpdateRequestParam: 'updateMediaAssetRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useMediaAssets',
      useOne: 'useMediaAsset',
      useCreate: 'useCreateMediaAsset',
      useUpdate: 'useUpdateMediaAsset',
      useDelete: 'useDeleteMediaAsset'
    },
  },
  {
    name: 'carts',
    type: 'Cart',
    createType: 'CreateCartInput',
    apiClass: 'CartsApi',
    sdkType: 'ListCarts200ResponseDataInner',
    sdkListMethod: 'listCarts',
    sdkGetMethod: 'getCartById',
    sdkCreateMethod: 'createCart',
    sdkUpdateMethod: 'updateCart',
    sdkDeleteMethod: 'deleteCart',
    sdkCreateRequestParam: 'createCartRequest',
    sdkUpdateRequestParam: 'updateCartRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useCarts',
      useOne: 'useCart',
      useCreate: 'useCreateCart',
      useUpdate: 'useUpdateCart',
      useDelete: 'useDeleteCart'
    },
  },
  {
    name: 'cartitems',
    type: 'CartItem',
    createType: 'CreateCartItemInput',
    apiClass: 'CartItemsApi',
    sdkType: 'ListCartItems200ResponseDataInner',
    sdkListMethod: 'listCartItems',
    sdkGetMethod: 'getCartItemById',
    sdkCreateMethod: 'createCartItem',
    sdkUpdateMethod: 'updateCartItem',
    sdkDeleteMethod: 'deleteCartItem',
    sdkCreateRequestParam: 'createCartItemRequest',
    sdkUpdateRequestParam: 'updateCartItemRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useCartItems',
      useOne: 'useCartItem',
      useCreate: 'useCreateCartItem',
      useUpdate: 'useUpdateCartItem',
      useDelete: 'useDeleteCartItem'
    },
  },
  {
    name: 'orders',
    type: 'Order',
    createType: 'CreateOrderInput',
    apiClass: 'OrdersApi',
    sdkType: 'ListOrders200ResponseDataInner',
    sdkListMethod: 'listOrders',
    sdkGetMethod: 'getOrderById',
    sdkCreateMethod: 'createOrder',
    sdkUpdateMethod: 'updateOrder',
    sdkDeleteMethod: 'deleteOrder',
    sdkCreateRequestParam: 'createOrderRequest',
    sdkUpdateRequestParam: 'updateOrderRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useOrders',
      useOne: 'useOrder',
      useCreate: 'useCreateOrder',
      useUpdate: 'useUpdateOrder',
      useDelete: 'useDeleteOrder'
    },
    extensions: {
      stripePaymentIntentId: 'string | null',
      stripeChargeId: 'string | null',
      store: '{ id: string; name: string } | undefined',
      items: 'OrderItem[] | undefined',
      addressSnapshot: 'AddressSnapshot | undefined',
    },
    computed: ``,
  },
  {
    name: 'orderitems',
    type: 'OrderItem',
    createType: 'CreateOrderItemInput',
    apiClass: 'OrderItemsApi',
    sdkType: 'ListOrderItems200ResponseDataInner',
    sdkListMethod: 'listOrderItems',
    sdkGetMethod: 'getOrderItemById',
    sdkCreateMethod: 'createOrderItem',
    sdkUpdateMethod: 'updateOrderItem',
    sdkDeleteMethod: 'deleteOrderItem',
    sdkCreateRequestParam: 'createOrderItemRequest',
    sdkUpdateRequestParam: 'updateOrderItemRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useOrderItems',
      useOne: 'useOrderItem',
      useCreate: 'useCreateOrderItem',
      useUpdate: 'useUpdateOrderItem',
      useDelete: 'useDeleteOrderItem'
    },
  },
  {
    name: 'orderevents',
    type: 'OrderEvent',
    createType: 'CreateOrderEventInput',
    apiClass: 'OrderEventsApi',
    sdkType: 'ListOrderEvents200ResponseDataInner',
    sdkListMethod: 'listOrderEvents',
    sdkGetMethod: 'getOrderEventById',
    sdkCreateMethod: 'createOrderEvent',
    sdkUpdateMethod: 'updateOrderEvent',
    sdkDeleteMethod: 'deleteOrderEvent',
    sdkCreateRequestParam: 'createOrderEventRequest',
    sdkUpdateRequestParam: 'updateOrderEventRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useOrderEvents',
      useOne: 'useOrderEvent',
      useCreate: 'useCreateOrderEvent',
      useUpdate: 'useUpdateOrderEvent',
      useDelete: 'useDeleteOrderEvent'
    },
  },
  {
    name: 'tips',
    type: 'Tip',
    createType: 'CreateTipInput',
    apiClass: 'TipsApi',
    sdkType: 'ListTips200ResponseDataInner',
    sdkListMethod: 'listTips',
    sdkGetMethod: 'getTipById',
    sdkCreateMethod: 'createTip',
    sdkUpdateMethod: 'updateTip',
    sdkDeleteMethod: 'deleteTip',
    sdkCreateRequestParam: 'createTipRequest',
    sdkUpdateRequestParam: 'updateTipRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useTips',
      useOne: 'useTip',
      useCreate: 'useCreateTip',
      useUpdate: 'useUpdateTip',
      useDelete: 'useDeleteTip'
    },
  },
  {
    name: 'addresss',
    type: 'Address',
    createType: 'CreateAddressInput',
    apiClass: 'AddresssApi',
    sdkType: 'ListAddresss200ResponseDataInner',
    sdkListMethod: 'listAddresss',
    sdkGetMethod: 'getAddressById',
    sdkCreateMethod: 'createAddress',
    sdkUpdateMethod: 'updateAddress',
    sdkDeleteMethod: 'deleteAddress',
    sdkCreateRequestParam: 'createAddressRequest',
    sdkUpdateRequestParam: 'updateAddressRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useAddresss',
      useOne: 'useAddress',
      useCreate: 'useCreateAddress',
      useUpdate: 'useUpdateAddress',
      useDelete: 'useDeleteAddress'
    },
  },
  {
    name: 'systemsettings',
    type: 'SystemSetting',
    createType: 'CreateSystemSettingInput',
    apiClass: 'SystemSettingsApi',
    sdkType: 'ListSystemSettings200ResponseDataInner',
    sdkListMethod: 'listSystemSettings',
    sdkGetMethod: 'getSystemSettingById',
    sdkCreateMethod: 'createSystemSetting',
    sdkUpdateMethod: 'updateSystemSetting',
    sdkDeleteMethod: 'deleteSystemSetting',
    sdkCreateRequestParam: 'createSystemSettingRequest',
    sdkUpdateRequestParam: 'updateSystemSettingRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useSystemSettings',
      useOne: 'useSystemSetting',
      useCreate: 'useCreateSystemSetting',
      useUpdate: 'useUpdateSystemSetting',
      useDelete: 'useDeleteSystemSetting'
    },
  },
  {
    name: 'paymentwebhooks',
    type: 'PaymentWebhook',
    createType: 'CreatePaymentWebhookInput',
    apiClass: 'PaymentWebhooksApi',
    sdkType: 'ListPaymentWebhooks200ResponseDataInner',
    sdkListMethod: 'listPaymentWebhooks',
    sdkGetMethod: 'getPaymentWebhookById',
    sdkCreateMethod: 'createPaymentWebhook',
    sdkUpdateMethod: 'updatePaymentWebhook',
    sdkDeleteMethod: 'deletePaymentWebhook',
    sdkCreateRequestParam: 'createPaymentWebhookRequest',
    sdkUpdateRequestParam: 'updatePaymentWebhookRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePaymentWebhooks',
      useOne: 'usePaymentWebhook',
      useCreate: 'useCreatePaymentWebhook',
      useUpdate: 'useUpdatePaymentWebhook',
      useDelete: 'useDeletePaymentWebhook'
    },
  },
  {
    name: 'paymentmethods',
    type: 'PaymentMethod',
    createType: 'CreatePaymentMethodInput',
    apiClass: 'PaymentMethodsApi',
    sdkType: 'ListPaymentMethods200ResponseDataInner',
    sdkListMethod: 'listPaymentMethods',
    sdkGetMethod: 'getPaymentMethodById',
    sdkCreateMethod: 'createPaymentMethod',
    sdkUpdateMethod: 'updatePaymentMethod',
    sdkDeleteMethod: 'deletePaymentMethod',
    sdkCreateRequestParam: 'createPaymentMethodRequest',
    sdkUpdateRequestParam: 'updatePaymentMethodRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePaymentMethods',
      useOne: 'usePaymentMethod',
      useCreate: 'useCreatePaymentMethod',
      useUpdate: 'useUpdatePaymentMethod',
      useDelete: 'useDeletePaymentMethod'
    },
  },
  {
    name: 'promotions',
    type: 'Promotion',
    createType: 'CreatePromotionInput',
    apiClass: 'PromotionsApi',
    sdkType: 'ListPromotions200ResponseDataInner',
    sdkListMethod: 'listPromotions',
    sdkGetMethod: 'getPromotionById',
    sdkCreateMethod: 'createPromotion',
    sdkUpdateMethod: 'updatePromotion',
    sdkDeleteMethod: 'deletePromotion',
    sdkCreateRequestParam: 'createPromotionRequest',
    sdkUpdateRequestParam: 'updatePromotionRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePromotions',
      useOne: 'usePromotion',
      useCreate: 'useCreatePromotion',
      useUpdate: 'useUpdatePromotion',
      useDelete: 'useDeletePromotion'
    },
  },
  {
    name: 'promotionredemptions',
    type: 'PromotionRedemption',
    createType: 'CreatePromotionRedemptionInput',
    apiClass: 'PromotionRedemptionsApi',
    sdkType: 'ListPromotionRedemptions200ResponseDataInner',
    sdkListMethod: 'listPromotionRedemptions',
    sdkGetMethod: 'getPromotionRedemptionById',
    sdkCreateMethod: 'createPromotionRedemption',
    sdkUpdateMethod: 'updatePromotionRedemption',
    sdkDeleteMethod: 'deletePromotionRedemption',
    sdkCreateRequestParam: 'createPromotionRedemptionRequest',
    sdkUpdateRequestParam: 'updatePromotionRedemptionRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePromotionRedemptions',
      useOne: 'usePromotionRedemption',
      useCreate: 'useCreatePromotionRedemption',
      useUpdate: 'useUpdatePromotionRedemption',
      useDelete: 'useDeletePromotionRedemption'
    },
  },
  {
    name: 'posts',
    type: 'Post',
    createType: 'CreatePostInput',
    apiClass: 'PostsApi',
    sdkType: 'ListPosts200ResponseDataInner',
    sdkListMethod: 'listPosts',
    sdkGetMethod: 'getPostById',
    sdkCreateMethod: 'createPost',
    sdkUpdateMethod: 'updatePost',
    sdkDeleteMethod: 'deletePost',
    sdkCreateRequestParam: 'createPostRequest',
    sdkUpdateRequestParam: 'updatePostRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePosts',
      useOne: 'usePost',
      useCreate: 'useCreatePost',
      useUpdate: 'useUpdatePost',
      useDelete: 'useDeletePost'
    },
  },
  {
    name: 'postlikes',
    type: 'PostLike',
    createType: 'CreatePostLikeInput',
    apiClass: 'PostLikesApi',
    sdkType: 'ListPostLikes200ResponseDataInner',
    sdkListMethod: 'listPostLikes',
    sdkGetMethod: 'getPostLikeById',
    sdkCreateMethod: 'createPostLike',
    sdkUpdateMethod: 'updatePostLike',
    sdkDeleteMethod: 'deletePostLike',
    sdkCreateRequestParam: 'createPostLikeRequest',
    sdkUpdateRequestParam: 'updatePostLikeRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'usePostLikes',
      useOne: 'usePostLike',
      useCreate: 'useCreatePostLike',
      useUpdate: 'useUpdatePostLike',
      useDelete: 'useDeletePostLike'
    },
  },
  {
    name: 'comments',
    type: 'Comment',
    createType: 'CreateCommentInput',
    apiClass: 'CommentsApi',
    sdkType: 'ListComments200ResponseDataInner',
    sdkListMethod: 'listComments',
    sdkGetMethod: 'getCommentById',
    sdkCreateMethod: 'createComment',
    sdkUpdateMethod: 'updateComment',
    sdkDeleteMethod: 'deleteComment',
    sdkCreateRequestParam: 'createCommentRequest',
    sdkUpdateRequestParam: 'updateCommentRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useComments',
      useOne: 'useComment',
      useCreate: 'useCreateComment',
      useUpdate: 'useUpdateComment',
      useDelete: 'useDeleteComment'
    },
  },
  {
    name: 'affiliates',
    type: 'Affiliate',
    createType: 'CreateAffiliateInput',
    apiClass: 'AffiliatesApi',
    sdkType: 'ListAffiliates200ResponseDataInner',
    sdkListMethod: 'listAffiliates',
    sdkGetMethod: 'getAffiliateById',
    sdkCreateMethod: 'createAffiliate',
    sdkUpdateMethod: 'updateAffiliate',
    sdkDeleteMethod: 'deleteAffiliate',
    sdkCreateRequestParam: 'createAffiliateRequest',
    sdkUpdateRequestParam: 'updateAffiliateRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useAffiliates',
      useOne: 'useAffiliate',
      useCreate: 'useCreateAffiliate',
      useUpdate: 'useUpdateAffiliate',
      useDelete: 'useDeleteAffiliate'
    },
  },
  {
    name: 'commissions',
    type: 'Commission',
    createType: 'CreateCommissionInput',
    apiClass: 'CommissionsApi',
    sdkType: 'ListCommissions200ResponseDataInner',
    sdkListMethod: 'listCommissions',
    sdkGetMethod: 'getCommissionById',
    sdkCreateMethod: 'createCommission',
    sdkUpdateMethod: 'updateCommission',
    sdkDeleteMethod: 'deleteCommission',
    sdkCreateRequestParam: 'createCommissionRequest',
    sdkUpdateRequestParam: 'updateCommissionRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useCommissions',
      useOne: 'useCommission',
      useCreate: 'useCreateCommission',
      useUpdate: 'useUpdateCommission',
      useDelete: 'useDeleteCommission'
    },
  },
  {
    name: 'affiliatepayouts',
    type: 'AffiliatePayout',
    createType: 'CreateAffiliatePayoutInput',
    apiClass: 'AffiliatePayoutsApi',
    sdkType: 'ListAffiliatePayouts200ResponseDataInner',
    sdkListMethod: 'listAffiliatePayouts',
    sdkGetMethod: 'getAffiliatePayoutById',
    sdkCreateMethod: 'createAffiliatePayout',
    sdkUpdateMethod: 'updateAffiliatePayout',
    sdkDeleteMethod: 'deleteAffiliatePayout',
    sdkCreateRequestParam: 'createAffiliatePayoutRequest',
    sdkUpdateRequestParam: 'updateAffiliatePayoutRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useAffiliatePayouts',
      useOne: 'useAffiliatePayout',
      useCreate: 'useCreateAffiliatePayout',
      useUpdate: 'useUpdateAffiliatePayout',
      useDelete: 'useDeleteAffiliatePayout'
    },
  },
  {
    name: 'deliveryzones',
    type: 'DeliveryZone',
    createType: 'CreateDeliveryZoneInput',
    apiClass: 'DeliveryZonesApi',
    sdkType: 'ListDeliveryZones200ResponseDataInner',
    sdkListMethod: 'listDeliveryZones',
    sdkGetMethod: 'getDeliveryZoneById',
    sdkCreateMethod: 'createDeliveryZone',
    sdkUpdateMethod: 'updateDeliveryZone',
    sdkDeleteMethod: 'deleteDeliveryZone',
    sdkCreateRequestParam: 'createDeliveryZoneRequest',
    sdkUpdateRequestParam: 'updateDeliveryZoneRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useDeliveryZones',
      useOne: 'useDeliveryZone',
      useCreate: 'useCreateDeliveryZone',
      useUpdate: 'useUpdateDeliveryZone',
      useDelete: 'useDeleteDeliveryZone'
    },
  },
  {
    name: 'vendorverifications',
    type: 'VendorVerification',
    createType: 'CreateVendorVerificationInput',
    apiClass: 'VendorVerificationsApi',
    sdkType: 'ListVendorVerifications200ResponseDataInner',
    sdkListMethod: 'listVendorVerifications',
    sdkGetMethod: 'getVendorVerificationById',
    sdkCreateMethod: 'createVendorVerification',
    sdkUpdateMethod: 'updateVendorVerification',
    sdkDeleteMethod: 'deleteVendorVerification',
    sdkCreateRequestParam: 'createVendorVerificationRequest',
    sdkUpdateRequestParam: 'updateVendorVerificationRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useVendorVerifications',
      useOne: 'useVendorVerification',
      useCreate: 'useCreateVendorVerification',
      useUpdate: 'useUpdateVendorVerification',
      useDelete: 'useDeleteVendorVerification'
    },
  },
  {
    name: 'teammembers',
    type: 'TeamMember',
    createType: 'CreateTeamMemberInput',
    apiClass: 'TeamMembersApi',
    sdkType: 'ListTeamMembers200ResponseDataInner',
    sdkListMethod: 'listTeamMembers',
    sdkGetMethod: 'getTeamMemberById',
    sdkCreateMethod: 'createTeamMember',
    sdkUpdateMethod: 'updateTeamMember',
    sdkDeleteMethod: 'deleteTeamMember',
    sdkCreateRequestParam: 'createTeamMemberRequest',
    sdkUpdateRequestParam: 'updateTeamMemberRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useTeamMembers',
      useOne: 'useTeamMember',
      useCreate: 'useCreateTeamMember',
      useUpdate: 'useUpdateTeamMember',
      useDelete: 'useDeleteTeamMember'
    },
  },
  {
    name: 'invitations',
    type: 'Invitation',
    createType: 'CreateInvitationInput',
    apiClass: 'InvitationsApi',
    sdkType: 'ListInvitations200ResponseDataInner',
    sdkListMethod: 'listInvitations',
    sdkGetMethod: 'getInvitationById',
    sdkCreateMethod: 'createInvitation',
    sdkUpdateMethod: 'updateInvitation',
    sdkDeleteMethod: 'deleteInvitation',
    sdkCreateRequestParam: 'createInvitationRequest',
    sdkUpdateRequestParam: 'updateInvitationRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useInvitations',
      useOne: 'useInvitation',
      useCreate: 'useCreateInvitation',
      useUpdate: 'useUpdateInvitation',
      useDelete: 'useDeleteInvitation'
    },
  },
  {
    name: 'favoritestores',
    type: 'FavoriteStore',
    createType: 'CreateFavoriteStoreInput',
    apiClass: 'FavoriteStoresApi',
    sdkType: 'ListFavoriteStores200ResponseDataInner',
    sdkListMethod: 'listFavoriteStores',
    sdkGetMethod: 'getFavoriteStoreById',
    sdkCreateMethod: 'createFavoriteStore',
    sdkUpdateMethod: 'updateFavoriteStore',
    sdkDeleteMethod: 'deleteFavoriteStore',
    sdkCreateRequestParam: 'createFavoriteStoreRequest',
    sdkUpdateRequestParam: 'updateFavoriteStoreRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useFavoriteStores',
      useOne: 'useFavoriteStore',
      useCreate: 'useCreateFavoriteStore',
      useUpdate: 'useUpdateFavoriteStore',
      useDelete: 'useDeleteFavoriteStore'
    },
  },
  {
    name: 'favoriteitems',
    type: 'FavoriteItem',
    createType: 'CreateFavoriteItemInput',
    apiClass: 'FavoriteItemsApi',
    sdkType: 'ListFavoriteItems200ResponseDataInner',
    sdkListMethod: 'listFavoriteItems',
    sdkGetMethod: 'getFavoriteItemById',
    sdkCreateMethod: 'createFavoriteItem',
    sdkUpdateMethod: 'updateFavoriteItem',
    sdkDeleteMethod: 'deleteFavoriteItem',
    sdkCreateRequestParam: 'createFavoriteItemRequest',
    sdkUpdateRequestParam: 'updateFavoriteItemRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useFavoriteItems',
      useOne: 'useFavoriteItem',
      useCreate: 'useCreateFavoriteItem',
      useUpdate: 'useUpdateFavoriteItem',
      useDelete: 'useDeleteFavoriteItem'
    },
  },
  {
    name: 'bundles',
    type: 'Bundle',
    createType: 'CreateBundleInput',
    apiClass: 'BundlesApi',
    sdkType: 'ListBundles200ResponseDataInner',
    sdkListMethod: 'listBundles',
    sdkGetMethod: 'getBundleById',
    sdkCreateMethod: 'createBundle',
    sdkUpdateMethod: 'updateBundle',
    sdkDeleteMethod: 'deleteBundle',
    sdkCreateRequestParam: 'createBundleRequest',
    sdkUpdateRequestParam: 'updateBundleRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useBundles',
      useOne: 'useBundle',
      useCreate: 'useCreateBundle',
      useUpdate: 'useUpdateBundle',
      useDelete: 'useDeleteBundle'
    },
    extensions: {
      totalItems: 'number',
      individualPrice: 'number',
      bundlePrice: 'number',
      savings: 'number',
      savingsPercent: 'number',
    },
    computed: ``,
  },
  {
    name: 'bundleitems',
    type: 'BundleItem',
    createType: 'CreateBundleItemInput',
    apiClass: 'BundleItemsApi',
    sdkType: 'ListBundleItems200ResponseDataInner',
    sdkListMethod: 'listBundleItems',
    sdkGetMethod: 'getBundleItemById',
    sdkCreateMethod: 'createBundleItem',
    sdkUpdateMethod: 'updateBundleItem',
    sdkDeleteMethod: 'deleteBundleItem',
    sdkCreateRequestParam: 'createBundleItemRequest',
    sdkUpdateRequestParam: 'updateBundleItemRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useBundleItems',
      useOne: 'useBundleItem',
      useCreate: 'useCreateBundleItem',
      useUpdate: 'useUpdateBundleItem',
      useDelete: 'useDeleteBundleItem'
    },
  },
  {
    name: 'bundlepricings',
    type: 'BundlePricing',
    createType: 'CreateBundlePricingInput',
    apiClass: 'BundlePricingsApi',
    sdkType: 'ListBundlePricings200ResponseDataInner',
    sdkListMethod: 'listBundlePricings',
    sdkGetMethod: 'getBundlePricingById',
    sdkCreateMethod: 'createBundlePricing',
    sdkUpdateMethod: 'updateBundlePricing',
    sdkDeleteMethod: 'deleteBundlePricing',
    sdkCreateRequestParam: 'createBundlePricingRequest',
    sdkUpdateRequestParam: 'updateBundlePricingRequest',
    listParams: 'params?: { page?: string; limit?: string }',
    hasCreate: true,
    hasUpdate: true,
    hasDelete: true,
    methods: ['list', 'getById', 'create', 'update', 'delete'],
    hooks: {
      useList: 'useBundlePricings',
      useOne: 'useBundlePricing',
      useCreate: 'useCreateBundlePricing',
      useUpdate: 'useUpdateBundlePricing',
      useDelete: 'useDeleteBundlePricing'
    },
  },
]

/**
 * Custom input types derived from Prisma schemas
 * These are the simplified frontend-focused interfaces
 */
export const CUSTOM_INPUT_TYPES = `
// Re-export from schemas package
export * from '@packages/schemas'
`
