/**
 * River (Social Feed) Feature Styles;
 */

export const river = {
  // Post cards;
  postCard: 'bg-white rounded-lg border border-gray-200 p-6',
  postHeader: 'flex items-start gap-3 mb-4',
  postAvatar: 'w-12 h-12 rounded-full bg-gray-200',
  postAuthor: 'flex-1',
  postAuthorName: 'font-semibold text-gray-900',
  postTime: 'text-sm text-gray-500',
  postContent: 'text-gray-800 mb-4 whitespace-pre-wrap',
  postActions: 'flex items-center gap-6 pt-4 border-t border-gray-200',
  postAction: 'flex items-center gap-2 text-gray-600 hover:text-blue-600 cursor-pointer transition-colors',
  postActionActive: 'text-blue-600',
  actionButton: 'flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-gray-100 transition-colors',
  liked: 'text-red-600',
  storeAvatar: 'w-12 h-12 rounded-full bg-gray-200',
  storeDetails: 'flex-1',
  timestamp: 'text-sm text-gray-500',
  
  // Media;
  mediaPreview: 'grid gap-2 mb-4',
  previewContainer: 'grid gap-2',
  previewItem: 'relative rounded-lg overflow-hidden border border-gray-200',
  youtubePreview: 'relative aspect-video',
  imagePreview: 'relative aspect-square',
  thumbnail: 'w-full h-full object-cover',
  youtubeOverlay: 'absolute inset-0 bg-black/30 flex items-center justify-center',
  playIcon: 'w-12 h-12',
  provider: 'absolute bottom-2 left-2 bg-red-600 text-white px-2 py-1 rounded text-xs font-bold',
  removeButton: 'absolute top-2 right-2 bg-red-600 text-white rounded-full w-6 h-6 flex items-center justify-center cursor-pointer hover:bg-red-700',
  urlInfo: 'flex items-center gap-2 p-2 bg-gray-100 rounded',
  urlText: 'text-sm text-gray-600 truncate',
  mediaSingle: 'grid-cols-1',
  mediaDouble: 'grid-cols-2',
  mediaMultiple: 'grid-cols-2',
  mediaItem: 'relative aspect-square overflow-hidden rounded-lg cursor-pointer',
  mediaImage: 'w-full h-full object-cover hover:scale-105 transition-transform',
  mediaOverlay: 'absolute inset-0 bg-black/50 flex items-center justify-center text-white font-bold text-2xl',
  
  // Post media;
  postMedia: 'mb-4',
  postMediaGrid: 'grid gap-2',
  postMediaSingle: 'grid-cols-1',
  postMediaDouble: 'grid-cols-2',
  postMediaMultiple: 'grid-cols-2',
  postMediaItem: 'relative aspect-square rounded-lg overflow-hidden cursor-pointer',
  postMediaImage: 'w-full h-full object-cover hover:scale-105 transition-transform',
  postMediaMore: 'absolute inset-0 bg-black/50 flex items-center justify-center text-white text-2xl font-bold',
  youtubeContainer: 'mb-4',
  youtubeEmbed: 'w-full aspect-video rounded-lg',
  imageContainer: 'relative aspect-square rounded-lg overflow-hidden',
  singleMedia: 'aspect-video',
  multiMedia: 'grid gap-2',
  mainMedia: 'aspect-video',
  thumbnailStrip: 'flex gap-2 overflow-x-auto',
  thumbnailButton: 'flex-shrink-0 w-20 h-20 rounded border-2 border-transparent hover:border-blue-500 cursor-pointer overflow-hidden',
  active: 'border-blue-600',
  thumbnailOverlay: 'absolute inset-0 bg-black/30 flex items-center justify-center',
  playIconSmall: 'w-6 h-6',
  
  // Composer;
  composerCard: 'bg-white rounded-lg border border-gray-200 p-6',
  composer: 'bg-white rounded-lg border border-gray-200 p-6',
  composerHeader: 'flex items-center gap-3 mb-4',
  composerAvatar: 'w-10 h-10 rounded-full bg-gray-200',
  composerTextarea: 'w-full min-h-32 p-3 border border-gray-300 rounded-lg resize-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
  textarea: 'w-full min-h-32 p-3 border border-gray-300 rounded-lg resize-none focus:ring-2 focus:ring-blue-500 focus:border-transparent',
  composerFooter: 'flex justify-between items-center mt-4',
  composerActions: 'flex gap-2',
  composerButton: 'px-3 py-2 rounded-lg hover:bg-gray-100 transition-colors',
  mediaPreviewContainer: 'mb-4',
  info: 'flex gap-4 text-sm text-gray-600',
  mediaCount: 'font-medium',
  maxReached: 'text-red-600 font-semibold',
  
  // Comments;
  commentsList: 'space-y-4 mt-4 pt-4 border-t border-gray-200',
  commentList: 'space-y-4 mt-4 pt-4 border-t border-gray-200',
  comment: 'flex gap-3',
  commentHeader: 'flex items-center gap-2 mb-2',
  userAvatar: 'w-8 h-8 rounded-full bg-gray-200',
  commentInfo: 'flex-1',
  userName: 'font-semibold text-sm',
  commentItem: 'flex gap-3',
  commentAvatar: 'w-8 h-8 rounded-full bg-gray-200',
  commentContent: 'flex-1 bg-gray-50 rounded-lg p-3',
  commentAuthor: 'font-semibold text-sm text-gray-900',
  commentText: 'text-sm text-gray-800 mt-1',
  commentTime: 'text-xs text-gray-500 mt-1',
  
  // Filters;
  filters: 'flex gap-2 mb-8 overflow-x-auto pb-2',
  filterButton: 'px-6 py-3 border-2 rounded-lg font-medium whitespace-nowrap transition-all border-gray-300 bg-white hover:border-blue-600 hover:bg-blue-50',
  filterButtonActive: 'border-blue-600 bg-blue-600 text-white',
  
  // Feed;
  riverFeed: 'space-y-6',
  riverEmpty: 'text-center py-12 text-gray-500',
  feed: 'space-y-6',
  postList: 'space-y-6',
  errorState: 'text-center py-12 text-red-600',
  errorMessage: 'text-xl font-bold mb-2',
  errorDetail: 'text-sm',
  loadingState: 'text-center py-12 text-gray-600',
  emptyMessage: 'text-xl font-bold text-gray-600 mb-2',
  emptyDescription: 'text-gray-500',
  loadMoreContainer: 'text-center mt-8',
  sortButtons: 'flex gap-2 mb-4',
  sortButton: 'px-4 py-2 border-2 border-gray-300 rounded-lg hover:border-blue-500',
  mediaFilter: 'px-4 py-2 border-2 border-gray-300 rounded-lg hover:border-blue-500'}

