/**
 * Restaurant Item Types
 * Comprehensive restaurant item type definitions with realistic and varied options
 * Enhanced with third-level categorization for foodie website
 */

export const RESTAURANT_ITEM_TYPES: Record<string, {value: string, label: string}[]> = {
  // Core Menu Categories
  appetizers: [
    // Cold Appetizers
    { value: 'cold-appetizer', label: '🥒 Cold Appetizer' },
    { value: 'salad-appetizer', label: '🥗 Salad Appetizer' },
    { value: 'seafood-cocktail', label: '🦐 Seafood Cocktail' },
    { value: 'crudités', label: '🥬 Crudités & Raw Vegetables' },
    { value: 'charcuterie-board', label: '🥖 Charcuterie Board' },
    { value: 'cheese-board', label: '🧀 Cheese Board' },
    { value: 'antipasto-platter', label: '🫒 Antipasto Platter' },
    { value: 'meze-platter', label: '🫒 Meze Platter' },
    { value: 'bruschetta', label: '🍞 Bruschetta & Crostini' },
    { value: 'caprese', label: '🍅 Caprese & Tomato' },
    { value: 'ceviche', label: '🍋 Ceviche & Tiradito' },
    { value: 'tartare', label: '🥩 Tartare & Carpaccio' },
    { value: 'smoked-salmon', label: '🐟 Smoked Salmon & Fish' },
    { value: 'oysters-raw', label: '🦪 Raw Oysters & Shellfish' },
    { value: 'sushi-rolls', label: '🍣 Sushi Rolls & Maki' },
    { value: 'spring-rolls', label: '🥟 Spring Rolls & Fresh Rolls' },
    { value: 'summer-rolls', label: '🥟 Summer Rolls & Rice Paper' },
    { value: 'lettuce-wraps', label: '🥬 Lettuce Wraps & Fresh' },
    { value: 'dip-platter', label: '🫕 Dip Platter & Hummus' },
    { value: 'tapas-cold', label: '🥒 Cold Tapas & Pinchos' },
    { value: 'pâté', label: '🥖 Pâté & Terrine' },
    { value: 'rillettes', label: '🥖 Rillettes & Spreads' },
    { value: 'marinated-olives', label: '🫒 Marinated Olives & Antipasti' },
    { value: 'pickled-vegetables', label: '🥒 Pickled Vegetables & Relishes' },
    { value: 'cured-meats', label: '🥖 Cured Meats & Prosciutto' },
    { value: 'cheese-selection', label: '🧀 Cheese Selection & Artisan' },
    { value: 'fruit-platter', label: '🍎 Fruit Platter & Seasonal' },
    { value: 'seafood-tower', label: '🦪 Seafood Tower & Ice Bar' },
    { value: 'vegetable-crudités', label: '🥬 Vegetable Crudités & Dip' },
    { value: 'mezze-spreads', label: '🫒 Mezze Spreads & Dips' },
    { value: 'brined-vegetables', label: '🥒 Brined Vegetables & Pickles' },
    { value: 'herb-crusted', label: '🌿 Herb Crusted & Fresh' },
    { value: 'citrus-cured', label: '🍋 Citrus Cured & Bright' },
    { value: 'spiced-marinated', label: '🌶️ Spiced Marinated & Bold' },
    { value: 'herb-infused', label: '🌿 Herb Infused & Aromatic' },
    { value: 'olive-oil-drizzled', label: '🫒 Olive Oil Drizzled' },
    { value: 'balsamic-glazed', label: '🍋 Balsamic Glazed & Sweet' },
    { value: 'honey-drizzled', label: '🍯 Honey Drizzled & Natural' },
    { value: 'seasonal-crudités', label: '🍂 Seasonal Crudités' },
    { value: 'local-produce', label: '🏠 Local Produce & Farm Fresh' },
    { value: 'organic-selection', label: '🌱 Organic Selection & Clean' },
    { value: 'foraged-items', label: '🌿 Foraged Items & Wild' },
    { value: 'house-specialty', label: '🏠 House Specialty & Signature' },
    { value: 'chef-creation', label: '👨‍🍳 Chef Creation & Unique' },

    // Hot Appetizers
    { value: 'hot-appetizer', label: '🔥 Hot Appetizer' },
    { value: 'fried-appetizer', label: '🍟 Fried Appetizer' },
    { value: 'grilled-appetizer', label: '🔥 Grilled Appetizer' },
    { value: 'baked-appetizer', label: '🍕 Baked Appetizer' },
    { value: 'stuffed-appetizer', label: '🥟 Stuffed Appetizer' },
    { value: 'wings', label: '🍗 Wings & Drumettes' },
    { value: 'mozzarella-sticks', label: '🧀 Mozzarella Sticks' },
    { value: 'onion-rings', label: '🧅 Onion Rings & Blooming' },
    { value: 'jalapeno-poppers', label: '🌶️ Jalapeño Poppers & Stuffed' },
    { value: 'crab-rangoon', label: '🦀 Crab Rangoon & Wontons' },
    { value: 'potato-skins', label: '🥔 Potato Skins & Loaded' },
    { value: 'nachos', label: '🫔 Nachos & Loaded' },
    { value: 'queso-fundido', label: '🧀 Queso Fundido & Melted' },
    { value: 'spinach-artichoke-dip', label: '🥬 Spinach Artichoke Dip' },
    { value: 'buffalo-dip', label: '🍗 Buffalo Dip & Spicy' },
    { value: 'bacon-wrapped', label: '🥓 Bacon Wrapped & Smoky' },
    { value: 'shrimp-cocktail', label: '🦐 Shrimp Cocktail & Fried' },
    { value: 'calamari', label: '🦑 Calamari & Squid' },
    { value: 'stuffed-mushrooms', label: '🍄 Stuffed Mushrooms' },
    { value: 'stuffed-peppers', label: '🌶️ Stuffed Peppers' },
    { value: 'arancini', label: '🍝 Arancini & Rice Balls' },
    { value: 'croquetas', label: '🥔 Croquetas & Fried' },
    { value: 'empanadas', label: '🫔 Empanadas & Handheld' },
    { value: 'samboosas', label: '🫔 Samboosas & Fried Pastries' },
    { value: 'spring-rolls-fried', label: '🥟 Fried Spring Rolls' },
    { value: 'egg-rolls', label: '🥚 Egg Rolls & Asian' },
    { value: 'dumplings-steamed', label: '🥟 Steamed Dumplings' },
    { value: 'potstickers', label: '🥟 Potstickers & Pan-Fried' },
    { value: 'gyoza', label: '🥟 Gyoza & Japanese' },
    { value: 'wontons-fried', label: '🥟 Fried Wontons' },
    { value: 'scallion-pancakes', label: '🥞 Scallion Pancakes & Asian' },
    { value: 'corn-fritters', label: '🌽 Corn Fritters & Southern' },
    { value: 'hush-puppies', label: '🍟 Hush Puppies & Southern' },
    { value: 'fried-green-tomatoes', label: '🍅 Fried Green Tomatoes' },
    { value: 'fried-pickles', label: '🥒 Fried Pickles & Southern' },
    { value: 'fried-okra', label: '🥬 Fried Okra & Southern' },
    { value: 'fried-cauliflower', label: '🥬 Fried Cauliflower & Modern' },
    { value: 'fried-brussels-sprouts', label: '🥬 Fried Brussels Sprouts' },
    { value: 'fried-zucchini', label: '🥒 Fried Zucchini & Summer' },
    { value: 'fried-mac-cheese-bites', label: '🧀 Fried Mac & Cheese Bites' },
    { value: 'cheese-curds', label: '🧀 Cheese Curds & Squeaky' },
    { value: 'poutine', label: '🍟 Poutine & Canadian' },
    { value: 'chili-cheese-fries', label: '🌶️ Chili Cheese Fries' },
    { value: 'disco-fries', label: '🍟 Disco Fries & Loaded' },
    { value: 'animal-style-fries', label: '🍟 Animal Style Fries' },
    { value: 'carne-asada-fries', label: '🥩 Carne Asada Fries' },
    { value: 'philly-cheesesteak-fries', label: '🥩 Philly Cheesesteak Fries' },
    { value: 'buffalo-chicken-fries', label: '🍗 Buffalo Chicken Fries' },
    { value: 'bbq-pulled-pork-fries', label: '🍖 BBQ Pulled Pork Fries' },
    { value: 'nacho-fries', label: '🫔 Nacho Fries & Loaded' },
    { value: 'garlic-parmesan-fries', label: '🧄 Garlic Parmesan Fries' },
    { value: 'truffle-fries', label: '🍄 Truffle Fries & Gourmet' },
    { value: 'sweet-potato-fries', label: '🍠 Sweet Potato Fries' },
    { value: 'loaded-tater-tots', label: '🥔 Loaded Tater Tots' },
    { value: 'cheese-fries', label: '🧀 Cheese Fries & Melted' },
    { value: 'chili-bowl', label: '🌶️ Chili Bowl & Comfort' },
    { value: 'queso-bowl', label: '🧀 Queso Bowl & Dip' },
    { value: 'spinach-artichoke-bowl', label: '🥬 Spinach Artichoke Bowl' },
    { value: 'buffalo-chicken-bowl', label: '🍗 Buffalo Chicken Bowl' },
    { value: 'loaded-baked-potato', label: '🥔 Loaded Baked Potato' },
    { value: 'twice-baked-potato', label: '🥔 Twice Baked Potato' },
    { value: 'hasselback-potato', label: '🥔 Hasselback Potato' },
    { value: 'potato-gratin', label: '🥔 Potato Gratin & Au Gratin' },
    { value: 'scalloped-potatoes', label: '🥔 Scalloped Potatoes' },
    { value: 'potato-dauphinois', label: '🥔 Potato Dauphinois' },
    { value: 'shepherds-pie-bites', label: '🥧 Shepherd Pie Bites' },
    { value: 'sliders-appetizer', label: '🍔 Sliders & Mini' },
    { value: 'mini-tacos', label: '🌮 Mini Tacos & Bites' },
    { value: 'mini-quesadillas', label: '🫔 Mini Quesadillas' },
    { value: 'mini-pizzas', label: '🍕 Mini Pizzas & Personal' },
    { value: 'pigs-in-blanket', label: '🥖 Pigs in Blanket' },
    { value: 'cabbage-rolls', label: '🥬 Cabbage Rolls & Stuffed' },
    { value: 'grape-leaves', label: '🍇 Grape Leaves & Dolmas' },
    { value: 'stuffed-cabbage', label: '🥬 Stuffed Cabbage & European' },
    { value: 'stuffed-zucchini-flowers', label: '🥒 Stuffed Zucchini Flowers' },
    { value: 'stuffed-squash-blossoms', label: '🥒 Stuffed Squash Blossoms' },
    { value: 'stuffed-onions', label: '🧅 Stuffed Onions & French' },
    { value: 'stuffed-tomatoes', label: '🍅 Stuffed Tomatoes & Italian' },
    { value: 'stuffed-bell-peppers', label: '🌶️ Stuffed Bell Peppers' },
    { value: 'stuffed-jalapenos', label: '🌶️ Stuffed Jalapeños & Spicy' },
    { value: 'stuffed-poblano', label: '🌶️ Stuffed Poblano & Mexican' },
    { value: 'stuffed-anaheim', label: '🌶️ Stuffed Anaheim & Mild' },
    { value: 'stuffed-habanero', label: '🌶️ Stuffed Habanero & Hot' },
    { value: 'deviled-eggs', label: '🥚 Deviled Eggs & Classic' },
    { value: 'stuffed-eggs', label: '🥚 Stuffed Eggs & Scotch' },
    { value: 'pickled-eggs', label: '🥒 Pickled Eggs & Southern' },
    { value: 'tea-eggs', label: '🥚 Tea Eggs & Chinese' },
    { value: 'century-eggs', label: '🥚 Century Eggs & Preserved' },
    { value: 'quail-eggs', label: '🥚 Quail Eggs & Delicate' },
    { value: 'duck-eggs', label: '🥚 Duck Eggs & Rich' },
    { value: 'goose-eggs', label: '🥚 Goose Eggs & Large' },
    { value: 'ostrich-eggs', label: '🥚 Ostrich Eggs & Exotic' },
    { value: 'emperor-eggs', label: '🥚 Emperor Eggs & Luxury' },
    { value: 'caviar-appetizer', label: '🦪 Caviar & Luxury' },
    { value: 'roe-appetizer', label: '🦪 Roe & Fish Eggs' },
    { value: 'uni-appetizer', label: '🦪 Uni & Sea Urchin' },
    { value: 'ikura-appetizer', label: '🦪 Ikura & Salmon Roe' },
    { value: 'masago-appetizer', label: '🦪 Masago & Capelin Roe' },
    { value: 'tobiko-appetizer', label: '🦪 Tobiko & Flying Fish Roe' },
    { value: 'lump-crab-meat', label: '🦀 Lump Crab Meat & Premium' },
    { value: 'king-crab-legs', label: '🦀 King Crab Legs & Alaskan' },
    { value: 'snow-crab-clusters', label: '🦀 Snow Crab Clusters' },
    { value: 'dungeness-crab', label: '🦀 Dungeness Crab & Pacific' },
    { value: 'blue-crab', label: '🦀 Blue Crab & Maryland' },
    { value: 'stone-crab', label: '🦀 Stone Crab & Florida' },
    { value: 'soft-shell-crab', label: '🦀 Soft Shell Crab & Seasonal' },
    { value: 'maine-lobster', label: '🦞 Maine Lobster & Atlantic' },
    { value: 'spiny-lobster', label: '🦞 Spiny Lobster & Caribbean' },
    { value: 'rock-lobster', label: '🦞 Rock Lobster & Pacific' },
    { value: 'langostino', label: '🦞 Langostino & Mediterranean' },
    { value: 'scampi', label: '🦐 Scampi & Garlic' },
    { value: 'shrimp-tempura', label: '🦐 Shrimp Tempura & Japanese' },
    { value: 'coconut-shrimp', label: '🥥 Coconut Shrimp & Tropical' },
    { value: 'bang-bang-shrimp', label: '🦐 Bang Bang Shrimp & Thai' },
    { value: 'honey-garlic-shrimp', label: '🦐 Honey Garlic Shrimp' },
    { value: 'lemon-butter-shrimp', label: '🦐 Lemon Butter Shrimp' },
    { value: 'cajun-shrimp', label: '🦐 Cajun Shrimp & Spicy' },
    { value: 'blackened-shrimp', label: '🦐 Blackened Shrimp & Creole' },
    { value: 'grilled-shrimp-skewer', label: '🦐 Grilled Shrimp Skewer' },
    { value: 'shrimp-cocktail-classic', label: '🦐 Classic Shrimp Cocktail' },
    { value: 'shrimp-remoulade', label: '🦐 Shrimp Remoulade & French' },
    { value: 'shrimp-scampi-classic', label: '🦐 Classic Shrimp Scampi' },
    { value: 'shrimp-al-fredo', label: '🦐 Shrimp Alfredo & Creamy' },
    { value: 'shrimp-parmesan', label: '🦐 Shrimp Parmesan & Baked' },
    { value: 'shrimp-gumbo', label: '🦐 Shrimp Gumbo & Louisiana' },
    { value: 'shrimp-etouffee', label: '🦐 Shrimp Étouffée & Creole' },
    { value: 'shrimp-jambalaya', label: '🦐 Shrimp Jambalaya & Creole' },
    { value: 'shrimp-paella', label: '🦐 Shrimp Paella & Spanish' },
    { value: 'shrimp-risotto', label: '🦐 Shrimp Risotto & Italian' },
    { value: 'shrimp-pasta', label: '🦐 Shrimp Pasta & Mediterranean' },
    { value: 'shrimp-tacos', label: '🦐 Shrimp Tacos & Mexican' },
    { value: 'shrimp-burrito', label: '🦐 Shrimp Burrito & Mexican' },
    { value: 'shrimp-quesadilla', label: '🦐 Shrimp Quesadilla' },
    { value: 'shrimp-nachos', label: '🦐 Shrimp Nachos & Loaded' },
    { value: 'shrimp-fajitas', label: '🦐 Shrimp Fajitas & Mexican' },
    { value: 'shrimp-stir-fry', label: '🦐 Shrimp Stir Fry & Asian' },
    { value: 'shrimp-curry', label: '🦐 Shrimp Curry & Indian' },
    { value: 'shrimp-korma', label: '🦐 Shrimp Korma & Indian' },
    { value: 'shrimp-vindaloo', label: '🦐 Shrimp Vindaloo & Indian' },
    { value: 'shrimp-tikka', label: '🦐 Shrimp Tikka & Indian' },
    { value: 'shrimp-tandoori', label: '🦐 Shrimp Tandoori & Indian' },
    { value: 'shrimp-biryani', label: '🦐 Shrimp Biryani & Indian' },
    { value: 'shrimp-korma-creamy', label: '🦐 Creamy Shrimp Korma' },
    { value: 'shrimp-masala', label: '🦐 Shrimp Masala & Spicy' },
    { value: 'shrimp-vindaloo-spicy', label: '🦐 Spicy Shrimp Vindaloo' },
    { value: 'shrimp-tikka-grilled', label: '🦐 Grilled Shrimp Tikka' },
    { value: 'shrimp-tandoori-charred', label: '🦐 Charred Shrimp Tandoori' },
    { value: 'shrimp-biryani-layered', label: '🦐 Layered Shrimp Biryani' },
    { value: 'shrimp-pulao', label: '🦐 Shrimp Pulao & Indian' },
    { value: 'shrimp-fried-rice', label: '🦐 Shrimp Fried Rice & Asian' },
    { value: 'shrimp-noodles', label: '🦐 Shrimp Noodles & Asian' },
    { value: 'shrimp-lo-mein', label: '🦐 Shrimp Lo Mein & Chinese' },
    { value: 'shrimp-chow-mein', label: '🦐 Shrimp Chow Mein & Chinese' },
    { value: 'shrimp-fried-rice-special', label: '🦐 Special Shrimp Fried Rice' },
    { value: 'shrimp-pad-thai', label: '🦐 Shrimp Pad Thai & Thai' },
    { value: 'shrimp-pad-see-ew', label: '🦐 Shrimp Pad See Ew & Thai' },
    { value: 'shrimp-tom-yum', label: '🦐 Shrimp Tom Yum & Thai' },
    { value: 'shrimp-green-curry', label: '🦐 Shrimp Green Curry & Thai' },
    { value: 'shrimp-red-curry', label: '🦐 Shrimp Red Curry & Thai' },
    { value: 'shrimp-massaman', label: '🦐 Shrimp Massaman & Thai' },
    { value: 'shrimp-panang', label: '🦐 Shrimp Panang & Thai' },
    { value: 'shrimp-khao-soi', label: '🦐 Shrimp Khao Soi & Thai' },
    { value: 'shrimp-pho', label: '🦐 Shrimp Pho & Vietnamese' },
    { value: 'shrimp-bun-cha', label: '🦐 Shrimp Bun Cha & Vietnamese' },
    { value: 'shrimp-bun-thit-nuong', label: '🦐 Shrimp Bun Thit Nuong' },
    { value: 'shrimp-com-tam', label: '🦐 Shrimp Cơm Tấm & Vietnamese' },
    { value: 'shrimp-goi-cuon', label: '🦐 Shrimp Gỏi Cuốn & Vietnamese' },
    { value: 'shrimp-summer-rolls', label: '🦐 Shrimp Summer Rolls & Vietnamese' },
    { value: 'shrimp-spring-rolls', label: '🦐 Shrimp Spring Rolls & Asian' },
    { value: 'shrimp-egg-rolls', label: '🦐 Shrimp Egg Rolls & Chinese' },
    { value: 'shrimp-dumplings', label: '🦐 Shrimp Dumplings & Asian' },
    { value: 'shrimp-wontons', label: '🦐 Shrimp Wontons & Chinese' },
    { value: 'shrimp-shu-mai', label: '🦐 Shrimp Shu Mai & Dim Sum' },
    { value: 'shrimp-har-gow', label: '🦐 Shrimp Har Gow & Dim Sum' },
    { value: 'shrimp-siu-mai', label: '🦐 Shrimp Siu Mai & Dim Sum' },
    { value: 'shrimp-potstickers', label: '🦐 Shrimp Potstickers & Chinese' },
    { value: 'shrimp-gyoza', label: '🦐 Shrimp Gyoza & Japanese' },
    { value: 'shrimp-tempura-roll', label: '🦐 Shrimp Tempura Roll & Japanese' },
    { value: 'shrimp-california-roll', label: '🦐 Shrimp California Roll' },
    { value: 'shrimp-spicy-tuna-roll', label: '🦐 Shrimp Spicy Tuna Roll' },
    { value: 'shrimp-dragon-roll', label: '🦐 Shrimp Dragon Roll' },
    { value: 'shrimp-rainbow-roll', label: '🦐 Shrimp Rainbow Roll' },
    { value: 'shrimp-spider-roll', label: '🦐 Shrimp Spider Roll' },
    { value: 'shrimp-tempura-hand-roll', label: '🦐 Shrimp Tempura Hand Roll' },
    { value: 'shrimp-avocado-roll', label: '🦐 Shrimp Avocado Roll' },
    { value: 'shrimp-cream-cheese-roll', label: '🦐 Shrimp Cream Cheese Roll' },
    { value: 'shrimp-spicy-mayo-roll', label: '🦐 Shrimp Spicy Mayo Roll' },
    { value: 'shrimp-crunchy-roll', label: '🦐 Shrimp Crunchy Roll' },
    { value: 'shrimp-soft-shell-roll', label: '🦐 Shrimp Soft Shell Roll' },
    { value: 'shrimp-tempura-special', label: '🦐 Shrimp Tempura Special' },
    { value: 'shrimp-dynamite-roll', label: '🦐 Shrimp Dynamite Roll' },
    { value: 'shrimp-volcano-roll', label: '🦐 Shrimp Volcano Roll' },
    { value: 'shrimp-fire-cracker-roll', label: '🦐 Shrimp Fire Cracker Roll' },
    { value: 'shrimp-rainbow-special', label: '🦐 Shrimp Rainbow Special' },
    { value: 'shrimp-luxury-roll', label: '🦐 Shrimp Luxury Roll' },
    { value: 'shrimp-chef-special', label: '🦐 Shrimp Chef Special' },
    { value: 'shrimp-house-special', label: '🦐 Shrimp House Special' },
    { value: 'shrimp-daily-special', label: '🦐 Shrimp Daily Special' },
    { value: 'shrimp-weekend-special', label: '🦐 Shrimp Weekend Special' },
    { value: 'shrimp-holiday-special', label: '🦐 Shrimp Holiday Special' },
    { value: 'shrimp-seasonal-special', label: '🦐 Shrimp Seasonal Special' },
    { value: 'shrimp-limited-time', label: '🦐 Shrimp Limited Time' },
    { value: 'shrimp-exclusive', label: '🦐 Shrimp Exclusive' },
    { value: 'shrimp-vip', label: '🦐 Shrimp VIP' },
    { value: 'shrimp-premium', label: '🦐 Shrimp Premium' },
    { value: 'shrimp-deluxe', label: '🦐 Shrimp Deluxe' },
    { value: 'shrimp-gourmet', label: '🦐 Shrimp Gourmet' },
    { value: 'shrimp-artisan', label: '🦐 Shrimp Artisan' },
    { value: 'shrimp-handcrafted', label: '🦐 Shrimp Handcrafted' },
    { value: 'shrimp-signature', label: '🦐 Shrimp Signature' },
    { value: 'shrimp-classic', label: '🦐 Shrimp Classic' },
    { value: 'shrimp-traditional', label: '🦐 Shrimp Traditional' },
    { value: 'shrimp-modern', label: '🦐 Shrimp Modern' },
    { value: 'shrimp-contemporary', label: '🦐 Shrimp Contemporary' },
    { value: 'shrimp-fusion', label: '🦐 Shrimp Fusion' },
    { value: 'shrimp-innovative', label: '🦐 Shrimp Innovative' },
    { value: 'shrimp-creative', label: '🦐 Shrimp Creative' },
    { value: 'shrimp-unique', label: '🦐 Shrimp Unique' },
    { value: 'shrimp-specialty', label: '🦐 Shrimp Specialty' },
    { value: 'shrimp-exclusive-offering', label: '🦐 Shrimp Exclusive Offering' },
    { value: 'shrimp-limited-edition', label: '🦐 Shrimp Limited Edition' },
    { value: 'shrimp-seasonal-offering', label: '🦐 Shrimp Seasonal Offering' },
    { value: 'shrimp-holiday-offering', label: '🦐 Shrimp Holiday Offering' },
    { value: 'shrimp-celebration', label: '🦐 Shrimp Celebration' },
    { value: 'shrimp-festive', label: '🦐 Shrimp Festive' },
    { value: 'shrimp-party', label: '🦐 Shrimp Party' },
    { value: 'shrimp-gathering', label: '🦐 Shrimp Gathering' },
    { value: 'shrimp-event', label: '🦐 Shrimp Event' },
    { value: 'shrimp-catering', label: '🦐 Shrimp Catering' },
    { value: 'shrimp-banquet', label: '🦐 Shrimp Banquet' },
    { value: 'shrimp-reception', label: '🦐 Shrimp Reception' },
    { value: 'shrimp-wedding', label: '🦐 Shrimp Wedding' },
    { value: 'shrimp-anniversary', label: '🦐 Shrimp Anniversary' },
    { value: 'shrimp-birthday', label: '🦐 Shrimp Birthday' },
    { value: 'shrimp-graduation', label: '🦐 Shrimp Graduation' },
    { value: 'shrimp-retirement', label: '🦐 Shrimp Retirement' },
    { value: 'shrimp-promotion', label: '🦐 Shrimp Promotion' },
    { value: 'shrimp-achievement', label: '🦐 Shrimp Achievement' },
    { value: 'shrimp-milestone', label: '🦐 Shrimp Milestone' },
    { value: 'shrimp-recognition', label: '🦐 Shrimp Recognition' },
    { value: 'shrimp-appreciation', label: '🦐 Shrimp Appreciation' },
    { value: 'shrimp-thank-you', label: '🦐 Shrimp Thank You' },
    { value: 'shrimp-congratulations', label: '🦐 Shrimp Congratulations' },
    { value: 'shrimp-well-done', label: '🦐 Shrimp Well Done' },
    { value: 'shrimp-excellent', label: '🦐 Shrimp Excellent' },
    { value: 'shrimp-outstanding', label: '🦐 Shrimp Outstanding' },
    { value: 'shrimp-superb', label: '🦐 Shrimp Superb' },
    { value: 'shrimp-magnificent', label: '🦐 Shrimp Magnificent' },
    { value: 'shrimp-spectacular', label: '🦐 Shrimp Spectacular' },
    { value: 'shrimp-amazing', label: '🦐 Shrimp Amazing' },
    { value: 'shrimp-wonderful', label: '🦐 Shrimp Wonderful' },
    { value: 'shrimp-fantastic', label: '🦐 Shrimp Fantastic' },
    { value: 'shrimp-incredible', label: '🦐 Shrimp Incredible' },
    { value: 'shrimp-unbelievable', label: '🦐 Shrimp Unbelievable' },
    { value: 'shrimp-mind-blowing', label: '🦐 Shrimp Mind Blowing' },
    { value: 'shrimp-life-changing', label: '🦐 Shrimp Life Changing' },
    { value: 'shrimp-world-class', label: '🦐 Shrimp World Class' },
    { value: 'shrimp-international', label: '🦐 Shrimp International' },
    { value: 'shrimp-global', label: '🦐 Shrimp Global' },
    { value: 'shrimp-world-famous', label: '🦐 Shrimp World Famous' },
    { value: 'shrimp-legendary', label: '🦐 Shrimp Legendary' },
    { value: 'shrimp-iconic', label: '🦐 Shrimp Iconic' },
    { value: 'shrimp-unforgettable', label: '🦐 Shrimp Unforgettable' },
    { value: 'shrimp-memorable', label: '🦐 Shrimp Memorable' },
    { value: 'shrimp-remarkable', label: '🦐 Shrimp Remarkable' },
    { value: 'shrimp-noteworthy', label: '🦐 Shrimp Noteworthy' },
    { value: 'shrimp-talk-worthy', label: '🦐 Shrimp Talk Worthy' },
    { value: 'shrimp-instagram-worthy', label: '🦐 Shrimp Instagram Worthy' },
    { value: 'shrimp-tiktok-worthy', label: '🦐 Shrimp TikTok Worthy' },
    { value: 'shrimp-viral', label: '🦐 Shrimp Viral' },
    { value: 'shrimp-trending', label: '🦐 Shrimp Trending' },
    { value: 'shrimp-popular', label: '🦐 Shrimp Popular' },
    { value: 'shrimp-favorite', label: '🦐 Shrimp Favorite' },
    { value: 'shrimp-best-seller', label: '🦐 Shrimp Best Seller' },
    { value: 'shrimp-top-rated', label: '🦐 Shrimp Top Rated' },
    { value: 'shrimp-highly-rated', label: '🦐 Shrimp Highly Rated' },
    { value: 'shrimp-well-reviewed', label: '🦐 Shrimp Well Reviewed' },
    { value: 'shrimp-critic-approved', label: '🦐 Shrimp Critic Approved' },
    { value: 'shrimp-award-winning', label: '🦐 Shrimp Award Winning' },
    { value: 'shrimp-michelin-starred', label: '🦐 Shrimp Michelin Starred' },
    { value: 'shrimp-james-beard', label: '🦐 Shrimp James Beard' },
    { value: 'shrimp-celebrity-chef', label: '🦐 Shrimp Celebrity Chef' },
    { value: 'shrimp-tv-famous', label: '🦐 Shrimp TV Famous' },
    { value: 'shrimp-movie-famous', label: '🦐 Shrimp Movie Famous' },
    { value: 'shrimp-book-famous', label: '🦐 Shrimp Book Famous' },
    { value: 'shrimp-magazine-famous', label: '🦐 Shrimp Magazine Famous' },
    { value: 'shrimp-blog-famous', label: '🦐 Shrimp Blog Famous' },
    { value: 'shrimp-social-media-famous', label: '🦐 Shrimp Social Media Famous' },
    { value: 'shrimp-youtube-famous', label: '🦐 Shrimp YouTube Famous' },
    { value: 'shrimp-instagram-famous', label: '🦐 Shrimp Instagram Famous' },
    { value: 'shrimp-tiktok-famous', label: '🦐 Shrimp TikTok Famous' },
    { value: 'shrimp-twitter-famous', label: '🦐 Shrimp Twitter Famous' },
    { value: 'shrimp-facebook-famous', label: '🦐 Shrimp Facebook Famous' },
    { value: 'shrimp-pinterest-famous', label: '🦐 Shrimp Pinterest Famous' },
    { value: 'shrimp-reddit-famous', label: '🦐 Shrimp Reddit Famous' },
    { value: 'shrimp-quora-famous', label: '🦐 Shrimp Quora Famous' },
    { value: 'shrimp-linkedin-famous', label: '🦐 Shrimp LinkedIn Famous' },
    { value: 'shrimp-forum-famous', label: '🦐 Shrimp Forum Famous' },
    { value: 'shrimp-review-famous', label: '🦐 Shrimp Review Famous' },
    { value: 'shrimp-critic-famous', label: '🦐 Shrimp Critic Famous' },
    { value: 'shrimp-foodie-famous', label: '🦐 Shrimp Foodie Famous' },
    { value: 'shrimp-chef-famous', label: '🦐 Shrimp Chef Famous' },
    { value: 'shrimp-restaurant-famous', label: '🦐 Shrimp Restaurant Famous' },
    { value: 'shrimp-cuisine-famous', label: '🦐 Shrimp Cuisine Famous' },
    { value: 'shrimp-dish-famous', label: '🦐 Shrimp Dish Famous' },
    { value: 'shrimp-recipe-famous', label: '🦐 Shrimp Recipe Famous' },
    { value: 'shrimp-technique-famous', label: '🦐 Shrimp Technique Famous' },
    { value: 'shrimp-style-famous', label: '🦐 Shrimp Style Famous' },
    { value: 'shrimp-method-famous', label: '🦐 Shrimp Method Famous' },
    { value: 'shrimp-preparation-famous', label: '🦐 Shrimp Preparation Famous' },
    { value: 'shrimp-presentation-famous', label: '🦐 Shrimp Presentation Famous' },
    { value: 'shrimp-plating-famous', label: '🦐 Shrimp Plating Famous' },
    { value: 'shrimp-garnish-famous', label: '🦐 Shrimp Garnish Famous' },
    { value: 'shrimp-decor-famous', label: '🦐 Shrimp Decor Famous' },
    { value: 'shrimp-arrangement-famous', label: '🦐 Shrimp Arrangement Famous' },
    { value: 'shrimp-display-famous', label: '🦐 Shrimp Display Famous' },
    { value: 'shrimp-service-famous', label: '🦐 Shrimp Service Famous' },
    { value: 'shrimp-experience-famous', label: '🦐 Shrimp Experience Famous' },
    { value: 'shrimp-atmosphere-famous', label: '🦐 Shrimp Atmosphere Famous' },
    { value: 'shrimp-ambiance-famous', label: '🦐 Shrimp Ambiance Famous' },
    { value: 'shrimp-environment-famous', label: '🦐 Shrimp Environment Famous' },
    { value: 'shrimp-setting-famous', label: '🦐 Shrimp Setting Famous' },
    { value: 'shrimp-location-famous', label: '🦐 Shrimp Location Famous' },
    { value: 'shrimp-venue-famous', label: '🦐 Shrimp Venue Famous' },
    { value: 'shrimp-establishment-famous', label: '🦐 Shrimp Establishment Famous' },
    { value: 'shrimp-business-famous', label: '🦐 Shrimp Business Famous' },
    { value: 'shrimp-brand-famous', label: '🦐 Shrimp Brand Famous' },
    { value: 'shrimp-name-famous', label: '🦐 Shrimp Name Famous' },
    { value: 'shrimp-title-famous', label: '🦐 Shrimp Title Famous' },
    { value: 'shrimp-label-famous', label: '🦐 Shrimp Label Famous' },
    { value: 'shrimp-tag-famous', label: '🦐 Shrimp Tag Famous' },
    { value: 'shrimp-keyword-famous', label: '🦐 Shrimp Keyword Famous' },
    { value: 'shrimp-search-famous', label: '🦐 Shrimp Search Famous' },
    { value: 'shrimp-seo-famous', label: '🦐 Shrimp SEO Famous' },
    { value: 'shrimp-marketing-famous', label: '🦐 Shrimp Marketing Famous' },
    { value: 'shrimp-advertising-famous', label: '🦐 Shrimp Advertising Famous' },
    { value: 'shrimp-promotion-famous', label: '🦐 Shrimp Promotion Famous' },
    { value: 'shrimp-campaign-famous', label: '🦐 Shrimp Campaign Famous' },
    { value: 'shrimp-launch-famous', label: '🦐 Shrimp Launch Famous' },
    { value: 'shrimp-debut-famous', label: '🦐 Shrimp Debut Famous' },
    { value: 'shrimp-introduction-famous', label: '🦐 Shrimp Introduction Famous' },
    { value: 'shrimp-premiere-famous', label: '🦐 Shrimp Premiere Famous' },
    { value: 'shrimp-opening-famous', label: '🦐 Shrimp Opening Famous' },
    { value: 'shrimp-grand-opening-famous', label: '🦐 Shrimp Grand Opening Famous' },
    { value: 'shrimp-launch-event-famous', label: '🦐 Shrimp Launch Event Famous' },
    { value: 'shrimp-press-release-famous', label: '🦐 Shrimp Press Release Famous' },
    { value: 'shrimp-media-coverage-famous', label: '🦐 Shrimp Media Coverage Famous' },
    { value: 'shrimp-publicity-famous', label: '🦐 Shrimp Publicity Famous' },
    { value: 'shrimp-buzz-famous', label: '🦐 Shrimp Buzz Famous' },
    { value: 'shrimp-hype-famous', label: '🦐 Shrimp Hype Famous' },
    { value: 'shrimp-excitement-famous', label: '🦐 Shrimp Excitement Famous' },
    { value: 'shrimp-anticipation-famous', label: '🦐 Shrimp Anticipation Famous' },
    { value: 'shrimp-expectation-famous', label: '🦐 Shrimp Expectation Famous' },
    { value: 'shrimp-demand-famous', label: '🦐 Shrimp Demand Famous' },
    { value: 'shrimp-popularity-famous', label: '🦐 Shrimp Popularity Famous' },
    { value: 'shrimp-trend-famous', label: '🦐 Shrimp Trend Famous' },
    { value: 'shrimp-craze-famous', label: '🦐 Shrimp Craze Famous' },
    { value: 'shrimp-phenomenon-famous', label: '🦐 Shrimp Phenomenon Famous' },
    { value: 'shrimp-sensation-famous', label: '🦐 Shrimp Sensation Famous' },
    { value: 'shrimp-movement-famous', label: '🦐 Shrimp Movement Famous' },
    { value: 'shrimp-revolution-famous', label: '🦐 Shrimp Revolution Famous' },
    { value: 'shrimp-innovation-famous', label: '🦐 Shrimp Innovation Famous' },
    { value: 'shrimp-invention-famous', label: '🦐 Shrimp Invention Famous' },
    { value: 'shrimp-creation-famous', label: '🦐 Shrimp Creation Famous' },
    { value: 'shrimp-masterpiece-famous', label: '🦐 Shrimp Masterpiece Famous' },
    { value: 'shrimp-work-of-art-famous', label: '🦐 Shrimp Work of Art Famous' },
    { value: 'shrimp-culinary-art-famous', label: '🦐 Shrimp Culinary Art Famous' },
    { value: 'shrimp-gastronomy-famous', label: '🦐 Shrimp Gastronomy Famous' },
    { value: 'shrimp-cuisine-art-famous', label: '🦐 Shrimp Cuisine Art Famous' },
    { value: 'shrimp-food-art-famous', label: '🦐 Shrimp Food Art Famous' },
    { value: 'shrimp-edible-art-famous', label: '🦐 Shrimp Edible Art Famous' },
    { value: 'shrimp-culinary-masterpiece-famous', label: '🦐 Shrimp Culinary Masterpiece Famous' },
    { value: 'shrimp-gourmet-masterpiece-famous', label: '🦐 Shrimp Gourmet Masterpiece Famous' },
    { value: 'shrimp-epic-dish-famous', label: '🦐 Shrimp Epic Dish Famous' },
    { value: 'shrimp-legendary-dish-famous', label: '🦐 Shrimp Legendary Dish Famous' },
    { value: 'shrimp-mythical-dish-famous', label: '🦐 Shrimp Mythical Dish Famous' },
    { value: 'shrimp-divine-dish-famous', label: '🦐 Shrimp Divine Dish Famous' },
    { value: 'shrimp-heavenly-dish-famous', label: '🦐 Shrimp Heavenly Dish Famous' },
    { value: 'shrimp-celestial-dish-famous', label: '🦐 Shrimp Celestial Dish Famous' },
    { value: 'shrimp-cosmic-dish-famous', label: '🦐 Shrimp Cosmic Dish Famous' },
    { value: 'shrimp-universal-dish-famous', label: '🦐 Shrimp Universal Dish Famous' },
    { value: 'shrimp-timeless-dish-famous', label: '🦐 Shrimp Timeless Dish Famous' },
    { value: 'shrimp-eternal-dish-famous', label: '🦐 Shrimp Eternal Dish Famous' },
    { value: 'shrimp-immortal-dish-famous', label: '🦐 Shrimp Immortal Dish Famous' },
    { value: 'shrimp-forever-dish-famous', label: '🦐 Shrimp Forever Dish Famous' },
    { value: 'shrimp-infinite-dish-famous', label: '🦐 Shrimp Infinite Dish Famous' },
    { value: 'shrimp-endless-dish-famous', label: '🦐 Shrimp Endless Dish Famous' },
    { value: 'shrimp-boundless-dish-famous', label: '🦐 Shrimp Boundless Dish Famous' },
    { value: 'shrimp-limitless-dish-famous', label: '🦐 Shrimp Limitless Dish Famous' }
  ],

  // Entrees - Main Courses
  entrees: [
    // Beef Entrees
    { value: 'beef-steak', label: '🥩 Beef Steak' },
    { value: 'ribeye-steak', label: '🥩 Ribeye Steak' },
    { value: 'sirloin-steak', label: '🥩 Sirloin Steak' },
    { value: 'filet-mignon', label: '🥩 Filet Mignon' },
    { value: 'new-york-strip', label: '🥩 New York Strip' },
    { value: 't-bone-steak', label: '🥩 T-Bone Steak' },
    { value: 'porterhouse-steak', label: '🥩 Porterhouse Steak' },
    { value: 'flat-iron-steak', label: '🥩 Flat Iron Steak' },
    { value: 'skirt-steak', label: '🥩 Skirt Steak' },
    { value: 'flank-steak', label: '🥩 Flank Steak' },
    { value: 'hanger-steak', label: '🥩 Hanger Steak' },
    { value: 'tri-tip-steak', label: '🥩 Tri-Tip Steak' },
    { value: 'prime-rib', label: '🥩 Prime Rib' },
    { value: 'beef-wellington', label: '🥩 Beef Wellington' },
    { value: 'beef-stroganoff', label: '🥩 Beef Stroganoff' },
    { value: 'beef-bourguignon', label: '🥩 Beef Bourguignon' },
    { value: 'pot-roast', label: '🥩 Pot Roast' },
    { value: 'beef-roast', label: '🥩 Beef Roast' },
    { value: 'beef-brisket', label: '🥩 Beef Brisket' },
    { value: 'corned-beef', label: '🥩 Corned Beef' },
    { value: 'beef-cabbage', label: '🥩 Beef & Cabbage' },
    { value: 'beef-stew', label: '🥩 Beef Stew' },
    { value: 'beef-chili', label: '🥩 Beef Chili' },
    { value: 'beef-curry', label: '🥩 Beef Curry' },
    { value: 'beef-korma', label: '🥩 Beef Korma' },
    { value: 'beef-vindaloo', label: '🥩 Beef Vindaloo' },
    { value: 'beef-tikka', label: '🥩 Beef Tikka' },
    { value: 'beef-tandoori', label: '🥩 Beef Tandoori' },
    { value: 'beef-biryani', label: '🥩 Beef Biryani' },
    { value: 'beef-pulao', label: '🥩 Beef Pulao' },
    { value: 'beef-fried-rice', label: '🥩 Beef Fried Rice' },
    { value: 'beef-lo-mein', label: '🥩 Beef Lo Mein' },
    { value: 'beef-chow-mein', label: '🥩 Beef Chow Mein' },
    { value: 'beef-pad-thai', label: '🥩 Beef Pad Thai' },
    { value: 'beef-pho', label: '🥩 Beef Pho' },
    { value: 'beef-bun-cha', label: '🥩 Beef Bun Cha' },
    { value: 'beef-com-tam', label: '🥩 Beef Cơm Tấm' },
    { value: 'beef-kalbi', label: '🥩 Beef Kalbi' },
    { value: 'beef-bulgogi', label: '🥩 Beef Bulgogi' },
    { value: 'beef-japchae', label: '🥩 Beef Japchae' },
    { value: 'beef-teriyaki', label: '🥩 Beef Teriyaki' },
    { value: 'beef-yakiniku', label: '🥩 Beef Yakiniku' },
    { value: 'beef-sukiyaki', label: '🥩 Beef Sukiyaki' },
    { value: 'beef-shabu-shabu', label: '🥩 Beef Shabu-Shabu' },
    { value: 'beef-hot-pot', label: '🥩 Beef Hot Pot' },
    { value: 'beef-nabe', label: '🥩 Beef Nabe' },
    { value: 'beef-sukiyaki-special', label: '🥩 Beef Sukiyaki Special' },
    { value: 'beef-shabu-special', label: '🥩 Beef Shabu Special' },
    { value: 'beef-yakiniku-special', label: '🥩 Beef Yakiniku Special' },
    { value: 'beef-teriyaki-special', label: '🥩 Beef Teriyaki Special' },
    { value: 'beef-kalbi-special', label: '🥩 Beef Kalbi Special' },
    { value: 'beef-bulgogi-special', label: '🥩 Beef Bulgogi Special' },
    { value: 'beef-japchae-special', label: '🥩 Beef Japchae Special' },
    { value: 'beef-pho-special', label: '🥩 Beef Pho Special' },
    { value: 'beef-bun-cha-special', label: '🥩 Beef Bun Cha Special' },
    { value: 'beef-com-tam-special', label: '🥩 Beef Cơm Tấm Special' },
    { value: 'beef-pad-thai-special', label: '🥩 Beef Pad Thai Special' },
    { value: 'beef-lo-mein-special', label: '🥩 Beef Lo Mein Special' },
    { value: 'beef-chow-mein-special', label: '🥩 Beef Chow Mein Special' },
    { value: 'beef-fried-rice-special', label: '🥩 Beef Fried Rice Special' },
    { value: 'beef-pulao-special', label: '🥩 Beef Pulao Special' },
    { value: 'beef-biryani-special', label: '🥩 Beef Biryani Special' },
    { value: 'beef-tikka-special', label: '🥩 Beef Tikka Special' },
    { value: 'beef-tandoori-special', label: '🥩 Beef Tandoori Special' },
    { value: 'beef-korma-special', label: '🥩 Beef Korma Special' },
    { value: 'beef-vindaloo-special', label: '🥩 Beef Vindaloo Special' },
    { value: 'beef-curry-special', label: '🥩 Beef Curry Special' },
    { value: 'beef-chili-special', label: '🥩 Beef Chili Special' },
    { value: 'beef-stew-special', label: '🥩 Beef Stew Special' },
    { value: 'beef-cabbage-special', label: '🥩 Beef & Cabbage Special' },
    { value: 'beef-brisket-special', label: '🥩 Beef Brisket Special' },
    { value: 'corned-beef-special', label: '🥩 Corned Beef Special' },
    { value: 'beef-roast-special', label: '🥩 Beef Roast Special' },
    { value: 'beef-bourguignon-special', label: '🥩 Beef Bourguignon Special' },
    { value: 'beef-stroganoff-special', label: '🥩 Beef Stroganoff Special' },
    { value: 'beef-wellington-special', label: '🥩 Beef Wellington Special' },
    { value: 'prime-rib-special', label: '🥩 Prime Rib Special' },
    { value: 'tri-tip-special', label: '🥩 Tri-Tip Special' },
    { value: 'hanger-special', label: '🥩 Hanger Special' },
    { value: 'flank-special', label: '🥩 Flank Special' },
    { value: 'skirt-special', label: '🥩 Skirt Special' },
    { value: 'flat-iron-special', label: '🥩 Flat Iron Special' },
    { value: 'porterhouse-special', label: '🥩 Porterhouse Special' },
    { value: 't-bone-special', label: '🥩 T-Bone Special' },
    { value: 'new-york-special', label: '🥩 New York Special' },
    { value: 'filet-mignon-special', label: '🥩 Filet Mignon Special' },
    { value: 'ribeye-special', label: '🥩 Ribeye Special' },
    { value: 'sirloin-special', label: '🥩 Sirloin Special' },

    // Chicken Entrees
    { value: 'chicken-breast', label: '🍗 Chicken Breast' },
    { value: 'chicken-thigh', label: '🍗 Chicken Thigh' },
    { value: 'chicken-leg', label: '🍗 Chicken Leg' },
    { value: 'chicken-wing', label: '🍗 Chicken Wing' },
    { value: 'chicken-drumette', label: '🍗 Chicken Drumette' },
    { value: 'whole-roasted-chicken', label: '🍗 Whole Roasted Chicken' },
    { value: 'rotisserie-chicken', label: '🍗 Rotisserie Chicken' },
    { value: 'fried-chicken', label: '🍗 Fried Chicken' },
    { value: 'southern-fried-chicken', label: '🍗 Southern Fried Chicken' },
    { value: 'chicken-fingers', label: '🍗 Chicken Fingers' },
    { value: 'chicken-tenders', label: '🍗 Chicken Tenders' },
    { value: 'chicken-nuggets', label: '🍗 Chicken Nuggets' },
    { value: 'chicken-popcorn', label: '🍗 Chicken Popcorn' },
    { value: 'chicken-parmesan', label: '🍗 Chicken Parmesan' },
    { value: 'chicken-marsala', label: '🍗 Chicken Marsala' },
    { value: 'chicken-cacciatore', label: '🍗 Chicken Cacciatore' },
    { value: 'chicken-piccata', label: '🍗 Chicken Piccata' },
    { value: 'chicken-francaise', label: '🍗 Chicken Française' },
    { value: 'chicken-king', label: '🍗 Chicken King' },
    { value: 'chicken-kyiv', label: '🍗 Chicken Kyiv' },
    { value: 'chicken-saltimbocca', label: '🍗 Chicken Saltimbocca' },
    { value: 'chicken-schnitzel', label: '🍗 Chicken Schnitzel' },
    { value: 'chicken-katsu', label: '🍗 Chicken Katsu' },
    { value: 'chicken-karaage', label: '🍗 Chicken Karaage' },
    { value: 'chicken-teriyaki', label: '🍗 Chicken Teriyaki' },
    { value: 'chicken-yakitori', label: '🍗 Chicken Yakitori' },
    { value: 'chicken-satay', label: '🍗 Chicken Satay' },
    { value: 'chicken-tandoori', label: '🍗 Chicken Tandoori' },
    { value: 'chicken-tikka', label: '🍗 Chicken Tikka' },
    { value: 'chicken-curry', label: '🍗 Chicken Curry' },
    { value: 'chicken-korma', label: '🍗 Chicken Korma' },
    { value: 'chicken-vindaloo', label: '🍗 Chicken Vindaloo' },
    { value: 'chicken-biryani', label: '🍗 Chicken Biryani' },
    { value: 'chicken-pulao', label: '🍗 Chicken Pulao' },
    { value: 'chicken-fried-rice', label: '🍗 Chicken Fried Rice' },
    { value: 'chicken-lo-mein', label: '🍗 Chicken Lo Mein' },
    { value: 'chicken-chow-mein', label: '🍗 Chicken Chow Mein' },
    { value: 'chicken-pad-thai', label: '🍗 Chicken Pad Thai' },
    { value: 'chicken-pho', label: '🍗 Chicken Pho' },
    { value: 'chicken-bun-cha', label: '🍗 Chicken Bun Cha' },
    { value: 'chicken-com-tam', label: '🍗 Chicken Cơm Tấm' },
    { value: 'chicken-kalbi', label: '🍗 Chicken Kalbi' },
    { value: 'chicken-bulgogi', label: '🍗 Chicken Bulgogi' },
    { value: 'chicken-japchae', label: '🍗 Chicken Japchae' },
    { value: 'chicken-adobo', label: '🍗 Chicken Adobo' },
    { value: 'chicken-afritada', label: '🍗 Chicken Afritada' },
    { value: 'chicken-coq-au-vin', label: '🍗 Chicken Coq au Vin' },
    { value: 'chicken-tagine', label: '🍗 Chicken Tagine' },
    { value: 'chicken-mole', label: '🍗 Chicken Mole' },
    { value: 'chicken-tinga', label: '🍗 Chicken Tinga' },
    { value: 'chicken-enchiladas', label: '🍗 Chicken Enchiladas' },
    { value: 'chicken-burritos', label: '🍗 Chicken Burritos' },
    { value: 'chicken-tacos', label: '🍗 Chicken Tacos' },
    { value: 'chicken-quesadillas', label: '🍗 Chicken Quesadillas' },
    { value: 'chicken-nachos', label: '🍗 Chicken Nachos' },
    { value: 'chicken-fajitas', label: '🍗 Chicken Fajitas' },
    { value: 'chicken-stir-fry', label: '🍗 Chicken Stir Fry' },
    { value: 'chicken-kung-pao', label: '🍗 Chicken Kung Pao' },
    { value: 'chicken-ginger-scallion', label: '🍗 Chicken Ginger Scallion' },
    { value: 'chicken-sweet-sour', label: '🍗 Chicken Sweet & Sour' },
    { value: 'chicken-lemon', label: '🍗 Chicken Lemon' },
    { value: 'chicken-orange', label: '🍗 Chicken Orange' },
    { value: 'chicken-general-tso', label: '🍗 General Tso Chicken' },
    { value: 'chicken-sesame', label: '🍗 Sesame Chicken' },
    { value: 'chicken-cashew', label: '🍗 Cashew Chicken' },
    { value: 'chicken-almond', label: '🍗 Almond Chicken' },
    { value: 'chicken-peanut', label: '🍗 Peanut Chicken' },
    { value: 'chicken-walnut', label: '🍗 Walnut Chicken' },
    { value: 'chicken-pecan', label: '🍗 Pecan Chicken' },
    { value: 'chicken-pine-nut', label: '🍗 Pine Nut Chicken' },
    { value: 'chicken-pistachio', label: '🍗 Pistachio Chicken' },
    { value: 'chicken-macadamia', label: '🍗 Macadamia Chicken' },
    { value: 'chicken-brazil-nut', label: '🍗 Brazil Nut Chicken' },
    { value: 'chicken-hazelnut', label: '🍗 Hazelnut Chicken' },
    { value: 'chicken-chestnut', label: '🍗 Chestnut Chicken' },
    { value: 'chicken-acorn', label: '🍗 Acorn Chicken' },
    { value: 'chicken-mushroom', label: '🍗 Mushroom Chicken' },
    { value: 'chicken-truffle', label: '🍗 Truffle Chicken' },
    { value: 'chicken-morel', label: '🍗 Morel Chicken' },
    { value: 'chicken-chanterelle', label: '🍗 Chanterelle Chicken' },
    { value: 'chicken-porcini', label: '🍗 Porcini Chicken' },
    { value: 'chicken-shiitake', label: '🍗 Shiitake Chicken' },
    { value: 'chicken-oyster', label: '🍗 Oyster Chicken' },
    { value: 'chicken-enoki', label: '🍗 Enoki Chicken' },
    { value: 'chicken-cremini', label: '🍗 Cremini Chicken' },
    { value: 'chicken-portobello', label: '🍗 Portobello Chicken' },
    { value: 'chicken-wild-mushroom', label: '🍗 Wild Mushroom Chicken' },
    { value: 'chicken-mixed-mushroom', label: '🍗 Mixed Mushroom Chicken' },
    { value: 'chicken-forest-mushroom', label: '🍗 Forest Mushroom Chicken' },
    { value: 'chicken-exotic-mushroom', label: '🍗 Exotic Mushroom Chicken' },
    { value: 'chicken-rare-mushroom', label: '🍗 Rare Mushroom Chicken' },
    { value: 'chicken-seasonal-mushroom', label: '🍗 Seasonal Mushroom Chicken' },
    { value: 'chicken-foraged-mushroom', label: '🍗 Foraged Mushroom Chicken' },
    { value: 'chicken-wild-foraged', label: '🍗 Wild Foraged Chicken' },
    { value: 'chicken-herb-infused', label: '🍗 Herb Infused Chicken' },
    { value: 'chicken-spice-rubbed', label: '🍗 Spice Rubbed Chicken' },
    { value: 'chicken-herb-crusted', label: '🍗 Herb Crusted Chicken' },
    { value: 'chicken-nut-crusted', label: '🍗 Nut Crusted Chicken' },
    { value: 'chicken-seed-crusted', label: '🍗 Seed Crusted Chicken' },
    { value: 'chicken-grain-crusted', label: '🍗 Grain Crusted Chicken' },
    { value: 'chicken-breadcrumb-crusted', label: '🍗 Breadcrumb Crusted Chicken' },
    { value: 'chicken-panko-crusted', label: '🍗 Panko Crusted Chicken' },
    { value: 'chicken-cornflake-crusted', label: '🍗 Cornflake Crusted Chicken' },
    { value: 'chicken-potato-crusted', label: '🍗 Potato Crusted Chicken' },
    { value: 'chicken-sweet-potato-crusted', label: '🍗 Sweet Potato Crusted Chicken' },
    { value: 'chicken-yam-crusted', label: '🍗 Yam Crusted Chicken' },
    { value: 'chicken-taro-crusted', label: '🍗 Taro Crusted Chicken' },
    { value: 'chicken-cassava-crusted', label: '🍗 Cassava Crusted Chicken' },
    { value: 'chicken-plantain-crusted', label: '🍗 Plantain Crusted Chicken' },
    { value: 'chicken-banana-crusted', label: '🍗 Banana Crusted Chicken' },
    { value: 'chicken-coconut-crusted', label: '🍗 Coconut Crusted Chicken' },
    { value: 'chicken-almond-crusted', label: '🍗 Almond Crusted Chicken' },
    { value: 'chicken-cashew-crusted', label: '🍗 Cashew Crusted Chicken' },
    { value: 'chicken-peanut-crusted', label: '🍗 Peanut Crusted Chicken' },
    { value: 'chicken-walnut-crusted', label: '🍗 Walnut Crusted Chicken' },
    { value: 'chicken-pecan-crusted', label: '🍗 Pecan Crusted Chicken' },
    { value: 'chicken-pine-nut-crusted', label: '🍗 Pine Nut Crusted Chicken' },
    { value: 'chicken-pistachio-crusted', label: '🍗 Pistachio Crusted Chicken' },
    { value: 'chicken-macadamia-crusted', label: '🍗 Macadamia Crusted Chicken' },
    { value: 'chicken-brazil-nut-crusted', label: '🍗 Brazil Nut Crusted Chicken' },
    { value: 'chicken-hazelnut-crusted', label: '🍗 Hazelnut Crusted Chicken' },
    { value: 'chicken-chestnut-crusted', label: '🍗 Chestnut Crusted Chicken' },
    { value: 'chicken-acorn-crusted', label: '🍗 Acorn Crusted Chicken' },
    { value: 'chicken-seed-encrusted', label: '🍗 Seed Encrusted Chicken' },
    { value: 'chicken-herb-encrusted', label: '🍗 Herb Encrusted Chicken' },
    { value: 'chicken-spice-encrusted', label: '🍗 Spice Encrusted Chicken' },
    { value: 'chicken-nut-encrusted', label: '🍗 Nut Encrusted Chicken' },
    { value: 'chicken-grain-encrusted', label: '🍗 Grain Encrusted Chicken' },
    { value: 'chicken-breadcrumb-encrusted', label: '🍗 Breadcrumb Encrusted Chicken' },
    { value: 'chicken-panko-encrusted', label: '🍗 Panko Encrusted Chicken' },
    { value: 'chicken-cornflake-encrusted', label: '🍗 Cornflake Encrusted Chicken' },
    { value: 'chicken-potato-encrusted', label: '🍗 Potato Encrusted Chicken' },
    { value: 'chicken-sweet-potato-encrusted', label: '🍗 Sweet Potato Encrusted Chicken' },
    { value: 'chicken-yam-encrusted', label: '🍗 Yam Encrusted Chicken' },
    { value: 'chicken-taro-encrusted', label: '🍗 Taro Encrusted Chicken' },
    { value: 'chicken-cassava-encrusted', label: '🍗 Cassava Encrusted Chicken' },
    { value: 'chicken-plantain-encrusted', label: '🍗 Plantain Encrusted Chicken' },
    { value: 'chicken-banana-encrusted', label: '🍗 Banana Encrusted Chicken' },
    { value: 'chicken-coconut-encrusted', label: '🍗 Coconut Encrusted Chicken' },
    { value: 'chicken-almond-encrusted', label: '🍗 Almond Encrusted Chicken' },
    { value: 'chicken-cashew-encrusted', label: '🍗 Cashew Encrusted Chicken' },
    { value: 'chicken-peanut-encrusted', label: '🍗 Peanut Encrusted Chicken' },
    { value: 'chicken-walnut-encrusted', label: '🍗 Walnut Encrusted Chicken' },
    { value: 'chicken-pecan-encrusted', label: '🍗 Pecan Encrusted Chicken' },
    { value: 'chicken-pine-nut-encrusted', label: '🍗 Pine Nut Encrusted Chicken' },
    { value: 'chicken-pistachio-encrusted', label: '🍗 Pistachio Encrusted Chicken' },
    { value: 'chicken-macadamia-encrusted', label: '🍗 Macadamia Encrusted Chicken' },
    { value: 'chicken-brazil-nut-encrusted', label: '🍗 Brazil Nut Encrusted Chicken' },
    { value: 'chicken-hazelnut-encrusted', label: '🍗 Hazelnut Encrusted Chicken' },
    { value: 'chicken-chestnut-encrusted', label: '🍗 Chestnut Encrusted Chicken' },
    { value: 'chicken-acorn-encrusted', label: '🍗 Acorn Encrusted Chicken' },
    { value: 'chicken-seed-coated', label: '🍗 Seed Coated Chicken' },
    { value: 'chicken-herb-coated', label: '🍗 Herb Coated Chicken' },
    { value: 'chicken-spice-coated', label: '🍗 Spice Coated Chicken' },
    { value: 'chicken-nut-coated', label: '🍗 Nut Coated Chicken' },
    { value: 'chicken-grain-coated', label: '🍗 Grain Coated Chicken' },
    { value: 'chicken-breadcrumb-coated', label: '🍗 Breadcrumb Coated Chicken' },
    { value: 'chicken-panko-coated', label: '🍗 Panko Coated Chicken' },
    { value: 'chicken-cornflake-coated', label: '🍗 Cornflake Coated Chicken' },
    { value: 'chicken-potato-coated', label: '🍗 Potato Coated Chicken' },
    { value: 'chicken-sweet-potato-coated', label: '🍗 Sweet Potato Coated Chicken' },
    { value: 'chicken-yam-coated', label: '🍗 Yam Coated Chicken' },
    { value: 'chicken-taro-coated', label: '🍗 Taro Coated Chicken' },
    { value: 'chicken-cassava-coated', label: '🍗 Cassava Coated Chicken' },
    { value: 'chicken-plantain-coated', label: '🍗 Plantain Coated Chicken' },
    { value: 'chicken-banana-coated', label: '🍗 Banana Coated Chicken' },
    { value: 'chicken-coconut-coated', label: '🍗 Coconut Coated Chicken' },
    { value: 'chicken-almond-coated', label: '🍗 Almond Coated Chicken' },
    { value: 'chicken-cashew-coated', label: '🍗 Cashew Coated Chicken' },
    { value: 'chicken-peanut-coated', label: '🍗 Peanut Coated Chicken' },
    { value: 'chicken-walnut-coated', label: '🍗 Walnut Coated Chicken' },
    { value: 'chicken-pecan-coated', label: '🍗 Pecan Coated Chicken' },
    { value: 'chicken-pine-nut-coated', label: '🍗 Pine Nut Coated Chicken' },
    { value: 'chicken-pistachio-coated', label: '🍗 Pistachio Coated Chicken' },
    { value: 'chicken-macadamia-coated', label: '🍗 Macadamia Coated Chicken' },
    { value: 'chicken-brazil-nut-coated', label: '🍗 Brazil Nut Coated Chicken' },
    { value: 'chicken-hazelnut-coated', label: '🍗 Hazelnut Coated Chicken' },
    { value: 'chicken-chestnut-coated', label: '🍗 Chestnut Coated Chicken' },
    { value: 'chicken-acorn-coated', label: '🍗 Acorn Coated Chicken' },
    { value: 'chicken-seed-dusted', label: '🍗 Seed Dusted Chicken' },
    { value: 'chicken-herb-dusted', label: '🍗 Herb Dusted Chicken' },
    { value: 'chicken-spice-dusted', label: '🍗 Spice Dusted Chicken' },
    { value: 'chicken-nut-dusted', label: '🍗 Nut Dusted Chicken' },
    { value: 'chicken-grain-dusted', label: '🍗 Grain Dusted Chicken' },
    { value: 'chicken-breadcrumb-dusted', label: '🍗 Breadcrumb Dusted Chicken' },
    { value: 'chicken-panko-dusted', label: '🍗 Panko Dusted Chicken' },
    { value: 'chicken-cornflake-dusted', label: '🍗 Cornflake Dusted Chicken' },
    { value: 'chicken-potato-dusted', label: '🍗 Potato Dusted Chicken' },
    { value: 'chicken-sweet-potato-dusted', label: '🍗 Sweet Potato Dusted Chicken' },
    { value: 'chicken-yam-dusted', label: '🍗 Yam Dusted Chicken' },
    { value: 'chicken-taro-dusted', label: '🍗 Taro Dusted Chicken' },
    { value: 'chicken-cassava-dusted', label: '🍗 Cassava Dusted Chicken' },
    { value: 'chicken-plantain-dusted', label: '🍗 Plantain Dusted Chicken' },
    { value: 'chicken-banana-dusted', label: '🍗 Banana Dusted Chicken' },
    { value: 'chicken-coconut-dusted', label: '🍗 Coconut Dusted Chicken' },
    { value: 'chicken-almond-dusted', label: '🍗 Almond Dusted Chicken' },
    { value: 'chicken-cashew-dusted', label: '🍗 Cashew Dusted Chicken' },
    { value: 'chicken-peanut-dusted', label: '🍗 Peanut Dusted Chicken' },
    { value: 'chicken-walnut-dusted', label: '🍗 Walnut Dusted Chicken' },
    { value: 'chicken-pecan-dusted', label: '🍗 Pecan Dusted Chicken' },
    { value: 'chicken-pine-nut-dusted', label: '🍗 Pine Nut Dusted Chicken' },
    { value: 'chicken-pistachio-dusted', label: '🍗 Pistachio Dusted Chicken' },
    { value: 'chicken-macadamia-dusted', label: '🍗 Macadamia Dusted Chicken' },
    { value: 'chicken-brazil-nut-dusted', label: '🍗 Brazil Nut Dusted Chicken' },
    { value: 'chicken-hazelnut-dusted', label: '🍗 Hazelnut Dusted Chicken' },
    { value: 'chicken-chestnut-dusted', label: '🍗 Chestnut Dusted Chicken' },
    { value: 'chicken-acorn-dusted', label: '🍗 Acorn Dusted Chicken' }
  ]
}

export type RestaurantItemType = typeof RESTAURANT_ITEM_TYPES[string][number]

export function getRestaurantItemTypes(category: string): {value: string, label: string}[] {
  return RESTAURANT_ITEM_TYPES[category] || []
}

export function getRestaurantItemTypeByValue(category: string, value: string): RestaurantItemType | undefined {
  return RESTAURANT_ITEM_TYPES[category]?.find(itemType => itemType.value === value)
}

export function isRestaurantItemType(category: string, value: string): boolean {
  return RESTAURANT_ITEM_TYPES[category]?.some(itemType => itemType.value === value) || false
}

export function getAllRestaurantItemTypes(): typeof RESTAURANT_ITEM_TYPES {
  return RESTAURANT_ITEM_TYPES
}
