/**
 * Frontend Types - Auto-Generated from Backend DTOs
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated by: pnpm generate:frontend-types
 * Source: packages/schemas/src/dtos/*.dto.ts
 * 
 * This file is 100% reliable - generated directly from Zod schemas
 * No OpenAPI middleman, no SDK generation needed
 */

import type { z } from 'zod'

// Import Zod schemas from DTOs
import type { AuthResponseSchema, LoginInputSchema, SignupInputSchema, UserPublicResponseSchema } from '../../../../packages/schemas/src/dtos/auth.dto.js'
import type { CreateStoreInputSchema, StoreListResponseSchema, StoreQuerySchema, StoreResponseSchema, UpdateStoreInputSchema } from '../../../../packages/schemas/src/dtos/store.dto.js'
import type { CreateItemInputSchema, ItemListResponseSchema, ItemQuerySchema, ItemResponseSchema, UpdateItemInputSchema } from '../../../../packages/schemas/src/dtos/item.dto.js'
import type { AddToCartInputSchema, CartListResponseSchema, CartQuerySchema, CartResponseSchema, CreateCartInputSchema, UpdateCartInputSchema } from '../../../../packages/schemas/src/dtos/cart.dto.js'
import type { CreateOrderInputSchema, OrderListResponseSchema, OrderQuerySchema, OrderResponseSchema, UpdateOrderInputSchema, UpdateOrderStatusSchema } from '../../../../packages/schemas/src/dtos/order.dto.js'
import type { AddressListResponseSchema, AddressQuerySchema, AddressResponseSchema, CreateAddressInputSchema, UpdateAddressInputSchema } from '../../../../packages/schemas/src/dtos/address.dto.js'
import type { CreatePromotionInputSchema, PromotionListResponseSchema, PromotionQuerySchema, PromotionResponseSchema, UpdatePromotionInputSchema } from '../../../../packages/schemas/src/dtos/promotion.dto.js'
import type { CreateTipInputSchema, ProcessTipInputSchema, TipListResponseSchema, TipQuerySchema, TipResponseSchema, TipStatusUpdateSchema, UpdateTipInputSchema } from '../../../../packages/schemas/src/dtos/tip.dto.js'
import type { CreateUserInputSchema, UpdateUserInputSchema, UserListResponseSchema, UserQuerySchema, UserResponseSchema } from '../../../../packages/schemas/src/dtos/user.dto.js'
import type { CommentListResponseSchema, CommentQuerySchema, CommentResponseSchema, CreateCommentInputSchema, CreatePostInputSchema, LikePostInputSchema, MediaItemSchema, PostListResponseSchema, PostQuerySchema, PostResponseSchema, UnlikePostInputSchema } from '../../../../packages/schemas/src/dtos/river.dto.js'
import type { MediaListResponseSchema, MediaResponseSchema, UploadMediaInputSchema } from '../../../../packages/schemas/src/dtos/media.dto.js'
import type { ConnectAccountResponseSchema, ConnectAccountStatusSchema, CreateConnectAccountInputSchema, CreatePaymentIntentInputSchema, PaymentIntentResponseSchema, PaymentMethodListResponseSchema, PaymentMethodResponseSchema, StripeWebhookEventSchema } from '../../../../packages/schemas/src/dtos/payment.dto.js'

// ========================================
// Type Exports (inferred from Zod schemas)
// ========================================

// Auth Types
export type AuthResponse = z.infer<typeof AuthResponseSchema>
export type LoginInput = z.infer<typeof LoginInputSchema>
export type SignupInput = z.infer<typeof SignupInputSchema>
export type UserPublicResponse = z.infer<typeof UserPublicResponseSchema>

// Store Types
export type CreateStoreInput = z.infer<typeof CreateStoreInputSchema>
export type StoreListResponse = z.infer<typeof StoreListResponseSchema>
export type StoreQuery = z.infer<typeof StoreQuerySchema>
export type StoreResponse = z.infer<typeof StoreResponseSchema>
export type UpdateStoreInput = z.infer<typeof UpdateStoreInputSchema>

// Item Types
export type CreateItemInput = z.infer<typeof CreateItemInputSchema>
export type ItemListResponse = z.infer<typeof ItemListResponseSchema>
export type ItemQuery = z.infer<typeof ItemQuerySchema>
export type ItemResponse = z.infer<typeof ItemResponseSchema>
export type UpdateItemInput = z.infer<typeof UpdateItemInputSchema>

// Cart Types
export type AddToCartInput = z.infer<typeof AddToCartInputSchema>
export type CartListResponse = z.infer<typeof CartListResponseSchema>
export type CartQuery = z.infer<typeof CartQuerySchema>
export type CartResponse = z.infer<typeof CartResponseSchema>
export type CreateCartInput = z.infer<typeof CreateCartInputSchema>
export type UpdateCartInput = z.infer<typeof UpdateCartInputSchema>

// Order Types
export type CreateOrderInput = z.infer<typeof CreateOrderInputSchema>
export type OrderListResponse = z.infer<typeof OrderListResponseSchema>
export type OrderQuery = z.infer<typeof OrderQuerySchema>
export type OrderResponse = z.infer<typeof OrderResponseSchema>
export type UpdateOrderInput = z.infer<typeof UpdateOrderInputSchema>
export type UpdateOrderStatus = z.infer<typeof UpdateOrderStatusSchema>

// Address Types
export type AddressListResponse = z.infer<typeof AddressListResponseSchema>
export type AddressQuery = z.infer<typeof AddressQuerySchema>
export type AddressResponse = z.infer<typeof AddressResponseSchema>
export type CreateAddressInput = z.infer<typeof CreateAddressInputSchema>
export type UpdateAddressInput = z.infer<typeof UpdateAddressInputSchema>

// Promotion Types
export type CreatePromotionInput = z.infer<typeof CreatePromotionInputSchema>
export type PromotionListResponse = z.infer<typeof PromotionListResponseSchema>
export type PromotionQuery = z.infer<typeof PromotionQuerySchema>
export type PromotionResponse = z.infer<typeof PromotionResponseSchema>
export type UpdatePromotionInput = z.infer<typeof UpdatePromotionInputSchema>

// Tip Types
export type CreateTipInput = z.infer<typeof CreateTipInputSchema>
export type ProcessTipInput = z.infer<typeof ProcessTipInputSchema>
export type TipListResponse = z.infer<typeof TipListResponseSchema>
export type TipQuery = z.infer<typeof TipQuerySchema>
export type TipResponse = z.infer<typeof TipResponseSchema>
export type TipStatusUpdate = z.infer<typeof TipStatusUpdateSchema>
export type UpdateTipInput = z.infer<typeof UpdateTipInputSchema>

// User Types
export type CreateUserInput = z.infer<typeof CreateUserInputSchema>
export type UpdateUserInput = z.infer<typeof UpdateUserInputSchema>
export type UserListResponse = z.infer<typeof UserListResponseSchema>
export type UserQuery = z.infer<typeof UserQuerySchema>
export type UserResponse = z.infer<typeof UserResponseSchema>

// River Types
export type CommentListResponse = z.infer<typeof CommentListResponseSchema>
export type CommentQuery = z.infer<typeof CommentQuerySchema>
export type CommentResponse = z.infer<typeof CommentResponseSchema>
export type CreateCommentInput = z.infer<typeof CreateCommentInputSchema>
export type CreatePostInput = z.infer<typeof CreatePostInputSchema>
export type LikePostInput = z.infer<typeof LikePostInputSchema>
export type MediaItem = z.infer<typeof MediaItemSchema>
export type PostListResponse = z.infer<typeof PostListResponseSchema>
export type PostQuery = z.infer<typeof PostQuerySchema>
export type PostResponse = z.infer<typeof PostResponseSchema>
export type UnlikePostInput = z.infer<typeof UnlikePostInputSchema>

// Media Types
export type MediaListResponse = z.infer<typeof MediaListResponseSchema>
export type MediaResponse = z.infer<typeof MediaResponseSchema>
export type UploadMediaInput = z.infer<typeof UploadMediaInputSchema>

// Payment Types
export type ConnectAccountResponse = z.infer<typeof ConnectAccountResponseSchema>
export type ConnectAccountStatus = z.infer<typeof ConnectAccountStatusSchema>
export type CreateConnectAccountInput = z.infer<typeof CreateConnectAccountInputSchema>
export type CreatePaymentIntentInput = z.infer<typeof CreatePaymentIntentInputSchema>
export type PaymentIntentResponse = z.infer<typeof PaymentIntentResponseSchema>
export type PaymentMethodListResponse = z.infer<typeof PaymentMethodListResponseSchema>
export type PaymentMethodResponse = z.infer<typeof PaymentMethodResponseSchema>
export type StripeWebhookEvent = z.infer<typeof StripeWebhookEventSchema>

// ========================================
// Convenience Aliases
// ========================================

export type Store = StoreResponse
export type Item = ItemResponse
export type Cart = CartResponse
export type Order = OrderResponse
export type Address = AddressResponse
export type User = UserResponse
export type RiverPost = PostResponse
export type RiverComment = CommentResponse

// ========================================
// Enhanced Types
// ========================================

/** Store with calculated distance from user location */
export interface StoreWithDistance extends StoreResponse {
  distance?: number
}

/** Cart with calculated totals */
export interface CartWithTotals {
  id: string
  status?: string
  user?: string
  storeId?: string
  store?: string
  userId?: string
  note?: string
  order?: string
  items: CartItemData[]
  itemCount: number
  subtotal: number
  tax: number
  total: number
}

/** Cart item with populated item data */
export interface CartItemData {
  id: string
  cartId: string
  itemId: string
  item: Item
  quantity: number
  price: number
  options?: Record<string, unknown>
  specialInstructions?: string | null
}

/** Address snapshot for orders */
export interface AddressSnapshot {
  line1: string
  line2?: string
  city: string
  state: string
  postalCode: string
  country?: string
}

// Order status enum
export type OrderStatus =
  | 'PLACED'
  | 'ACCEPTED'
  | 'PREPARING'
  | 'READY'
  | 'OUT_FOR_DELIVERY'
  | 'COMPLETED'
  | 'CANCELED'

// MediaItem is already exported above in River Types section

// River filters
export interface RiverFilters {
  storeId?: string
  sortBy?: 'recent' | 'popular' | 'trending'
  hasMedia?: boolean
}
